### ISSUE TITLE
请问如何自己训练语料和自己配置词典？

### ISSUE THREAD

**Issue by fireflycsq** [shibing624/pycorrector#10]
词典中，AB型 3 n，3和n是什么意思

**Comment by fighting41love** [comment]
同问

**Comment by fighting41love** [comment]
如何加载自己用kenLM训练的模型？如何自己配置词典？求解。

**Comment by fighting41love** [comment]
d'd模型load已搞定，修改config.py中的language_model_path即可，词典还没搞懂。

**Comment by fighting41love** [comment]
数字可能是词频，n什么的代表词性。

**Comment by shibing624** [comment]
词典来源于：https://github.com/NLPchina/ansj_seg/tree/master/library ，3 是数字，n是词性（代表名词词性）

**Comment by shibing624** [comment]
暂时关闭，如有需求，feel free to reopen it, thx.
