### ISSUE TITLE
关于使用RNN_LM模型给字打分的疑惑

### ISSUE THREAD

**Issue by cabbageNoob** [shibing624/pycorrector#100]
前辈您好
1、我看到您在使用rnn_lm模型给句子每个字打分的函数，和下面计算句子整体困惑度的代码基本一样，那是不是可以理解为在使用rnn_lm模型时，您就是以困惑度为基准为每个字打分。
2、那如果最后得到的打分是字困惑度，那检测疑似错误字时候，通过平均值上下三倍标准差之间属于正常点，打分低于平均值值下三倍标准差会被认为是疑似错字。可困惑度越小不是准确度越高吗？
3、前辈可以简单解释一下在使用rnn_lm模型时，是怎么计算困惑度的吗？也就是lm.py文件中的char_scores函数和perplexity函数。看了许久，始终不明白困惑度怎么就被算出来了。

**Comment by shibing624** [comment]
1. 可以先了解一下统计模型中语言模型的困惑度计算方法，kenlm工具的实现比较具体，本质是该字或词出现在上下文中的似然概率值。
2. rnn实现的深度语言模型是一样的，只是实现上是序列的预测。

**Comment by brealisty** [comment]
> 前辈您好
> 1、我看到您在使用rnn_lm模型给句子每个字打分的函数，和下面计算句子整体困惑度的代码基本一样，那是不是可以理解为在使用rnn_lm模型时，您就是以困惑度为基准为每个字打分。
> 2、那如果最后得到的打分是字困惑度，那检测疑似错误字时候，通过平均值上下三倍标准差之间属于正常点，打分低于平均值值下三倍标准差会被认为是疑似错字。可困惑度越小不是准确度越高吗？
> 3、前辈可以简单解释一下在使用rnn_lm模型时，是怎么计算困惑度的吗？也就是lm.py文件中的char_scores函数和perplexity函数。看了许久，始终不明白困惑度怎么就被算出来了。

rnn_lm下好像并没有model文件

**Comment by cabbageNoob** [comment]
执行preprocess.py文件和train.py文件可生成rnn_lm模型
