### ISSUE TITLE
bert和seq2seq原理上的细节问题

### ISSUE THREAD

**Issue by brealisty** [shibing624/pycorrector#103]
看了大佬几个模型的readme，seq2seq,只是能够直接给出正确的结果，而不能够提示哪里错误在哪里，也就是one-stage这种模式，是这样吧？
我比较关心bert的模型，看了图片展示的结果，应该是能够判断错误的词/字,并且能够给出对应的修改意见，应该是属于two-stage——检错+纠错。那么检错部分，数据集的标签是如何标注的，输出是如何设计的？纠错部分也是按照首页，规则纠错的方式，分别尽力音近、形近等词库，然后利用语言模型给出比较符合的正确结果，这样进行的吗？

**Comment by shibing624** [comment]
1. 是
2. 具体可以看代码，有规则的，也有bert模型自动处理，目前是模型自动纠错。

**Comment by brealisty** [comment]
> 1. 是
> 2. 具体可以看代码，有规则的，也有bert模型自动处理，目前是模型自动纠错。

1、看了bert pytorch的代码，这一部分代码，都是预测阶段的代码，并没有模型搭建的输出设计，loss设计，等一系列训练阶段的代码。
2、有个地方比较奇怪，detect和correct两者都加载同一个模型，同一套权重（也就是correct同样用用以bert做语言模型），只是输入上稍有不同，为什么detect的输出就是一个带有[mask]的tokens，而correct输出是正确的值（两者都是self.model(input).）
另：没有找到readme中的pregenerate_training_data.py等文件，按照作者在另一个issue中提供的连接transformer，似乎也对应不上。

**Comment by shibing624** [comment]
transformer是项目在快速更新，紧跟版本人力不足，不过大体意思一致的，训练模型即可。
