### ISSUE TITLE
是否有考虑提升检测效率？

### ISSUE THREAD

**Issue by liyang-lomo** [shibing624/pycorrector#104]
检测效率太低了，几百字一篇文章卡半天

**Comment by shibing624** [comment]
规则的方法应该不会太慢，你是用哪种方法慢？可以具体介绍一下你的本地环境配置:cpu, 多少字花费多少时间？

**Comment by liyang-lomo** [comment]
是的，规则的文本快很多，大概70s五千字吧，直接放html页面进去会卡死

**Comment by liyang-lomo** [comment]
还有一个问题就是误报率比较高，有没有什么办法降低一下误报率呢

**Comment by liyang-lomo** [comment]
url:https://jianshu.com
corrected_sent我不要你花钱我要我出钱渠内流行一句话土豪公司才敢说
detail[['圈', '渠', 11, 12]]

corrected_sent沪公网安倍好
detail[['安备', '安倍', 3, 5], ['号', '好', 5, 6]]

像这种误报的非常多

**Comment by shibing624** [comment]
会修复，排期中，目前人力有限，慢慢来，欢迎pr

**Comment by shibing624** [comment]
fixed with https://github.com/shibing624/pycorrector/commit/34a5316a41eeea886f3bb2e5a2ce0e0c882f522d
