### ISSUE TITLE
语言模型与中文纠错模型怎么配合使用

### ISSUE THREAD

**Issue by ZengHorace** [shibing624/pycorrector#108]
作者大大，语言模型与中文纠错模型是啥区别啊，怎么配合用，我就理解了你说的中文纠错模型，输入一个有问题的句子，出来纠正后的句子，那么语言模型在这是怎么用啊

**Comment by shibing624** [comment]
理解一下语言模型的原理比较好，link: https://github.com/shibing624/pycorrector/wiki/%E7%BB%9F%E8%AE%A1%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B%E5%8E%9F%E7%90%86

**Comment by ZengHorace** [comment]
您发的链接我有看，它是可以做拼音到汉字的解码，但怎么应用到您说的中文纠错呢
