### ISSUE TITLE
训练kenlm 模型不切词可以吗

### ISSUE THREAD

**Issue by liyang-lomo** [shibing624/pycorrector#109]
训练kenlm 模型不切词可以吗？不切词是否会对检测效果有影响？
用人民日报库感觉误报率太高了，我打算用爬几个客户的网站数据来训练kenlm 模型，但不知道应该怎么切词。如果需要切词，能告诉我怎么切词吗？

**Comment by shibing624** [comment]
可以不切词，按字处理。
