### ISSUE TITLE
1. load word model报错 2. 关于char模型的误报

### ISSUE THREAD

**Issue by fighting41love** [shibing624/pycorrector#11]
1. 我修改了config.py，下载了您训练的word模型，准备load模型：
`language_model_path = 'data/kenlm/people2014corpus_words.klm'`
但爆出了错误，people2014corpus_words.klm
OSError: Cannot read model 'data/kenlm/people2014corpus_words.klm' (lm/read_arpa.cc:65 in void lm::ReadARPACounts(util::FilePiece&, std::vector<long unsigned int>&) threw FormatLoadException. first non-empty line was "<html>" not \data\. Byte: 7)

请问一下，您有试过word模型吗？是不是模型本身的格式问题，char模型，我load是没有问题的。

2. 使用char模型进行文本纠错，会出现很多把正确的句子改错的情况，举个例子：
借款额度可以提现吗 借款额度可以提现马： 把“吗”错误地改成了“马”
您怎么看待这个问题，是否要调节一下阈值threshold?

多谢了！

**Comment by fighting41love** [comment]
个人感觉是 char-level的模型，容易产生误报现象。。。

**Comment by shibing624** [comment]
1.我试过word模型，测试无问题，如果你是自己训练的word粒度语言模型，建议自己查错并解决。也可以下载我提供的word粒度语言模型，百度云盘有提供下载地址。
2.这种改错了的原因是模型准确率不够导致的，方法1）修改detect阶段错字识别阈值；2）给个纠错集及正确集，针对这种常见字过滤。

**Comment by fighting41love** [comment]
我是下载了您百度云盘中的word模型并load，报错，char模型不报错。。。
我自己train的word模型，也不报错。。。

**Comment by shibing624** [comment]
加载word粒度的模型，需要打开detector.py下18、19行注释，然后detecor.py下第51、61、120行的模型文件名称修改为word粒度的模型文件路径。corrector.py下的trigram_char 修改为trigram_word。

**Comment by fighting41love** [comment]
好滴，谢谢！

**Comment by cloudfool** [comment]
我尝试用云盘里的char模型替换默认的模型，可是程序报错“illegal instruction (core dumped)”, 你知道是什么原因么？谢谢。

**Comment by fighting41love** [comment]
个人的经验：不建议使用char模型来做纠错，误判率比较高（在我的语料上是这样的）
建议word-level model，用自己的语料训练。
char模型，我当时Load作者的model，没问题，没有遇到过你说的错误。
