### ISSUE TITLE
建微信群

### ISSUE THREAD

**Issue by li-aolong** [shibing624/pycorrector#110]
作者是不是先下载google提供的原始中文预训练模型，加语料微调，然后就直接进行检测与纠正，都是无监督训练，不需要标注的吧

**Comment by shibing624** [comment]
是。

**Comment by li-aolong** [comment]
@shibing624 想问下我想在现有bert模型基础上使用有标签的纠错句子对进行训练，应该怎样进行呢？

**Comment by li-aolong** [comment]
@shibing624 还有想问下作者能不能建个社群，可以让有相关兴趣的人即使讨论与分享

**Comment by sparkingarthur** [comment]
同意建社群

**Comment by shibing624** [comment]
哪位同学新建一个群，拉我就好。微信号：xuming624

**Comment by li-aolong** [comment]
群建好了，感兴趣的同学可以加一下
![image](https://user-images.githubusercontent.com/12003487/69050479-17fd9900-0a3d-11ea-8788-7a9898db2380.png)

**Comment by yingyueln** [comment]
@li-aolong 可以重新发一下群的二维码吗，以前那个已经过期了

**Comment by li-aolong** [comment]
@yingyueln 更新了，首页的readme也有
