### ISSUE TITLE
conv_seqtoseq 执行infer.py文件输出全为“的”，无法正常预测

### ISSUE THREAD

**Issue by XiaoTaiYang-8338** [shibing624/pycorrector#112]
eg:
S-8	会 能 够 大 幅 减 少 互 相 抱 怨 的 情 况 。
H-8	-4.699657917022705	的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的 的
P-8	-5.4797 -5.1852 -4.8052 -4.7773 -4.7814 -4.6970 -4.6841 -4.6774 -4.6618 -4.7146 -4.6164 -4.7154 -4.7329 -4.7249 -4.7032 -4.6161 -4.6866 -4.6403 -4.6600 -4.6852 -4.6137 -4.7548 -4.6602 -4.6549 -4.7024 -4.6478 -4.6790 -4.6844 -4.6708 -4.6846 -4.7449 -4.6806 -4.7088 -4.6991 -4.6523 -4.7013 -4.7583 -4.6713 -4.6557 -4.6331 -4.6350 -4.7072 -4.7323 -4.6543 -4.7052 -4.6844 -4.6520 -4.6738 -4.6875 -4.6980 -4.7527 -4.6269 -4.6669 -4.7675 -4.6874 -4.6414 -4.7057 -4.6603 -4.6679 -4.6360 -4.7030 -4.6357 -4.7288 -4.7456 -4.6945 -4.6915 -4.6242 -4.7213 -4.6547 -4.6866 -4.7542 -4.6557 -4.6075 -4.6338 -4.6102 -4.7516 -4.6155 -4.7081 -4.7718 -4.7660 -4.7538 -4.7057 -4.7046 -4.6920 -4.6729 -4.6665 -4.6060 -4.6683 -4.6700 -4.7200 -4.6593 -4.6398 -4.7263 -4.6647 -4.6511 -4.7316 -4.7064 -4.7038 -4.7134 -4.6975 -4.7143 -4.6559 -4.7231 -4.6839 -4.6542 -4.6917 -4.7428 -4.8106 -4.6603 -4.7211 -4.6991 -4.6793 -4.6970 -4.7039 -4.7880 -4.6992 -4.6746 -4.6664 -4.7322 -4.6368 -4.6530 -4.6957 -4.6770 -4.6403 -4.6837 -4.6402 -4.6964 -4.7203 -4.6896 -4.6562 -4.7435 -4.6492 -4.7642 -4.6599 -4.7485 -4.7103 -4.7495 -4.7127 -4.7089 -4.7105 -4.7000 -4.6740 -4.6686 -4.7112 -4.6416 -4.6921 -4.7201 -4.7570 -4.6422 -4.7000 -4.6833 -4.7191 -4.6045 -4.6797 -4.7267 -4.6633 -4.6573 -4.6649 -4.6601 -4.7028 -4.7067 -4.8274 -4.6387 -4.6719 -4.6939 -4.6845 -4.6846 -4.7194 -4.6843 -4.6933 -4.7406 -4.6565 -4.6905 -4.6287 -4.6791 -4.6163 -4.6697 -4.7007 -4.6651 -4.6807 -4.6541 -4.6440 -4.6978 -4.7203 -4.7137 -4.6628 -4.7479 -4.6758 -4.7293 -4.6738 -4.7213 -4.7535 -4.6710 -4.6913 -4.7386 -4.6687 -4.7237 -4.6932 -4.6016 -4.6688 -5.3757
你好，预测结果全为“的”，这个问题有出现吗？

**Comment by shibing624** [comment]
训练不足，继续跑，不要着急。epochs=40轮左右可以看到效果

**Comment by shm007g** [comment]
@shibing624 可以上传你基于NLPCC2018CGEC数据集训练好的模型么？
