### ISSUE TITLE
请问 rnn_lm 提供的预训练的模型在哪下载

### ISSUE THREAD

**Issue by loserdog-err** [shibing624/pycorrector#113]
![image](https://user-images.githubusercontent.com/13502799/69023464-d4357000-09f9-11ea-8187-06f857bf582e.png)
根据文档说提供了个训练好的模型，请问哪里下载，还是要自己训练呢。

**Comment by shibing624** [comment]
。。。发现训练的模型效果不好，就没提交，我改下readme

**Comment by loserdog-err** [comment]
好吧:sweat_smile:
