### ISSUE TITLE
训练bert模型中的两个方法是否能提供出来

### ISSUE THREAD

**Issue by bigzhouj** [shibing624/pycorrector#115]
python pregenerate_training_data.py 
python finetune_on_pregenerated.py
谢谢！！

**Comment by shibing624** [comment]
提供了呀

**Comment by bigzhouj** [comment]
啊，我在项目里面没有发现呢，能否给个路径，谢谢！

**Comment by shibing624** [comment]
https://github.com/huggingface/transformers

**Comment by bigzhouj** [comment]
run_lm_finetuning.py  里面没有这两个方法，项目里面也没有。。。

**Comment by shibing624** [comment]
https://github.com/huggingface/transformers/blob/master/examples/run_lm_finetuning.py
