### ISSUE TITLE
 代码版本？

### ISSUE THREAD

**Issue by orangetwo** [shibing624/pycorrector#12]
请教下  用pip安装下 在___init__文件下
def get_confusion_char_set(c):
    confusion_char_set = get_same_pinyin(c)  # .union(get_same_stroke(c))
    if not confusion_char_set:
        confusion_char_set = set()
    return confusion_char_set
与您现在的 公布的代码
def get_confusion_char_set(c):
    confusion_char_set = get_same_pinyin(c).union(get_same_stroke(c))
    if not confusion_char_set:
        confusion_char_set = set()
    return confusion_char_set

这里有些不一样 是不是版本的问题呢 ？

**Comment by shibing624** [comment]
是版本不一致导致的。请用最新版本代码。
