### ISSUE TITLE
No module named 'fairseq.fb_pathmgr'

### ISSUE THREAD

**Issue by martinchai16** [shibing624/pycorrector#121]
你好，我用conv_seq2seq训练时，跑了一个epoch后出现Module not Found错误，具体错误内容：No module named 'fairseq.fb_pathmgr'
我的fairseq是0.9.0，现在从0.9.0降到0.8.0然后到0.7.2，一直出现这个错误，查了fairseq的作者源，有相同的issue，但是作者说应该已经解决了，但实际上并没有。。请问下作者，你用conv_seq2seq训过吗，有没有碰到我这种错误。。

**Comment by shibing624** [comment]
fairseq==0.7.2
