### ISSUE TITLE
语言模型困惑度得分的原理是啥呢

### ISSUE THREAD

**Issue by pk3725069** [shibing624/pycorrector#124]
### Describe the Question
hi 感谢开源分享，我想问问一个问题
    def ppl_score(self, words):
        """
        取语言模型困惑度得分，越小句子越通顺
        :param words: list, 以词或字切分
        :return:
        """
        self.check_detector_initialized()
        return self.lm.perplexity(' '.join(words))
我看“self.lm.perplexity(' '.join(words))” 
把会把句子中所有词输入，输出的分数是啥呢？
若是n-gram，是多个条件概率之和？

**Comment by yudong27** [comment]
首先你要看困惑度的定义，困惑度=1/句子出现的概率，参考这个[困惑度](https://zhuanlan.zhihu.com/p/44107044)
通常来讲，困惑度应该是各个词语出现概率（条件概率）之积，但实际应用中用log(P)代替P，这样P=p1*p2...pn转成log(P)=log(p1)+log(p2)...log(pn)，我们就看到了加法运算
