### ISSUE TITLE
kenlm 安装出错

### ISSUE THREAD

**Issue by Apollo2Mars** [shibing624/pycorrector#126]
ERROR: Command errored out with exit status 1:
     command: /export/home/sunhongchao1/anaconda3/envs/tf_base/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f1alr7il/kenlm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f1alr7il/kenlm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5d5y7cv5/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-f1alr7il/kenlm/
    Complete output (12 lines):
    running install
    running build
    running build_ext
    building 'kenlm' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/util
    creating build/temp.linux-x86_64-3.6/lm
    creating build/temp.linux-x86_64-3.6/util/double-conversion
    creating build/temp.linux-x86_64-3.6/python
    gcc -pthread -B /export/home/sunhongchao1/anaconda3/envs/tf_base/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I. -I/export/home/sunhongchao1/anaconda3/envs/tf_base/include/python3.6m -c util/file_piece.cc -o build/temp.linux-x86_64-3.6/util/file_piece.o -O3 -DNDEBUG -DKENLM_MAX_ORDER=6 -std=c++11
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /export/home/sunhongchao1/anaconda3/envs/tf_base/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-f1alr7il/kenlm/setup.py'"'"'; __file__='"'"'/tmp/pip-install-f1alr7il/kenlm/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-5d5y7cv5/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/wiki/Install-Kenlm(%E5%AE%89%E8%A3%85kenlm)
