### ISSUE TITLE
Please add the python version limited

### ISSUE THREAD

**Issue by OwenLuo123** [shibing624/pycorrector#127]
In my using case, 
1. I use python 3.5 to run the example code and I meet the bug "TypeError: join() argument must be str or bytes, not 'PosixPath' "because It does not support on python 3.5.
2. I use python 3.7 to run python setup.py install and I meet the bug "error: ‘PyThreadState {aka struct _ts}’ has no member named ‘exc_traceback’; did you mean ‘curexc_traceback’?" which causes is not support on python 3.7.

Last... I use python 3.6 everything is good!

**Comment by shibing624** [comment]
done
