### ISSUE TITLE
请教transformer模型，用130w数据需要训练多少步？

### ISSUE THREAD

**Issue by hxyshare** [shibing624/pycorrector#129]
### Describe the Question
我使用batch size为128，130w数据大概10w个step可以训练完成。也就是10w step大约是一个epoch，那么是不是需要训练40个epoch大概400w步模型才可以收敛。

**Comment by hxyshare** [comment]
loss不降没有关系吗。一直在1.3左右震荡。

**Comment by Irisleaf** [comment]
能问下你跑起来了嘛？能问一下tensorflow版本和OpenNMT_tf的版本吗

**Comment by shibing624** [comment]
tensorflow>=2.0.0 # tensorflow-gpu>=2.0.0
transformers>=2.2.1
OpenNMT-tf==2.4.0
