### ISSUE TITLE
自动安装失败

### ISSUE THREAD

**Issue by djk111** [shibing624/pycorrector#13]
error: can't copy 'pycorrector/data/kenlm': doesn't exist or not a regular file

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-D4lnto/pycorrector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kGC_ZP/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-D4lnto/pycorrector/
这是怎么回事，求解答，谢谢！

**Comment by shibing624** [comment]
暂不支持win，抱歉，原因是kenlm这个库需要.so文件支持，后续改为TensorFlow版本的rnn语言模型可以摆脱kenlm库了，届时win上就可以支持了。
mac和linux都支持。

**Comment by djk111** [comment]
可是我是在Linux上安装的pycorretor啊，还是保错
error: can't copy 'pycorrector/data/kenlm': doesn't exist or not a regular file
我该怎么解决？谢谢了

**Comment by shibing624** [comment]
文件大约20MB，重新试一下。建议直接从源码安装吧。

**Comment by djk111** [comment]
我无论自动安装还是源码安装均失败，烦请大佬检查是这个项目安装是不是有问题啊
源码安装error: can't copy 'pycorrector/data/test': doesn't exist or not a regular file
自动安装error: can't copy 'pycorrector/data/kenlm': doesn't exist or not a regular file
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-JCu7Lc/pycorrector/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-Qpahys/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-JCu7Lc/pycorrector/

**Comment by hxh123** [comment]
Here: https://github.com/shibing624/pycorrector/issues/17#issuecomment-414884588

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话重新open，我来跟进。

**Comment by shibing624** [comment]
后续可以考虑升级，年前完成吧。

**Comment by HiIcy** [comment]
请问现在win10可以了吗
