### ISSUE TITLE
deep context的KeyError问题

### ISSUE THREAD

**Issue by hdzx68** [shibing624/pycorrector#130]
deep context运行出错，请问怎么解决？
Traceback (most recent call last):
  File "train.py", line 178, in <module>
    config.gpu_id)
  File "train.py", line 119, in train
    for batch in iterator:
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torchtext\data\iterator.py", line 156, in __iter__
    yield Batch(minibatch, self.dataset, self.device)
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torchtext\data\batch.py", line 34, in __init__
    setattr(self, name, field.process(batch, device=device))
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torchtext\data\field.py", line 237, in process
    tensor = self.numericalize(padded, device=device)
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torchtext\data\field.py", line 336, in numericalize
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torchtext\data\field.py", line 336, in <listcomp>
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
  File "d:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torchtext\data\field.py", line 336, in <listcomp>
    arr = [[self.vocab.stoi[x] for x in ex] for ex in arr]
KeyError: '搁'

**Comment by liuxinyu41** [comment]
遇见了相同的问题，同求帮助

**Comment by shibing624** [comment]
fix.

**Comment by htt6** [comment]
有相同的问题，请求帮助！

**Comment by hdzx68** [comment]
构建词表时将频度低于10（具体数字忘了）过滤了，所以导致那个问题，需要将过滤的词统一用一种字符表示，或者把频度阈值设为0
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "htt6"<notifications@github.com&gt;; 
发送时间: 2020年6月4日(星期四) 中午12:27
收件人: "shibing624/pycorrector"<pycorrector@noreply.github.com&gt;; 
抄送: "1071213991"<1071213991@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shibing624/pycorrector] deep context的KeyError问题 (#130)





 
有相同的问题，请求帮助！

**Comment by htt6** [comment]
谢谢回复！



---原始邮件---
发件人: "hdzx68"<notifications@github.com&gt;
发送时间: 2020年6月7日(周日) 中午1:27
收件人: "shibing624/pycorrector"<pycorrector@noreply.github.com&gt;;
抄送: "htt6"<243444788@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题: Re: [shibing624/pycorrector] deep context的KeyError问题 (#130)




 构建词表时将频度低于10（具体数字忘了）过滤了，所以导致那个问题，需要将过滤的词统一用一种字符表示，或者把频度阈值设为0 
   
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: "htt6"<notifications@github.com&amp;gt;;  
 发送时间: 2020年6月4日(星期四) 中午12:27 
 收件人: "shibing624/pycorrector"<pycorrector@noreply.github.com&amp;gt;;  
 抄送: "1071213991"<1071213991@qq.com&amp;gt;; "Author"<author@noreply.github.com&amp;gt;;  
 主题: Re: [shibing624/pycorrector] deep context的KeyError问题 (#130) 
 
 
 
 
 
   
 有相同的问题，请求帮助！

**Comment by shibing624** [comment]
pip install torchtext==0.3.0

**Comment by hdzx68** [comment]
谢谢
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "xuming"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 下午2:03
收件人: "shibing624/pycorrector"<pycorrector@noreply.github.com&gt;; 
抄送: "1071213991"<1071213991@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [shibing624/pycorrector] deep context的KeyError问题 (#130)





 
pip install torchtext==0.3.0
