### ISSUE TITLE
关于专有名词的使用问题及疑惑

### ISSUE THREAD

**Issue by biihgzcer** [shibing624/pycorrector#131]
### 问题描述
在使用pycorrector对于office word里的内容进行纠错的时候，发现pycorrector使用kenlm对字进行校验判断的时候存在误判，主要集中在人名和专有名词。

### 问题截图

![改正后的图](https://user-images.githubusercontent.com/25925377/75609840-d786de80-5b46-11ea-86ad-628a91799a35.png)
![改正后的图](https://user-images.githubusercontent.com/25925377/75609845-ed949f00-5b46-11ea-94bc-9003f9ac0bff.png)

### Describe your attempts

1. 如果打开字粒度我把具体的名字加入到people_name.txt，debug发现仍然没有用，使用kenlm模型打分仍然会把名字中的某个字改了，如图上

2. 我目前修正的文章是段落作为输入调用correct方法，阅读您的文档中在想将整个文章作为输入是否能有所改善？

3. kenlm模型用的默认的，想问下是否有办法合并二进制文件，或者有方式下载2.8G模型的原文件？
4. 微信群您建议使用ner，但是不知道具体如何应用，是修改pycorrector源码还是直接就可以应用？
5. jieba另外一种分词方式能够提供词性标注；这种是否可以应用在pycorrector中，即通过词性判断是否是专有名词，这种方式是否和ner有关？具体代码示例如下：
`>>> import jieba
>>> import jieba.posseg as pseg
>>> words = pseg.cut("我爱北京天安门") #jieba默认模式
>>> jieba.enable_paddle() #启动paddle模式。 0.40版之后开始支持，早期版本不支持
>>> words = pseg.cut("我爱北京天安门",use_paddle=True) #paddle模式
>>> for word, flag in words:
...    print('%s %s' % (word, flag))
...
我 r
爱 v
北京 ns
天安门 ns`
综上，目前的目的是降低误判率，提升改正的正确率

原文：
`发行人共同实际控制人肖[萧改成肖]华、霍荣铨、邓啟棠、张旗康分别承诺：“自公司股票上市之日起三十六个月内，不转让或者委托他人管理本人直接或间接持有的公司公开发行股票前已持有的公司股份，也不由公司回购本人直接或间接持有的公司公开发行股票前已持有的股份；于上述禁售期满后，在担任公司董事、监事或高级管理人员的任职期间，每年转让的股份不超过本人所持有公司股份总数的 25%，在离职后半年内不转让所持有的公司股份；在申报离职六个月后的十二个月内，通过证券交易所挂牌交易出售公司股票数量占本人所持有公司股票总数的比例不超过 50%；所持公司股票在锁定期满后两年内减持的，其减持价格不低于公司首次公开发行股票时的发行价；如果因派发现金红利、送股、转增股本、增发新股等原因进行除权、除息的，应按照中国证券监督管理委员会、深圳证券交易所的有关规定相应调整减持价格的下限；公司上市后 6 个月内如公司股票连续 20 个交易日的收盘价均低于公司首次公开发行股票时的发行价，或者上市后 6 个月期末收盘价低于公司首次公开发行股票时的发行价，本人持有公司股票的锁定期限自动延长 6  个月；如果因派发现金红利、送股、转增股本、增发新股等原因进行除权、除息的，须按照中国证券监督管理委员会、深圳证券交易所的有关规定相应调整减持价格的下限。上述承诺内容及[系改成及]本人真实意思表示，本人自愿接受监管机构、自律组织及社会公众的监督，若违反上述承诺，本人将依法承担相应责任。`

**Comment by shibing624** [comment]
补充一下图和文字case。

**Comment by shibing624** [comment]
1.错误可以通过补充混淆集字典修复，具体应用见：https://github.com/shibing624/pycorrector/commit/f27a88b4e94a948ba6bafd4cab11b7060fa30c85

**Comment by biihgzcer** [comment]
收到，感谢明哥，我进行一些测试！
