### ISSUE TITLE
bert_model

### ISSUE THREAD

**Issue by shnn217** [shibing624/pycorrector#134]
下載以後，在data/bert_model底下沒有預訓練好的模型，在readme的網址也不存在了，希望能提供你們fine-tune以後的模型，感謝

**Comment by shibing624** [comment]
done, see bert/readme

**Comment by shnn217** [comment]
sorry, but https://pan.baidu.com/s/14E7jtEgEtxWnwcggRBWeiw this website i
still got an error message , its always transfer to
https://pan.baidu.com/error/404.html , says the page no longer exists.

xuming <notifications@github.com> 於 2020年3月18日 週三 上午10:00寫道：
