### ISSUE TITLE
module 'pycorrector' has no attribute 'enable_char_error'

### ISSUE THREAD

**Issue by v-yunbin** [shibing624/pycorrector#135]
### Describe the Question
```
Traceback (most recent call last):
  File "correct_txt.py", line 25, in <module>
    main(inputfile,outfile)
  File "correct_txt.py", line 15, in main
    pycorrector.enable_char_error(enable=False)
AttributeError: module 'pycorrector' has no attribute 'enable_char_error'
```
### Describe your attempts
无法关闭字粒度的情况下，使用纠错：
正确文本：寻找诗与田野
识别文本：寻找诗与天眼
纠正文本：寻找诗与大宴

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.
version 0.24

**Comment by shibing624** [comment]
更新代码试试，错误未复现。original sentence:寻找诗与田野 => correct sentence:('寻找诗与田野', [])

**Comment by v-yunbin** [comment]
抱歉啊，又有新的错误：
```
Traceback (most recent call last):
  File "correct_txt.py", line 5, in <module>
    import pycorrector
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pycorrector-0.2.4-py3
.7.egg\pycorrector\__init__.py", line 7, in <module>
    from .en_spell import en_correct
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pycorrector-0.2.4-py3
.7.egg\pycorrector\en_spell.py", line 16, in <module>
    WORDS = Counter(words(open(path).read()))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrato
r\\Anaconda3\\lib\\site-packages\\pycorrector-0.2.4-py3.7.egg\\pycorrector\\data
/en/big.txt'
```

**Comment by shibing624** [comment]
update to pycorrector-0.2.5

**Comment by v-yunbin** [comment]
@shibing624 maybe you not read me, I mean:
met error1 with version 0.2.4:
`Traceback (most recent call last):
  File "correct_txt.py", line 25, in <module>
    main(inputfile,outfile)
  File "correct_txt.py", line 15, in main
    pycorrector.enable_char_error(enable=False)
AttributeError: module 'pycorrector' has no attribute 'enable_char_error'`
however, met error2with version 0.2.5:
`  File "correct_txt.py", line 5, in <module>
    import pycorrector
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pycorrector-0.2.4-py3
.7.egg\pycorrector\__init__.py", line 7, in <module>
    from .en_spell import en_correct
  File "C:\Users\Administrator\Anaconda3\lib\site-packages\pycorrector-0.2.4-py3
.7.egg\pycorrector\en_spell.py", line 16, in <module>
    WORDS = Counter(words(open(path).read()))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Administrato
r\\Anaconda3\\lib\\site-packages\\pycorrector-0.2.4-py3.7.egg\\pycorrector\\data
/en/big.txt'`

**Comment by shibing624** [comment]
update to pycorrector-0.2.6. update setup

**Comment by v-yunbin** [comment]
@shibing624 3ks，it works and it‘’s a great tool
But it seems that there is no promotionfor my jobs，total errors increased：
1. Before optimization
![image](https://user-images.githubusercontent.com/38179632/77043302-362dd280-69f8-11ea-836d-1eafcd80436e.png)
2. after  optimization with the tool
![image](https://user-images.githubusercontent.com/38179632/77043380-65444400-69f8-11ea-9160-d8ee205b1c9e.png)

**Comment by shibing624** [comment]
Maybe it's about confusing dictionaries, rule's method depends on data source. I update the default confusion dict, and you can update it too. see examples/use_custom_confusion.py

**Comment by v-yunbin** [comment]
@shibing624 i use myself lm model, how to set "enable_char_error=False"

**Comment by shibing624** [comment]
readme可以读一遍。  https://github.com/shibing624/pycorrector/blob/master/examples/disable_char_error.py
