### ISSUE TITLE
请问，怎么做eval_corpus.json这样的数据集呢？

### ISSUE THREAD

**Issue by yeyuling1990** [shibing624/pycorrector#136]
{
        "text": "讲台上放着一只漂亮的刚笔。",
        "correction": "讲台上放着一只漂亮的钢笔。",
        "errors": [
            [
                "刚",
                "钢",
                10,
                11
            ]
        ]
    },

**Comment by shibing624** [comment]
1.手动写代码生成的json文件，具体代码见pycorrector/utils/eval.py，功能包括：生成评估样本集，评估准召率。
2.标准样本数据格式见CGED的样本，可自行扩展数据样本。
