### ISSUE TITLE
Bert纠错使用贪心解码效果有改善

### ISSUE THREAD

**Issue by cabbageNoob** [shibing624/pycorrector#139]
- [ ] I checked to make sure that this is not a duplicate issue
- [ ] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/shibing624/pycorrector))

### Additional Information
Other things you want the developers to know.

**Comment by cabbageNoob** [comment]
![image](https://user-images.githubusercontent.com/42823417/79222968-140a6180-7e8b-11ea-9d66-4f108a8db5eb.png)

**Comment by shibing624** [comment]
update, 准召率评估提升1%，thanks. https://github.com/shibing624/pycorrector/issues/139
