### ISSUE TITLE
下载了您的word粒度模型，NLP小白想请教您几个问题。

### ISSUE THREAD

**Issue by yuhc0721** [shibing624/pycorrector#14]
（1）“【s】”   和   “【/s】”符号代表着什么意思？这里三角号打不出来....
（2）每行数据的第一个数字代表的是该词数量的log10统计概率吗？
（3）需要 对文本进行怎样的预处理？我参考您的博客只进行分词了，需不需要每句都要添加句子起止符？

**Comment by shibing624** [comment]
1)词性。
2）你是指分词的词表吗？代表词频。
3）不需要特别的预处理。用word粒度的需要分词，不用加起止符号。

**Comment by yuhc0721** [comment]
感谢回复！！！还想问您几个。。。希望您不忙的时候帮忙看一下哈
（1）字粒度是不是就对语料去除一些特殊符号，保留常用的标点符号就可以了？因为我自己训练了一个字粒度，把每个字都分开了，效果好差。
（2）我现在想用找错功能，来检测游戏领域的文本。但用我自己训练好的模型（中文维基语料）效果很差（字、词）都是，很多误筛。这种情况下，我是应该增大语料库大小，还是换语料？
（3）您能讲解下字粒度部分的筛错思想吗？之前看其他问题上您说过会写在博客上。。但没找到

**Comment by shibing624** [comment]
1）是。
2）建议通用语料+领域内语料结合训练，效果不够建议根据具体情况修改。建议：a.过滤通用字词表；b.过滤高频字词表；c.适度调整错误检测的阈值（具体是detector.py中的threshold=1.4）d.优化错误修改的方法（具体是corrector.py中的纠错集生成方法_generate_items）e.补充形似、音似词表 f.添加纠错映射词表。
3）这个博客。。。等等哈。

**Comment by yuhc0721** [comment]
非常感谢！
