### ISSUE TITLE
运行bert模块的代码core dumped

### ISSUE THREAD

**Issue by gubinbin123** [shibing624/pycorrector#141]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

### To Reproduce
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) here. We hope we can simply copy/paste/run it. It is also nice to share a hosted runnable script (e.g. Google Colab), especially for hardware-related problems.

### Describe your attempts
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
tf2.0以上，transformers>=2.2.1

**Comment by gubinbin123** [comment]
非常感谢回复，我升级了tensorflow之后程序能够运行了。transformer貌似应该至少大于2.2.1，因为2.2.1的版本没有pipeline模块，我transformer用的是2.4.0。
