### ISSUE TITLE
预测输出<unk>

### ISSUE THREAD

**Issue by tongchangD** [shibing624/pycorrector#142]
测试，运行infer.py出现如下bug，输出<unk>，没有数据
显示如下：
\<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> 
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>
\<unk>
\<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk> \<unk>

不知道是传入的数据问题还是代码存在一部分小问题，如能解决，不胜感激

**Comment by shibing624** [comment]
哪个模型？

**Comment by tongchangD** [comment]
是transformer那个模型

**Comment by shibing624** [comment]
fixed.

**Comment by tongchangD** [comment]
> fixed.

谢谢，我去瞅瞅
