### ISSUE TITLE
bert 运行时提示 unable to parse modelcard.json

### ISSUE THREAD

**Issue by BigWavelet** [shibing624/pycorrector#147]
win10 python3.6.5
运行python bert_corrector.py后报错
```
 python bert_corrector.py
2020-06-09 20:13:31.892959: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "bert_corrector.py", line 79, in <module>
    d = BertCorrector()
  File "bert_corrector.py", line 29, in __init__
    tokenizer=bert_model_dir)
  File "C:\Users\ydbn2153\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\pipelines.py", line 1799, in pipeline
    modelcard = ModelCard.from_pretrained(modelcard)
  File "C:\Users\ydbn2153\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\modelcard.py", line 153, in from_pretrained
    model_card_file, cache_dir=cache_dir, force_download=True, proxies=proxies, resume_download=False
  File "C:\Users\ydbn2153\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\file_utils.py", line 270, in cached_path
    raise ValueError("unable to parse {} as a URL or as a local path".format(url_or_filename))
ValueError: unable to parse D:\dev\nlp\Corrector\pycorrector\pycorrector\bert\./../data/bert_models/chinese_finetuned_lm/modelcard.json as a URL or as a local path
```

其中fine-tuned lm已经下载并放入对应的目录，文件列表为：
```shell
bert_config.json
config.json
pytorch_model.bin
vocab.txt
```

没有报错里提到的modelcard.json

求助

**Comment by shibing624** [comment]
对应transformers版本，自动忽略。

**Comment by gdh756462786** [comment]
@BigWavelet 大佬，微调bert是pytorch版本吗？

**Comment by mengtiantm** [comment]
使用bert模型时遇到同样的问题，请问解决了嘛？我使用的TensorFlow2.2.0，transformers3.0.0，“对应transformers版本，自动忽略。”什么意思，求助

**Comment by shibing624** [comment]
transformers==2.10.0

**Comment by mengtiantm** [comment]
分别将tf和transformers版本改成了TensorFlow2.0.0，transformers2.10.0，依然报错，如下：
Traceback (most recent call last):
  File "tests\bert_corrector_test.py", line 58, in <module>
    bertCorrector = bert_corrector.BertCorrector()
  File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\pycorrector-0.2.8-py
3.7.egg\pycorrector\bert\bert_corrector.py", line 29, in __init__
    tokenizer=bert_model_dir)
  File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\pipelin
es.py", line 1798, in pipeline
    modelcard = ModelCard.from_pretrained(modelcard)
  File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\modelca
rd.py", line 153, in from_pretrained
    model_card_file, cache_dir=cache_dir, force_download=True, proxies=proxies,
resume_download=False
  File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\file_ut
ils.py", line 269, in cached_path
    raise ValueError("unable to parse {} as a URL or as a local path".format(url
_or_filename))
ValueError: unable to parse D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\
pycorrector-0.2.8-py3.7.egg\pycorrector\bert\../data/bert_models/chinese_finetun
ed_lm/modelcard.json as a URL or as a local path

**Comment by Baililily** [comment]
您的问题解决了吗，我也遇到了这个问题，transforms的版本改到了2.10.0还是报这个错误

**Comment by WenRichard** [comment]
> win10 python3.6.5
> 运行python bert_corrector.py后报错
> 
> ```
>  python bert_corrector.py
> 2020-06-09 20:13:31.892959: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
> Traceback (most recent call last):
>   File "bert_corrector.py", line 79, in <module>
>     d = BertCorrector()
>   File "bert_corrector.py", line 29, in __init__
>     tokenizer=bert_model_dir)
>   File "C:\Users\ydbn2153\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\pipelines.py", line 1799, in pipeline
>     modelcard = ModelCard.from_pretrained(modelcard)
>   File "C:\Users\ydbn2153\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\modelcard.py", line 153, in from_pretrained
>     model_card_file, cache_dir=cache_dir, force_download=True, proxies=proxies, resume_download=False
>   File "C:\Users\ydbn2153\AppData\Local\Programs\Python\Python36\lib\site-packages\transformers\file_utils.py", line 270, in cached_path
>     raise ValueError("unable to parse {} as a URL or as a local path".format(url_or_filename))
> ValueError: unable to parse D:\dev\nlp\Corrector\pycorrector\pycorrector\bert\./../data/bert_models/chinese_finetuned_lm/modelcard.json as a URL or as a local path
> ```
> 
> 其中fine-tuned lm已经下载并放入对应的目录，文件列表为：
> 
> ```shell
> bert_config.json
> config.json
> pytorch_model.bin
> vocab.txt
> ```
> 
> 没有报错里提到的modelcard.json
> 
> 求助

文件读取地址不太对，注释pwd_path=‘’试试，我这边是成功运行了

**Comment by WenRichard** [comment]
> 分别将tf和transformers版本改成了TensorFlow2.0.0，transformers2.10.0，依然报错，如下：
> Traceback (most recent call last):
> File "tests\bert_corrector_test.py", line 58, in
> bertCorrector = bert_corrector.BertCorrector()
> File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\pycorrector-0.2.8-py
> 3.7.egg\pycorrector\bert\bert_corrector.py", line 29, in **init**
> tokenizer=bert_model_dir)
> File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\pipelin
> es.py", line 1798, in pipeline
> modelcard = ModelCard.from_pretrained(modelcard)
> File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\modelca
> rd.py", line 153, in from_pretrained
> model_card_file, cache_dir=cache_dir, force_download=True, proxies=proxies,
> resume_download=False
> File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\file_ut
> ils.py", line 269, in cached_path
> raise ValueError("unable to parse {} as a URL or as a local path".format(url
> _or_filename))
> ValueError: unable to parse D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages
> pycorrector-0.2.8-py3.7.egg\pycorrector\bert../data/bert_models/chinese_finetun
> ed_lm/modelcard.json as a URL or as a local path

文件读取地址不太对，改成pwd_path=‘’试试，我这边是成功运行了

**Comment by Baililily** [comment]
Traceback (most recent call last):
&nbsp; File "D:\Software\Python\Python36\lib\site-packages\transformers\configuration_utils.py", line 253, in get_config_dict
&nbsp; &nbsp; raise EnvironmentError
OSError


During handling of the above exception, another exception occurred:


Traceback (most recent call last):
&nbsp; File "D:/Software/Python/Python36/Lib/site-packages/pycorrector/bert/bert_corrector.py", line 83, in <module&gt;
&nbsp; &nbsp; d = BertCorrector()
&nbsp; File "D:/Software/Python/Python36/Lib/site-packages/pycorrector/bert/bert_corrector.py", line 33, in __init__
&nbsp; &nbsp; tokenizer=bert_model_dir)
&nbsp; File "D:\Software\Python\Python36\lib\site-packages\transformers\pipelines.py", line 1790, in pipeline
&nbsp; &nbsp; tokenizer = AutoTokenizer.from_pretrained(tokenizer)
&nbsp; File "D:\Software\Python\Python36\lib\site-packages\transformers\tokenization_auto.py", line 197, in from_pretrained
&nbsp; &nbsp; config = AutoConfig.from_pretrained(pretrained_model_name_or_path, **kwargs)
&nbsp; File "D:\Software\Python\Python36\lib\site-packages\transformers\configuration_auto.py", line 197, in from_pretrained
&nbsp; &nbsp; pretrained_model_name_or_path, pretrained_config_archive_map=ALL_PRETRAINED_CONFIG_ARCHIVE_MAP, **kwargs
&nbsp; File "D:\Software\Python\Python36\lib\site-packages\transformers\configuration_utils.py", line 272, in get_config_dict
&nbsp; &nbsp; raise EnvironmentError(msg)
OSError: Can't load '../data/bert_models/chinese_finetuned_lm/'. Make sure that:


- '../data/bert_models/chinese_finetuned_lm/' is a correct model identifier listed on 'https://huggingface.co/models'


- or '../data/bert_models/chinese_finetuned_lm/' is the correct path to a directory containing a 'config.json' file



我的还是不行，会报这个错误




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一梦南柯"<notifications@github.com&gt;; 
发送时间: 2020年8月5日(星期三) 下午3:31
收件人: "shibing624/pycorrector"<pycorrector@noreply.github.com&gt;; 
抄送: "白雪丽"<1057400303@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [shibing624/pycorrector] bert 运行时提示 unable to parse modelcard.json (#147)





  
分别将tf和transformers版本改成了TensorFlow2.0.0，transformers2.10.0，依然报错，如下：
 Traceback (most recent call last):
 File "tests\bert_corrector_test.py", line 58, in
 bertCorrector = bert_corrector.BertCorrector()
 File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\pycorrector-0.2.8-py
 3.7.egg\pycorrector\bert\bert_corrector.py", line 29, in init
 tokenizer=bert_model_dir)
 File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\pipelin
 es.py", line 1798, in pipeline
 modelcard = ModelCard.from_pretrained(modelcard)
 File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\modelca
 rd.py", line 153, in from_pretrained
 model_card_file, cache_dir=cache_dir, force_download=True, proxies=proxies,
 resume_download=False
 File "D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages\transformers\file_ut
 ils.py", line 269, in cached_path
 raise ValueError("unable to parse {} as a URL or as a local path".format(url
 _or_filename))
 ValueError: unable to parse D:\ProgramData\Anaconda3\envs\tf2\lib\site-packages
 pycorrector-0.2.8-py3.7.egg\pycorrector\bert../data/bert_models/chinese_finetun
 ed_lm/modelcard.json as a URL or as a local path
  
文件读取地址不太对，改成pwd_path=‘’试试，我这边是成功运行了
 
&mdash;

**Comment by Baililily** [comment]
1







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shibing624/pycorrector"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月14日(星期三) 晚上10:14
收件人:&nbsp;"shibing624/pycorrector"<pycorrector@noreply.github.com&gt;;
抄送:&nbsp;"白雪丽"<1057400303@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [shibing624/pycorrector] bert 运行时提示 unable to parse modelcard.json (#147)





 
加一，有21年毕业搞文本纠错的吗？联系合作/龇牙

**Comment by YgluWanh** [comment]
我在指定文件夹下新建了一个空白的modelcard.json文件，虽然还会报红，但是程序结果可以跑出来了。
了解一下______________________________

**Comment by dage0127** [comment]
可能是版本的问题，
找到transformers\pipelines.py中的2726行，
注释掉： #modelcard = ModelCard.from_pretrained(modelcard)
就OK了。
估计是新版本新增加了modelcard.json.

**Comment by outoffantasy** [comment]
> 可能是版本的问题，
> 找到transformers\pipelines.py中的2726行，
> 注释掉： #modelcard = ModelCard.from_pretrained(modelcard)
> 加一行: pass
> 就OK了。
> 估计是新版本新增加了modelcard.json.


参考这个方法确实可以！
非常感谢
