### ISSUE TITLE
大佬你好，能问一下你对中文语法纠错的思路吗

### ISSUE THREAD

**Issue by qq10198472861** [shibing624/pycorrector#149]
我测试过某些词语，例如'中国人民共和国'，这样的词应该纠正为'中华人民共和国'，但是pycorrector纠不了，我网上找了很多资料，但是关于这种纠正的很少，所以想请教您一下，如果要在pycorrector里面加入这样的纠正功能，应该从哪方面入手，非常感谢

**Comment by shibing624** [comment]
加入混淆词典。

**Comment by qq10198472861** [comment]
ok了，万分感谢您抽时间回复我




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"xuming"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月28日(星期天) 晚上7:53
收件人:&nbsp;"shibing624/pycorrector"<pycorrector@noreply.github.com&gt;;
抄送:&nbsp;"我是你的谁"<a1019847286@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shibing624/pycorrector] 大佬你好，能问一下你对中文语法纠错的思路吗 (#149)





 
加入混淆词典。
