### ISSUE TITLE
加载多个klm模型

### ISSUE THREAD

**Issue by willduan** [shibing624/pycorrector#15]
您好，目前安装了pycorrector模块之后发现只能加载people_chars_lm.klm这个模型，想问一下我自己下载了维基百科的文本数据训练了一个模型，想放到安装目录的data/kenlm文件夹下面也让它同时加载这两个模型，应该如何更改呢，谢谢啦

**Comment by shibing624** [comment]
现在没有加载连个模型的方法。建议把两个数据集合并然后用kenlm训练得到一个语言模型，再加载即可。

**Comment by batmanfightpredator** [comment]
有没有办法加载在一个数据集上训练好的kenlm模型，然后在另一个数据集上继续训练？
