### ISSUE TITLE
correct方法增加可选参数

### ISSUE THREAD

**Issue by luozhouyang** [shibing624/pycorrector#150]
- [x] I checked to make sure that this is not a duplicate issue
- [x] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/shibing624/pycorrector))

### Is your feature request related to a problem? Please describe.
`Corrector`的代码实现中，多个方法都含有可选参数。但是在主入口`correct`方法没有这些可选参数。

希望可以在`correct`方法中增加这些可选参数，以便更自由设置这些参数。

### Describe the solution you'd like
在`correct`方法中增加`correct(self, text, include_symbol=True, threshold=57, **kwargs)`等参数

**Comment by shibing624** [comment]
fixed with https://github.com/shibing624/pycorrector/commit/75fc5a7f7fed1fc1dacc3e26be76e70b7f551ef3, thx.
