### ISSUE TITLE
用GPU训练大数据

### ISSUE THREAD

**Issue by chaohuang** [shibing624/pycorrector#156]
我用pycorrector自带的数据能训练seq2seq_attention模型，但换成我自己的数据就报错说GPU资源不够：

![image](https://user-images.githubusercontent.com/1179764/88729551-0a7ad180-d0e9-11ea-90ab-8abc0df71e33.png)

我看了下，pycorrector自带的训练数据有9762个，而我自己的数据有23万个，请问这种情况下怎么用GPU训练呢？我的GPU内存为24G。

另外，请问pycorrector能用多个GPU进行训练吗？我尝试把config.py里的gpu_id改成"0,1,2,3"，但是没用。

**Comment by luozhouyang** [comment]
根据代码实现[Seq2Seq](https://github.com/shibing624/pycorrector/blob/331590be2ecc7b55a4cb60a6b1a8d678b6d0713d/pycorrector/seq2seq_attention/model.py#L99)，只支持指定gpu_id，不支持多个。你可以手动更改代码。
另外，你的词典大小是多少？24万数据其实不多，我怀疑是Embedding层太大导致的OOM。

**Comment by luozhouyang** [comment]
训练模型推荐[OpenNMT/OpenNMT-tf](https://github.com/OpenNMT/OpenNMT-tf)这个库。

本仓库的代码实现是使用Tensorflow官方的教程[transformer](https://www.tensorflow.org/tutorials/text/transformer)里面的代码实现的，训练的模型只有Checkpoint格式，不能导出成SavedModel格式，只适合作为教程使用。

**Comment by chaohuang** [comment]
@luozhouyang 多谢回复！我去试试OpenNMT

**Comment by shibing624** [comment]
OpenNMT 和fairseq都可以多gpu训练。

**Comment by xialei2821212670** [comment]
> 我用pycorrector自带的数据能训练seq2seq_attention模型，但换成我自己的数据就报错说GPU资源不足：
> 
> ![图片](https://user-images.githubusercontent.com/1179764/88729551-0a7ad180-d0e9-11ea-90ab-8abc0df71e33.png)
> 
> 我看了下，pycorrector自带的训练数据有9762个，而我自己的数据有23万个，请问这种情况下怎么用GPU训练呢？我的GPU内存为24G。
> 
> 另外，请问pycorrector能用多个GPU进行训练吗？我尝试把config.py里的gpu_id改成“ 0,1,2,3”，但是没用。
你好你的数据是网络数据？，可以分享一份？

**Comment by xialei2821212670** [comment]
你好，请问数据是网络收集整理的？可以发一份？

**Comment by chaohuang** [comment]
> 你好，请问数据是网络收集整理的？可以发一份？

我自己生成的数据
