### ISSUE TITLE
您好，请问这个项目能在win10跑吗？我在win10下安装fairseq之后，运行transformer出错，提示：

### ISSUE THREAD

**Issue by hesterLong** [shibing624/pycorrector#157]
> from fairseq import libnat
> ImportError: cannot import name 'libnat'

我是按照fairseq官方描述来安装的，过程中没有出错。
即:

> git clone https://github.com/pytorch/fairseq
> cd fairseq
> pip install --editable ./

您是否知道这是什么错误，如何解决呢？谢谢！

**Comment by shibing624** [comment]
我在mac上测试的，fairseq安装成功后应该就可以正确运行。注意fairseq的安装版本。

**Comment by shibing624** [comment]
没在win系统下安装测试过。
