### ISSUE TITLE
detector.py 中的正则表达式问题

### ISSUE THREAD

**Issue by QUENTINNE** [shibing624/pycorrector#159]
你好！我在阅读以下源码时：
[pycorrector/pycorrector/detector.py
](https://github.com/shibing624/pycorrector/blob/master/pycorrector/detector.py)
其中**第20行代码**为
`re_han = re.compile("([\u4E00-\u9FD5a-zA-Z0-9+#&]+)", re.U)`

正则表达式里的`u4E00-\u9FD5`，**是否应该修改为`\u4E00-\u9FA5`**？

因为匹配中文字符的正则表达式应该是：` [\u4E00-\u9FA5]`。

麻烦解答，谢谢！！

**Comment by shibing624** [comment]
应该是u9FA5
