### ISSUE TITLE
confusion set建议 & n-gram模型疑问

### ISSUE THREAD

**Issue by QianqianQiao** [shibing624/pycorrector#16]
您好！有幸拜读您的代码，发现同音字set中的语料都是繁体字，也许转成简体更好。另外我使用了sighan给出的同形字库进行扩充，效果有所提升。

想请教您一点：在使用kenlm训练是给入的是分好词的语料，是不是意味着kenlm认为一个词是一个gram，2-gram是两个词(based on words)，而不是两个字(based on character)呢？如果是的话，会不会与detector中以字为单位(based on words)有所矛盾呢？

感谢您🙏

**Comment by shibing624** [comment]
kenlm是训练语言模型的，用以字切分的话，跟detector中字错误检测相对应。以此切分的话同理。现在的逻辑是词错误检测通过过滤词表得到，这部分可以优化。欢迎pull request.

**Comment by yuhc0721** [comment]
@QianqianQiao  sighan的同形字库在哪里能找到？

**Comment by QianqianQiao** [comment]
@yuhc0721 搜索sighan2013下载相关资源

**Comment by dolortaste** [comment]
@QianqianQiao sighan 2013 网上的下载链接已失效，可以提供一下相关资源吗？万分感谢！

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话重新open，我来跟进。
