### ISSUE TITLE
使用kenlm，输入一段文本时响应时间过长，超过十秒。如何优化性能呢

### ISSUE THREAD

**Issue by hujunyi96** [shibing624/pycorrector#162]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [x] I walked through the tutorials
- [ ] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
只是首次服务启动需要10s，做成服务后，后续预测耗时较快，每条预测大概百ms内。
