### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by moyan2016** [shibing624/pycorrector#17]
执行python setup.py  install　
报错
copying pycorrector/__init__.py -> build/lib/pycorrector
copying pycorrector/eval.py -> build/lib/pycorrector
copying pycorrector/config.py -> build/lib/pycorrector
copying pycorrector/en_spell.py -> build/lib/pycorrector
creating build/lib/pycorrector/data
error: can't copy 'pycorrector/data/test': doesn't exist or not a regular file

源码安装和pip都是报这个错，请问什么原因？谢谢

**Comment by hxh123** [comment]
In setup.py file,
Replace the package_data field:
    package_data={
        'pycorrector': ['*.py', 'zhtools/*', 'LICENSE', 'README.*',
                        'data/*.txt', 'data/*.pkl',
                        'data/kenlm/*', 'data/test/*'],
    }
Then python setup.py install.
Done.

**Comment by shibing624** [comment]
感谢这位同学的反馈 @hxh123 ，可以提交一下pull request 么，我合并一下，这样就是你的贡献了。

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话重新open，我来跟进。
