### ISSUE TITLE
如何评价纠错模型中的一些指标值

### ISSUE THREAD

**Issue by Kvicii** [shibing624/pycorrector#170]
如F1和准确率，因为纠错的文本可能和之前的不一致了，无法对比序列得到结果

**Comment by shibing624** [comment]
跟ground_truth完全匹配，不一致就算错。

**Comment by Kvicii** [comment]
ground_truth是经过人工修正后完全正确的文本数据吗？

**Comment by shibing624** [comment]
是的

**Comment by Godlikemandyy** [comment]
你好，请问一下kenlm训练出来的语言模型的作用是什么，如果在垂直领域里应用需要训练的语料大小格式有什么要求吗？

**Comment by shibing624** [comment]
详细请了解语言模型的wiki： https://github.com/shibing624/pycorrector/wiki/%E7%BB%9F%E8%AE%A1%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B%E5%8E%9F%E7%90%86
