### ISSUE TITLE
ConnectionResetError: [Errno 54] Connection reset by peer

### ISSUE THREAD

**Issue by SlytherinWyne** [shibing624/pycorrector#171]
first use:
Downloading data from https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm
ConnectionResetError: [Errno 54] Connection reset by peer

Is it just my network problem?

**Comment by shibing624** [comment]
浏览器点击https链接下载，放到~/.pycorrector/dataset/下面对应的位置即可。
