### ISSUE TITLE
默认模型的纠错结果好像不是很好

### ISSUE THREAD

**Issue by Hexa4C** [shibing624/pycorrector#172]
### Describe the Question
您好，我使用的默认的kenlm模型（2.8G的）。然后我在网上找到了NLPCC 2018的测试集和ground truth。但是得到的结果很差，precision | recall | F_0.5分别是 0.0968 | 0.0549 | 0.0840。
请问一下，是这个模型能力不够，因此结果不怎么好吗？

**Comment by shibing624** [comment]
没有评估过该数据集的效果，欢迎把评估脚本和数据集上传给我比对一下

**Comment by Hexa4C** [comment]
> 没有评估过该数据集的效果，欢迎把评估脚本和数据集上传给我比对一下

您好，感谢您的回复。
我在NLPCC2018的官网上没有找到ground truth，但是在https://github.com/zhaoyyoo/NLPCC2018_GEC 这里看到，应该是曾经参加该shared task的人上传的，groud truth就在该repo的`Data.zip`解压后的`test/gold/`中，测试集就是`test/source.txt`。
使用pycorrector得到结果后，再用jieba工具分词。然后评测脚本是使用的https://github.com/nusnlp/m2scorer 提供的。
ground truth 有三个标注的版本，按官网上的描述，是两个anotator进行标注的，第三个是综合的结果。
我在这三个ground truth上评测，结果都差不多，效果都不太好。
不知道有没有可能是我哪里弄错了。
以及请问一下，**kenlm的一般能有多好的结果呢？**
我这里是想评测一下一些我找到的纠错工具的性能，然后找的NLPCC2018的测试集。我也有用SIGHAN进行评测过，F 0.5值在0.33左右，相对正常一点。**请问你们自己在测试的时候用的测试集是哪一个呢？**

**Comment by Hexa4C** [comment]
您好，之前我刚开始了解文本纠错，不太清楚。前段时间经过一些了解之后，我发现，默认的language model应该是只能做spelling check的对吧？如果我说的没问题，我想应该可以关闭issuse了

**Comment by shibing624** [comment]
是，中文语法维度的纠错效果不好，缺少相应的适配模型和中文语法纠错语料。
