### ISSUE TITLE
请教一下kenlm训练出来的语言模型的作用

### ISSUE THREAD

**Issue by Godlikemandyy** [shibing624/pycorrector#173]
你好，请问一下kenlm训练出来的语言模型的作用是什么，如果在垂直领域里应用需要训练的语料大小格式有什么要求吗？

**Comment by dage0127** [comment]
# 语言模型检测疑似错误字中使用kenlm的语言模型。
![image](https://user-images.githubusercontent.com/43975842/101434810-35eab400-3946-11eb-907f-49db99225a04.png)
![image](https://user-images.githubusercontent.com/43975842/101434884-5b77bd80-3946-11eb-8fbb-45e1a2c64c0d.png)

**Comment by shibing624** [comment]
1. 语料大小格式有什么要求吗? 正常语料文本，百万字以上即可，包含该领域的实体词、通用表述。如：医疗领域，需要包括疾病名称、医院名、药品名称、寻病问诊句式，这种通用实体名和表述。
2. kenlm给句子打分，需要空格间隔处理。
