### ISSUE TITLE
关于迭代bert

### ISSUE THREAD

**Issue by tangmin789** [shibing624/pycorrector#175]
你好，请问如何使用自己的数据集迭代bert模型？看了文档没整通．

**Comment by tangmin789** [comment]
ok,已经跑通了，应该是版本的问题．

**Comment by tangmin789** [comment]
> 你好，请问如何使用自己的数据集继承bert模型？看了文档没整通。

我这边已经跑通了，应该是transformers的问题．

**Comment by tangmin789** [comment]
> 你好，请问如何使用自己的数据集继承bert模型？看了文档没整通。

我这边已经跑通了，应该是transformers版本的问题。

**Comment by yxz-git** [comment]
请问一下缺少modelcard.json文件怎么解决谢谢

**Comment by shibing624** [comment]
同https://github.com/shibing624/pycorrector/issues/174 ， 已经更新fix代码。
