### ISSUE TITLE
bert finetune

### ISSUE THREAD

**Issue by Soulscb** [shibing624/pycorrector#176]
### Describe the Question
请问bert finetune的训练数据是哪一个脚本生成的

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
就是日常的无监督样本数据，包括新闻文章、百科、标题等一些通顺文本。我也有提供一批人民日报数据，均可以finetune。训练的是MLM模型，无关纠错业务。
