### ISSUE TITLE
bert纠错能力确认

### ISSUE THREAD

**Issue by vanillar7** [shibing624/pycorrector#177]
bert lm纠错方案只能解决下面错字的情况吧，补全、顺序颠倒这类的感觉应该解决不了。训练的input和output的长度是一样的

---------------------------------------------------------
中文文本纠错任务，常见错误类型包括：

谐音字词，如 配副眼睛-配副眼镜
混淆音字词，如 流浪织女-牛郎织女
字词顺序颠倒，如 伍迪艾伦-艾伦伍迪
字词补全，如 爱有天意-假如爱有天意
形似字错误，如 高梁-高粱
中文拼音全拼，如 xingfu-幸福
中文拼音缩写，如 sz-深圳
语法错误，如 想象难以-难以想象

**Comment by shibing624** [comment]
嗯，多字、少字、字序颠倒是待解决的问题。可以讨论交流。

**Comment by vanillar7** [comment]
好的，感谢答复
