### ISSUE TITLE
初始化BertCorrector失败，无法识别的模型 / Should have a `model_type` key

### ISSUE THREAD

**Issue by ouyangjunfei** [shibing624/pycorrector#178]
### 描述问题

阅读主页的Readme掌握Pycorrector的基本使用后，我尝试加载Bert模型用于纠错

![4.png](https://user-images.githubusercontent.com/24387167/100463509-ea930300-3106-11eb-91d5-b5ab2168502b.png)

请忽略红色的错误提示，这是Pycharm的环境，运行环境部署于CentOS且安装了相应的库

当我运行此py文件后，提示相应错误

![3.png](https://user-images.githubusercontent.com/24387167/100467164-fa154a80-310c-11eb-96d4-2746f6f66ddb.png)

### 模型目录与相关pip包版本

从飞书下载的压缩包，解压后与[BERT模型Readme](https://github.com/shibing624/pycorrector/tree/master/pycorrector/bert)所述的文件结构相比，多出一个`bert_config.json`文件，经查看`config.json`文件里确实没有`model_type`的key，但是查阅之前的Issue并没有看见提出与模型相关的问题

![1.png](https://user-images.githubusercontent.com/24387167/100467345-42346d00-310d-11eb-9ae8-135923b9699d.jpg)

`transformer`保持旧版本

![2](https://user-images.githubusercontent.com/24387167/100467363-4a8ca800-310d-11eb-91ad-3e2ae7346179.jpg)

    pycorrector==0.2.8

### 可能原因

目前`pycorrector`包中的`bert_corrector`是否是可用的，因为如果使用import方式使用`pycorrector`模型文件是不应该存放于`data/bert_models`目录，而需要额外传入路径参数

另，我尝试将`bert_corrector.py`文件修改`bert_model_dir`后单独运行，报错与上面一样

**Comment by shibing624** [comment]
同https://github.com/shibing624/pycorrector/issues/174， 已经fixed，更新代码即可。
