### ISSUE TITLE
请问bert文本纠错的话 怎么提速，model可以用GPU推理吗

### ISSUE THREAD

**Issue by James0128** [shibing624/pycorrector#179]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [x] I walked through the tutorials
- [ ] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by dage0127** [comment]
理论上应该可以用GPU。但直接用CPU速度也够快，加载模型2.6秒，每一句用时在0.07s左右，一秒可以处理14个句子。

load bert model time usage:2.642973s
infer time usage:0.070808s
infer time usage:0.056847s
infer time usage:0.060837s
infer time usage:0.074316s
infer time usage:0.071808s

**Comment by James0128** [comment]
您好, 我只对一条句子做了一个简单的推理，
    started = time.time()
    d=BertCorrector()
    correct_sent1=d.bert_correct('我的心请不好')
    finished=time.time()
    print('with revise：{0}'.format(correct_sent1[0]))
    print('inference time:{0}'.format(finished-started))
最后：inference time:10.504112005233765
我的运行环境是六核i7，不知道为什么回这么慢呢

**Comment by shibing624** [comment]
如果对预测qps有要求，我可以优化下，补充使用gpu预测的功能吧。这样后面就不直接调用transformers包了。

**Comment by seun-wun** [comment]
> 您好, 我只对一条句子做了一个简单的推理，
> started = time.time()
> d=BertCorrector()
> correct_sent1=d.bert_correct('我的心请不好')
> finished=time.time()
> print('with revise：{0}'.format(correct_sent1[0]))
> print('inference time:{0}'.format(finished-started))
> 最后：inference time:10.504112005233765
> 我的运行环境是六核i7，不知道为什么回这么慢呢

你好 我也是预测的很慢 你找到解决的办法了吗~

**Comment by shibing624** [comment]
已经完成transformers包的迁移，infer对gpu的支持可配置。

**Comment by Garen-in-bush** [comment]
> > 您好, 我只对一条句子做了一个简单的推理，
> > started = time.time()
> > d=BertCorrector()
> > correct_sent1=d.bert_correct('我的心请不好')
> > finished=time.time()
> > print('with revise：{0}'.format(correct_sent1[0]))
> > print('inference time:{0}'.format(finished-started))
> > 最后：inference time:10.504112005233765
> > 我的运行环境是六核i7，不知道为什么回这么慢呢
> 
> 你好 我也是预测的很慢 你找到解决的办法了吗~

你可以试试将每个模块的耗时都计算一下吗，这样才好分析是哪里出了问题，可以使用cProfile与line_profiler来定位是哪里耗费了你大量的时间

**Comment by shibing624** [comment]
显式支持gpu预测。https://github.com/shibing624/pycorrector/commit/29c03a5a1f01cd48349c580c5d917a635edf9ac4
