### ISSUE TITLE
相似音的词语错误可以纠正吗？

### ISSUE THREAD

**Issue by YanglanWang** [shibing624/pycorrector#181]
### Describe the Question
Please provide a clear and concise description of what the question is.
1、“流浪织女”的错误能纠正吗？我运行得到的结果都没有正确纠正
### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
支持加自定义混淆纠错词表。
