### ISSUE TITLE
如何训练属于自己的模型

### ISSUE THREAD

**Issue by lmw0320** [shibing624/pycorrector#183]
大佬，你好。刚入门学习NLP，想请教几点疑问：
1. 这份代码没有预训练模型么？ --我想训练一个属于自己业务范畴的模型，如果有预训练模型，可能会比较快些？
2.  我想测试下，是否可以正常跑通代码，没有模型的话，也没法跑通吧？
3. 如果要训练属于自己的数据集，要如何准备数据？ 对这块的原理，了解不是很多。。应该要准备一个正确的词典文件？
4. 如果博主能出一个博客，感激不尽～～

**Comment by shibing624** [comment]
看完readme，上手试试。
