### ISSUE TITLE
ernie模型如何在垂直领域进行优化

### ISSUE THREAD

**Issue by FankLi** [shibing624/pycorrector#185]
RT
期待并感谢你的回复

**Comment by shibing624** [comment]
请罗列需要优化的点和case

**Comment by FankLi** [comment]
提升准确率，是要对ernie模型进行2次训练吗，当前开源中好像没看到相关脚本

**Comment by FankLi** [comment]
认真研究了下源码，此方法有其微妙之处：基于ernie模型预测[MASK]，并用了规则统计语言模型进行兜底。
所以可以从3个方面进行准确率的优化：
1.用垂直领域数据对ernie进行2次训练；
2.用垂直领域数据对kenLM模型进行2次训练；
3.不断维护关键词典。

麻烦确认一下这样的理解，对吗？谢谢

**Comment by shibing624** [comment]
1.ernie纠错的设计逻辑，规则方法主要是考虑到线上应用时，方便调整输出效果；
2.模型和数据维度的提升才是提升纠错效果的关键；如果没有纠错专用的模型，那么效果还是提升不了；数据是业务领域数据效果肯定更好。

**Comment by FankLi** [comment]
纠错专用的模型，是指？
我理解的，就是运用ernie的 MLM 能力，所以拿业务数据二次训练ernie即可，是否理解有误？

**Comment by shibing624** [comment]
ernie跟bert一样，是预训练模型。可以拿业务数据二次训练ernie
