### ISSUE TITLE
bert纠错方法用小模型finetune预测反而更慢

### ISSUE THREAD

**Issue by wangyidong223** [shibing624/pycorrector#188]
您好！感谢您的贡献。我有一个问题。我用您的bert方法，换了Rbt3,Electra等小模型来finetune，最后用bert_corrector.py测试的时候纠错的速度反而比您提供的bert更慢，这是怎么回事呢？
谢谢！

**Comment by shibing624** [comment]
robote,electra模型比bert大；albert, albert-tiny, distill-bert比base-bert模型小。这里的大小表示权重值总量。

**Comment by wangyidong223** [comment]
> robote,electra模型比bert大；albert, albert-tiny, distill-bert比base-bert模型小。这里的大小表示权重值总量。

我这两天用run_language_modeling.py训练了albert_tiny的模型，但跑一条同样的大概250个字的片段，居然还是比您提供的bert慢啊，用的都是您最新的bert_correcotor.py代码，您知道是怎么回事么？
