### ISSUE TITLE
显卡使用

### ISSUE THREAD

**Issue by HandsLing** [shibing624/pycorrector#194]
貌似只能使用0号显卡，换成其他显卡会报错  RuntimeError: CUDA error: invalid device ordinal
请问有啥参数可以指定用除了0之外的显卡吗？
谢谢

**Comment by shibing624** [comment]
export CUDA_VISIBLE_DEVICES=0,1 ##仅显卡设备0,1GPU可见。可用的GPU可通过nvidia-smi -L命令查看
