### ISSUE TITLE
Bert model run exception

### ISSUE THREAD

**Issue by zjhiphop** [shibing624/pycorrector#195]
### Describe the bug
Follow the "README" inside `pycorrector/bert/` to download bert mode and run. The exception: `AttributeError: 'tokenizers.Encoding' object has no attribute 'n_sequences'` will happen.

### To Reproduce
```
import os

from pycorrector.transformers import pipeline

model_dir = ".pycorrector/datasets/bert_models/chinese_finetuned_lm"
nlp = pipeline('fill-mask', model=model_dir)

i = nlp('今天[MASK]情很好')
print(i)

```

### Describe your attempts
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not a duplicate issue

### Context
 - Mac OS 11.1
 - MacBook Pro 2.6 GHz 6-Core Intel Core i7 / 16G mem
 - PyCorrrect version: git commit hash 4fabbfddf46b9f62732cb960eaa1aaf70deefaf3

### Additional Information
Potential solution: 
![image](https://user-images.githubusercontent.com/763008/110496693-b7fa9c80-8130-11eb-9a4f-c9ca1eded00e.png)

**Comment by shibing624** [comment]
PyTorch version 1.6.0 没出问题。

**Comment by gitabtion** [comment]
pycorrector 内置的是4.2.0版本的transformers，对应的tokenizers版本为0.9.4，请使用以下命令安装tokenizers包。
``pip install tokenizers==0.9.4``
