### ISSUE TITLE
关于pycorrector.correct模块的使用-漏召回case

### ISSUE THREAD

**Issue by cxy86121-sudo** [shibing624/pycorrector#196]
>>> import pycorrector
>>> cor ,det = pycorrector.correct('明月即使有,把酒问青天')
>>> print(cor,det)
>>> 明月即使有,把酒问青天 []

>>> s,f = pycorrector.correct('你是我的小宝呗')
>>> print(s,f)
你是我的小宝呗 []

使用纠错模块，试了几个例子后发现很多纠正不了，如上面的两个例子。

**Comment by shibing624** [comment]
长尾漏召回case，建议自己加到混淆词典confusion dict处理。
