### ISSUE TITLE
BERT和MacBERT模型来源问题

### ISSUE THREAD

**Issue by githubofzhj** [shibing624/pycorrector#197]
bert默认读取这个 /root/.pycorrector/datasets/bert_models/chinese_finetuned_lm/路径下的模型文件，请问chinese_finetuned_lm直接可以从huggingface下载得到吗？还是需要自己训练？谢谢~

**Comment by shibing624** [comment]
可以直接下载，如果要fine-tune自己的数据也行，具体因效果而异。
