### ISSUE TITLE
pytorch版本的seq2seq模型的infer.py运行结果全是“我我我我我我我......”

### ISSUE THREAD

**Issue by ChuoQi** [shibing624/pycorrector#198]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

### To Reproduce
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) here. We hope we can simply copy/paste/run it. It is also nice to share a hosted runnable script (e.g. Google Colab), especially for hardware-related problems.

### Describe your attempts
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
样本太少。

**Comment by ChuoQi** [comment]
好的，我试试增加样本，还有就是代码中的seq2seq模型能不能在评估模块除了loss的计算再加上准确率，召回率，F1值的计算呀？谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月13日(周二) 晚上8:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shibing624/pycorrector] pytorch版本的seq2seq模型的infer.py运行结果出错，推测的结果全是“我我我我我我我......” (#198)




 
样本太少。

**Comment by shibing624** [comment]
可以自己加，不建议加，seq2seq仅仅是生成任务，F1值不适合。
