### ISSUE TITLE
【Feature】针对多字,少字的检测和纠错模块

### ISSUE THREAD

**Issue by JiachengNlp** [shibing624/pycorrector#202]
- [ ] I checked to make sure that this is not a duplicate issue
- [ ] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/shibing624/pycorrector))

### Describe the solution you'd like
针对多字,少字的检测和纠错模块

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
请提供些多字、少字的case

**Comment by Kiteflyingee** [comment]
比如说多吉美，用户说成多吉的美，这种可以实现吗？必须加混淆词吗？

**Comment by Kiteflyingee** [comment]
> 比如说多吉美，用户说成多吉的美，这种可以实现吗？必须加混淆词吗？



> 请提供些多字、少字的case

比如“多吉美”，说成多吉吉美，用户多说了一个字，必须通过添加混淆词汇吗？

**Comment by Kiteflyingee** [comment]
> > 比如说多吉美，用户说成多吉的美，这种可以实现吗？必须加混淆词吗？
> 
> > 请提供些多字、少字的case
> 
> 比如“多吉美”，说成多吉吉美，用户多说了一个字，必须通过添加混淆词汇吗？

我尝试把多吉美加入专有词，发现这两种情况没纠错出来，是我的使用方法有问题吗？我是直接调用pycorrector.correct(line)
