### ISSUE TITLE
bert运行报错：modelcard.json not found

### ISSUE THREAD

**Issue by xubinxin123** [shibing624/pycorrector#203]
已经下载了bert的预训练模型并放到指定位置，运行bert_corrector.py,已经看到模型被加载，但是后边又提示模型找不到
D:\SoftRun\Anaconda3\envs\gluon\python.exe E:/nlpcode/pycorrector-master/pycorrector-master/pycorrector/bert/bert_corrector.py
[   INFO 20210429 10:52:14 configuration_utils: 426] loading configuration file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/config.json
[   INFO 20210429 10:52:14 configuration_utils: 464] Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

[   INFO 20210429 10:52:14 modeling_utils:1019] loading weights file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/pytorch_model.bin
[   INFO 20210429 10:52:15 modeling_utils:1137] All model checkpoint weights were used when initializing BertModel.

[   INFO 20210429 10:52:15 modeling_utils:1146] All the weights of BertModel were initialized from the model checkpoint at C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/.
If your task is similar to the task the model of the checkpoint was trained on, you can already use BertModel for predictions without further training.
[   INFO 20210429 10:52:15 configuration_utils: 426] loading configuration file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/config.json
[   INFO 20210429 10:52:15 configuration_utils: 464] Model config BertConfig {
  "attention_probs_dropout_prob": 0.1,
  "directionality": "bidi",
  "gradient_checkpointing": false,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "pooler_fc_size": 768,
  "pooler_num_attention_heads": 12,
  "pooler_num_fc_layers": 3,
  "pooler_size_per_head": 128,
  "pooler_type": "first_token_transform",
  "position_embedding_type": "absolute",
  "type_vocab_size": 2,
  "use_cache": true,
  "vocab_size": 21128
}

[   INFO 20210429 10:52:15 tokenization_utils_base:1720] Model name 'C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/' not found in model shortcut name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, TurkuNLP/bert-base-finnish-cased-v1, TurkuNLP/bert-base-finnish-uncased-v1, wietsedv/bert-base-dutch-cased). Assuming 'C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/' is a path, a model identifier, or url to a directory containing tokenizer files.
[   INFO 20210429 10:52:15 tokenization_utils_base:1753] Didn't find file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/tokenizer.json. We won't load it.
[   INFO 20210429 10:52:15 tokenization_utils_base:1753] Didn't find file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/added_tokens.json. We won't load it.
[   INFO 20210429 10:52:15 tokenization_utils_base:1753] Didn't find file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/special_tokens_map.json. We won't load it.
[   INFO 20210429 10:52:15 tokenization_utils_base:1753] Didn't find file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/tokenizer_config.json. We won't load it.
[   INFO 20210429 10:52:15 tokenization_utils_base:1799] loading file C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/vocab.txt
[   INFO 20210429 10:52:15 tokenization_utils_base:1799] loading file None
[   INFO 20210429 10:52:15 tokenization_utils_base:1799] loading file None
[   INFO 20210429 10:52:15 tokenization_utils_base:1799] loading file None
[   INFO 20210429 10:52:15 tokenization_utils_base:1799] loading file None
Traceback (most recent call last):
  File "E:/nlpcode/pycorrector-master/pycorrector-master/pycorrector/bert/bert_corrector.py", line 82, in <module>
    d = BertCorrector()
  File "E:/nlpcode/pycorrector-master/pycorrector-master/pycorrector/bert/bert_corrector.py", line 31, in __init__
    device=0,  # gpu device id
  File "E:\nlpcode\pycorrector-master\pycorrector-master\pycorrector\transformers\pipelines.py", line 1572, in pipeline
    modelcard = ModelCard.from_pretrained(modelcard, revision=revision)
  File "E:\nlpcode\pycorrector-master\pycorrector-master\pycorrector\transformers\modelcard.py", line 152, in from_pretrained
    resolved_model_card_file = cached_path(model_card_file, cache_dir=cache_dir, proxies=proxies)
  File "E:\nlpcode\pycorrector-master\pycorrector-master\pycorrector\transformers\file_utils.py", line 1034, in cached_path
    raise ValueError("unable to parse {} as a URL or as a local path".format(url_or_filename))
ValueError: unable to parse C:\Users\Administrator/.pycorrector/datasets\bert_models/chinese_finetuned_lm/modelcard.json as a URL or as a local path

Process finished with exit code 1

### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

### To Reproduce
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) here. We hope we can simply copy/paste/run it. It is also nice to share a hosted runnable script (e.g. Google Colab), especially for hardware-related problems.

### Describe your attempts
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
pip uninstall transformers

**Comment by xubinxin123** [comment]
已经删除，还是一样的报错输出
 C:\Users\Administrator>pip uninstall transformers
Found existing installation: transformers 2.1.1
Uninstalling transformers-2.1.1:
  Would remove:
    c:\users\administrator\anaconda3\envs\gluon\lib\site-packages\transformers-2.1.1.dist-info\*
    c:\users\administrator\anaconda3\envs\gluon\lib\site-packages\transformers\*
    c:\users\administrator\anaconda3\envs\gluon\scripts\transformers.exe
Proceed (y/n)? y
  Successfully uninstalled transformers-2.1.1
