### ISSUE TITLE
英文纠错误杀

### ISSUE THREAD

**Issue by zhongyanxia123** [shibing624/pycorrector#204]
关于英文纠错的部分，pycorrector会把一些本身没有错的单词就成另外一个单词，case如下：
folder -> older, 
payroll -> patrol,
connectivity -> conductivity,
website -> webster

这些词都是比较普遍的词（词库应该会有这样的单词存在），但是还是被纠错了，感觉很容易被误杀，能不能看一下这个case怎么解决呢？

谢谢！

**Comment by shibing624** [comment]
fix with https://github.com/shibing624/pycorrector/commit/264efdbe0bebf98fb5ada1ce9b2df47f12d4d1cc
