### ISSUE TITLE
规则方法纠错效果评估

### ISSUE THREAD

**Issue by liaoxuewei** [shibing624/pycorrector#205]
https://zhuanlan.zhihu.com/p/259540550

但在使用PYcorrector的时候，我发现PYcorrector确实能找出部分文本中的错误：
**原句:一般的保温杯太高竞然接不到水,纠正:一般的保温杯太高竟然接不到水**

但更多的是False Positive，比如以下：
**原句:下置式饮水机颜值很高呀,纠正:下置式饮水机验值很高呀
原句:一如既往的高颜值,纠正:一如既往的高燕值
原句:上水声音太大,纠正:上说声音太大
原句:价格感觉有点小贵小贵的,纠正:价格感觉有点小归小贵的
原句:希望用久点吧,纠正:希望永久点吧**

**Comment by shibing624** [comment]
1.规则方法：结合关闭字粒度错误，和混淆纠错集使用。
2.深度方法：可以尝试下macbert的领域纠错，然后如果有训练数据，尝试finetune 预训练模型再纠错。

**Comment by liaoxuewei** [comment]
> 1.规则方法：结合关闭字粒度错误，和混淆纠错集使用。
> 2.深度方法：可以尝试下macbert的领域纠错，然后如果有训练数据，尝试finetune 预训练模型再纠错。

感谢回复，刚刚才接触，要熟悉一下。谢谢！
