### ISSUE TITLE
能否提供一些固定词定义功能

### ISSUE THREAD

**Issue by liaoxuewei** [shibing624/pycorrector#206]
能否提供一些固定词定义功能，如“有产业级模型库、开发套件和工具组件”，最终纠错的结果“有产业集模型库、开发套件和工具组件 [['业级', '业集', 2, 4]]”，纠错失败了。
我在自定义混淆纠错集定义“产业集 产业级”，也尝试在自定义词频做了“产业级”定义，都是是不能实现。
但是在自定义混淆纠错集定义“业集 业级“，是可以避免问题，但是实际上我们知道“产业级”是一个比较明显的词，可能是分词问题导致，有人提到结巴分词准确性不如百度分词，故提出是否可以定义这种固定词避免分词错误。

**Comment by shibing624** [comment]
可以提供固定词思路？
