### ISSUE TITLE
AttributeError: module 'pycorrector' has no attribute 'correct'

### ISSUE THREAD

**Issue by hjing100** [shibing624/pycorrector#207]
import pycorrector

corrected_sent, detail = pycorrector.correct('少先队员因该为老人让坐')
print(corrected_sent,detail)

have error:
AttributeError: module 'pycorrector' has no attribute 'correct'

And pycorrector version: 0.3.1

**Comment by hjing100** [comment]
then I try:

from pycorrector import Corrector
import os


pwd_path = os.path.abspath(os.path.dirname(__file__))
lm_path = os.path.join(pwd_path, './packages/zh_giga.no_cna_cmn.prune01244.klm')
model = Corrector(language_model_path=lm_path)

error_sentence = "少先队员因该为老人让坐"
print(model.correct(error_sentence))


have error:
ImportError: cannot import name 'Corrector'

**Comment by shibing624** [comment]
刷新本地环境再试。
