### ISSUE TITLE
中文拼音全拼是否已经支持

### ISSUE THREAD

**Issue by nghuyong** [shibing624/pycorrector#208]
针对目前混杂拼音的纠错是否已经支持了，即readme中提到的两种场景
- 中文拼音全拼 如 xingfu-幸福 
- 中文拼音缩写，如 sz-深圳
----
直接调用`pycorrector.correct('我住在sz')`目前还不行

**Comment by shibing624** [comment]
未支持。
1.中文中出现拼音的场景较少，实用性不高，当前默认遇到非中文字符会过滤；
2.加入拼音纠错，文本有些英文商标会误纠错为中文，造成误杀。

基于此，拼音纠错的的功能是否需要实现还在评估中。
