### ISSUE TITLE
运行报错，没有modelcard.json文件

### ISSUE THREAD

**Issue by cfy42584125** [shibing624/pycorrector#213]
![image](https://user-images.githubusercontent.com/62530854/120967543-28e63a80-c79a-11eb-99d1-344bad384384.png)
运行bert_corrector.py报错。没有找到C:\Users\chu.fangyuan/.pycorrector/datasets\bert_models/chinese_finetuned_lm/modelcard.json 文件
![image](https://user-images.githubusercontent.com/62530854/120967711-6b0f7c00-c79a-11eb-9f74-72298d7d07e4.png)
下载的文件中并没有modelcard.json文件

**Comment by gitabtion** [comment]
应该是transformers版本太高了，本地测试在4.0.0<transformers<=4.1.1的环境下可正常使用

**Comment by A6Matrix** [comment]
请问这个问题你解决了吗

**Comment by jr011** [comment]
在modelcard.py文件中的145-148行，把replace后面的两个变量调换顺序就好了
        if find_from_standard_name or pretrained_model_name_or_path in ALL_PRETRAINED_CONFIG_ARCHIVE_MAP:
            model_card_file = model_card_file.replace(MODEL_CARD_NAME, CONFIG_NAME)
            model_card_file = model_card_file.replace(MODEL_CARD_NAME, WEIGHTS_NAME)
            model_card_file = model_card_file.replace(MODEL_CARD_NAME, TF2_WEIGHTS_NAME)

**Comment by wshzd** [comment]
> 在modelcard.py文件中的145-148行，把replace后面的两个变量调换顺序就好了
> if find_from_standard_name or pretrained_model_name_or_path in ALL_PRETRAINED_CONFIG_ARCHIVE_MAP:
> model_card_file = model_card_file.replace(MODEL_CARD_NAME, CONFIG_NAME)
> model_card_file = model_card_file.replace(MODEL_CARD_NAME, WEIGHTS_NAME)
> model_card_file = model_card_file.replace(MODEL_CARD_NAME, TF2_WEIGHTS_NAME)
