### ISSUE TITLE
英文纠错：增加判断输入词在不在词典word_freq_dict中的功能

### ISSUE THREAD

**Issue by zhongyanxia123** [shibing624/pycorrector#214]
测试的时候发现一个case：如果输入joiner会被纠正成joined，本身joiner是正确的，词典里也有，但是由于经过转换产生了candidates集合，其中joined的词频更高，joiner就被纠成了joined

为解决该问题，针对en_spell中的corrector类下面的纠错逻辑做了一些思考：
1、由于前面_init的方法已经筛去了词频少于400的词，一定程度上已经筛掉了大量的错词
2、 本人认为可以对输入词进行一个判断，首先判断在不在混淆词集，然后判断该词在不在整个词典word_freq_dict里，如果该词在词典里则不进行纠错。

代码更改如下：

<img width="629" alt="截屏2021-06-07 下午3 16 22" [
<img width="629" alt="截屏2021-06-07 下午3 16 22" src="https://user-images.githubusercontent.com/84298873/120975072-6b604500-c7a3-11eb-8bf3-c745ef36bd20.png">
](src="https://user-images.githubusercontent.com/84298873/120975016-5daabf80-c7a3-11eb-9dca-be4ba32876ff.png">)

**Comment by shibing624** [comment]
good
