### ISSUE TITLE
可以仅启用字形校准吗

### ISSUE THREAD

**Issue by hqp-hub** [shibing624/pycorrector#215]
如题，想将pycorrector应用在对OCR识别结果的校准上面，但是有些发音、拼音的非错误被误判了，所以想请教一下，有仅针对字形进行纠错或者关闭发音，谐音的功能吗？谢谢

**Comment by shibing624** [comment]
应该可以，我改下

**Comment by shibing624** [comment]
1.发现拼音和字形的逻辑耦合比较深，改逻辑比较麻烦。
2.简单的做法，把`pycorrector/data/same_pinyin.txt`文件删除，也能达到关闭拼音纠错的效果。

**Comment by hqp-hub** [comment]
好的，谢谢指点
