### ISSUE TITLE
ngram中的n是多少

### ISSUE THREAD

**Issue by nghuyong** [shibing624/pycorrector#216]
感谢您提供的语言模型，我分别下载了字和词级别的

![image](https://user-images.githubusercontent.com/16462374/122263972-9a945600-cf09-11eb-8029-2391be17befe.png)

请问词级别和字级别分别是 几gram 的语言模型？

词级别的语言模型，对语料的分词是什么分词器，加载词典了吗？

**Comment by shibing624** [comment]
1.都是3
2.人民日报熟语料，是人工标注分词结果，分词过的熟语料。

**Comment by nghuyong** [comment]
再请教一下，`zh_giga.no_cna_cmn.prune01244.klm`是基于千兆的语料训练而成的，这部分语料能开放吗？
这个语言模型是字级别的语言模型，是否有对应版本的词级别的语言模型？

**Comment by shibing624** [comment]
未开放，来自百度语音识别部训练。也可以用在词级别。

**Comment by nghuyong** [comment]
这是一个字级别和词级别通用的语言模型吗？
