### ISSUE TITLE
macbert预训练模型

### ISSUE THREAD

**Issue by szq261299** [shibing624/pycorrector#217]
### Describe the Question
想知道最终用于文本纠错的macbert 预训练模型 是以什么任务为目标微调得到的  

### Your Attempts
只看到直接调用别人训练好的预训练模型

**Comment by shibing624** [comment]
可以看paper了解原理，主要是基于bert的相似词替换的预训练模型。

**Comment by Jay-9912** [comment]
您好，请问MacBERT除了用SIGHAN15来fine tune还使用了哪些数据？ @shibing624

**Comment by gitabtion** [comment]
> 您好，请问MacBERT除了用SIGHAN15来fine tune还使用了哪些数据？ @shibing624

[wang 271k](https://github.com/wdimmy/Automatic-Corpus-Generation/blob/master/corpus/train.sgml)
