### ISSUE TITLE
安装paddle是哪个版本

### ISSUE THREAD

**Issue by ht281358490** [shibing624/pycorrector#218]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

### To Reproduce
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) here. We hope we can simply copy/paste/run it. It is also nice to share a hosted runnable script (e.g. Google Colab), especially for hardware-related problems.

### Describe your attempts
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
pip install paddlepaddle==1.8.4  https://github.com/shibing624/pycorrector/tree/master/pycorrector/ernie

**Comment by ht281358490** [comment]
thank  you. I have tried to install   paddlepaddle==1.8.5
