### ISSUE TITLE
语言模型出错

### ISSUE THREAD

**Issue by cloudfool** [shibing624/pycorrector#22]
您好，

我发现您提供的云盘里的语言模型people2014corpus_chars.klm和程序默认的语言模型people_chars_lm.klm是不一样的。然后我把云盘里的模型替换掉默认模型之后，程序就运行失败了，显示Illegal instruction (core dumped). 
我想问下我该如何使用云盘里提供的语言模型，谢谢。

**Comment by shibing624** [comment]
嗯，https://github.com/shibing624/pycorrector/issues/11

**Comment by cloudfool** [comment]
楼上的这个问题和我的好像不一样。。
我看到你最近更新了一个程序 load_custom_dict.py，可以加载自定义的模型文件。我这边把config.py里的语言模型的路径换成你云盘里提供的char模型，程序依然显示相同的错误。但是我用默认的语言模型，程序就能正常运行，不知道为什么。。。

**Comment by cloudfool** [comment]
您好，我想请问程序默认的语言模型people_chars_lm.klm和云盘里提供的语言模型people2014corpus_char.klm，都是用您附上的那篇关于kenlm的博客里写的方法训练得到的么？
因为目前不论是用云盘里提供的模型还是我自己训练的模型，运行程序都容易出现illegal instructions的错误，唯独用默认的语言模型people_chars_lm.klm可以正常运行。
对于这个问题，希望您能给我一些建议，谢谢了。

**Comment by shibing624** [comment]
1. 都是用您附上的那篇关于kenlm的博客里写的方法训练得到的.
2. people2014corpus_chars.klm 是 people2014corpus_chars.arps的压缩格式，使用people2014corpus_chars.klm替换默认模型应该可以使用，而且纠错效果要好一些。
