### ISSUE TITLE
BertBasedCorrectionModels模型问题

### ISSUE THREAD

**Issue by myboyliu** [shibing624/pycorrector#220]
###目前文档只有MACBERT MLM模型的部署方法，我使用的是SoftMaskedBert，具体的方法能否描述一下。
下面是我训练好的SoftMaskedBert权重文件已经放到/.pycorrector/datasets/macbert_models/chinese_finetuned_correction
Please provide a clear and concise description of what the question is.
total 486164
     4 drwxrwxr-x 2 gpu gpu      4096 7月   7 15:41 .
     4 drwxrwxr-x 3 gpu gpu      4096 7月   7 15:40 ..
     4 -rw-rw-r-- 1 gpu gpu         2 7月   7 15:41 added_tokens.json
     4 -rw-rw-r-- 1 gpu gpu       659 7月   7 15:41 config.json
486140 -rw-rw-r-- 1 gpu gpu 497799880 7月   7 15:41 pytorch_model.bin
     4 -rw-rw-r-- 1 gpu gpu       112 7月   7 15:41 special_tokens_map.json
     4 -rw-rw-r-- 1 gpu gpu        19 7月   7 15:41 tokenizer_config.json
### Describe your attempts
- [ ] 能否进一步提供一份详细的部署方法。

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/README.md

**Comment by gitabtion** [comment]
暂不支持部署SoftMaskedBERT，如需使用请用原仓库的inference脚本
