### ISSUE TITLE
transformer训练模型预测全是<UNK>

### ISSUE THREAD

**Issue by ghostviper** [shibing624/pycorrector#221]
请问下，我用transformer训练了您百度网盘的语料+我自己的部分语料，训练出来的模型预测全部打印<unk>是我哪个阶段做错了吗？是不是train和test里面的词语不同导致的？

**Comment by jr011** [comment]
请问您解决了吗

**Comment by shibing624** [comment]
请提供下训练参数和预测的badcase

**Comment by shibing624** [comment]
该模型transformer用于纠错难以拟合，需要海量数据，当前纯seq生成的模型在纠错效果都不佳，改进中。
