### ISSUE TITLE
MacBert model bug

### ISSUE THREAD

**Issue by ericperfect** [shibing624/pycorrector#222]
"""下载用开源的中文文本纠错数据集fine-tune后的预训练MACBERT MLM模型（飞书文档链接: https://szuy1h04n8.feishu.cn/file/boxcnoKfHHtjokcZojQO2VjtQHB 密码: QKz3），解压后放置于~/.pycorrector/dataset/macbert_models/chinese_finetuned_correction目录下"""

这个模型似乎有问题 加载时提示
 f"Unable to load weights from pytorch checkpoint file for '{pretrained_model_name_or_path}' "
OSError: Unable to load weights from pytorch checkpoint file for '/home/wuyunzhao/.pycorrector/datasets/macbert_models/chinese_finetuned_correction' at '/home/wuyunzhao/.pycorrector/datasets/macbert_models/chinese_finetuned_correction/pytorch_model.bin'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

**Comment by gitabtion** [comment]
ubuntu18.04, torch1.8.1+cu111, 模型加载正常

**Comment by linyuchuan** [comment]
补充：如果环境不能更新
可以通过以下代码，先在高版本torch和transformer环境下加载模型，然后重新保存为低版本的torch和transformer环境下的模型
state_dict = torch.load(path, map_location="cpu")
torch.save(state_dict, output_dir, _use_new_zipfile_serialization=False)
重新保存后的模型即便是低版本的transformer或torch下也可使用
