### ISSUE TITLE
污染Python关键字int？

### ISSUE THREAD

**Issue by SakigamiYang** [shibing624/pycorrector#224]
### Describe the bug
调用correct函数后对detail进行循环时发现，除第一项的start和end为int类型外，其它项的start和end均变为numpy.int类型。
尝试用关键词int和numpy进行搜索，没发现有直接赋值替换的地方。
是否有污染关键字的代码存在？

### To Reproduce
```python
import pycorrector

corrected_sent, detail = pycorrector.correct('我们应该让坐')
for item in detail:
    source, target, start, end = item
    print(type(start))
    print(type(end))
```

### Describe your attempts
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: macOS 11.4
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: CPU only

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.
pycorrector.__version__ == 0.3.2

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
fixed, to int. <class 'int'>   https://github.com/shibing624/pycorrector/commit/b93a4d91c21a6893acbc0d786a0a4f4dbe11b3d0
