### ISSUE TITLE
conv_seq2seq模型 infer RuntimeError

### ISSUE THREAD

**Issue by currenttime** [shibing624/pycorrector#225]
conv_seq2seq模型，训练完模型后，运行infer.py报错

Namespace(arch='fconv', beam=5, bpe=None, buffer_size=1, cpu=False, criterion='cross_entropy', data='/home/dell/brx/pycorrector/pycorrector/conv_seq2seq/output/bin', dataset_impl=None, decoder_attention='True', decoder_embed_dim=512, decoder_embed_path=None, decoder_layers='[(512, 3)] * 20', decoder_out_embed_dim=256, decoding_format=None, diverse_beam_groups=-1, diverse_beam_strength=0.5, dropout=0.1, empty_cache_freq=0, encoder_embed_dim=512, encoder_embed_path=None, encoder_layers='[(512, 3)] * 20', force_anneal=None, fp16=False, fp16_init_scale=128, fp16_scale_tolerance=0.0, fp16_scale_window=None, gen_subset='test', input=['（ 二 ） 审 议 通 过 《 关 于 公 司 2 0 1 9 年 年 度 报 告 及 摘 要 的 议 案 》'], iter_decode_eos_penalty=0.0, iter_decode_force_max_iter=False, iter_decode_max_iter=10, lazy_load=False, left_pad_source='True', left_pad_target='False', lenpen=1, load_alignments=False, log_format=None, log_interval=1000, lr_scheduler='fixed', lr_shrink=0.1, match_source_len=False, max_len_a=0, max_len_b=200, max_sentences=None, max_source_positions=1024, max_target_positions=1024, max_tokens=400, memory_efficient_fp16=False, min_len=1, min_loss_scale=0.0001, model_overrides='{}', momentum=0.99, nbest=1, no_beamable_mm=False, no_early_stop=False, no_progress_bar=False, no_repeat_ngram_size=0, num_shards=1, num_workers=1, optimizer='nag', path='/home/dell/brx/pycorrector/pycorrector/conv_seq2seq/output/models/checkpoint_best.pt', prefix_size=0, print_alignment=False, print_step=False, quiet=False, raw_text=False, remove_bpe=None, replace_unk=None, required_batch_size_multiple=8, results_path=None, retain_iter_history=False, sacrebleu=False, sampling=False, sampling_topk=-1, sampling_topp=-1.0, score_reference=False, seed=1, shard_id=0, share_input_output_embed=False, skip_invalid_size_inputs_valid_test=False, source_lang=None, target_lang=None, task='translation', temperature=1.0, tensorboard_logdir='', threshold_loss_scale=None, tokenizer=None, truncate_source=False, unkpen=0, unnormalized=False, upsample_primary=1, user_dir=None, warmup_updates=0, weight_decay=0.0)
| [src] dictionary: 4744 types
| [trg] dictionary: 3776 types
| loading model(s) from /home/dell/brx/pycorrector/pycorrector/conv_seq2seq/output/models/checkpoint_best.pt
Traceback (most recent call last):
  File "infer.py", line 42, in <module>
    temperature=config.temperature)
  File "infer.py", line 25, in infer
    return interactive.main(args)
  File "../../pycorrector/conv_seq2seq/interactive.py", line 151, in main
    translations = task.inference_step(generator, models, sample)
  File "/home/dell/anaconda3/envs/torch1.3/lib/python3.6/site-packages/fairseq/tasks/fairseq_task.py", line 265, in inference_step
    return generator.generate(models, sample, prefix_tokens=prefix_tokens)
  File "/home/dell/anaconda3/envs/torch1.3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/anaconda3/envs/torch1.3/lib/python3.6/site-packages/fairseq/sequence_generator.py", line 113, in generate
    return self._generate(model, sample, **kwargs)
  File "/home/dell/anaconda3/envs/torch1.3/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/dell/anaconda3/envs/torch1.3/lib/python3.6/site-packages/fairseq/sequence_generator.py", line 379, in _generate
    scores.view(bsz, beam_size, -1)[:, :, :step],
  File "/home/dell/anaconda3/envs/torch1.3/lib/python3.6/site-packages/fairseq/search.py", line 81, in step
    torch.div(self.indices_buf, vocab_size, out=self.beams_buf)
RuntimeError: result type Float can't be cast to the desired output type Long

GPU:RTX 3090

环境：
python3.6

conda环境：
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
_pytorch_select           0.2                       gpu_0  
blas                      1.0                         mkl  
ca-certificates           2021.5.30            ha878542_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
certifi                   2021.5.30        py36h5fab9bb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
cffi                      1.12.3           py36h2e261b9_0  
cudatoolkit               11.1.74              h6bb024c_0    <unknown>
cython                    0.29.24          py36h295c915_0  
dataclasses               0.8                pyh787bdff_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
fairseq                   0.9.0            py36hdb11119_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
intel-openmp              2021.3.0          h06a4308_3350  
jieba                     0.42.1                   pypi_0    pypi
ld_impl_linux-64          2.35.1               h7274673_9  
libffi                    3.2.1             hf484d3e_1007  
libgcc-ng                 9.3.0               h5101ec6_17  
libgfortran-ng            7.5.0               ha8ba4b0_17  
libgfortran4              7.5.0               ha8ba4b0_17  
libgomp                   9.3.0               h5101ec6_17  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libuv                     1.42.0               h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
mkl                       2020.2                      256  
mkl-service               2.3.0            py36he8ac12f_0  
mkl_fft                   1.3.0            py36h54f3939_0  
mkl_random                1.1.1            py36h0573a6f_0  
ncurses                   6.2                  he6710b0_1  
ninja                     1.10.2               hff7bd54_1  
numpy                     1.17.4           py36hc1035e2_0  
numpy-base                1.17.4           py36hde5b4d6_0  
openssl                   1.1.1k               h7f98852_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pip                       21.0.1           py36h06a4308_0  
portalocker               2.3.0            py36h06a4308_0  
pycparser                 2.20                       py_2  
pypinyin                  0.42.0                   pypi_0    pypi
python                    3.6.10               hcf32534_1  
python_abi                3.6                     2_cp36m    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
pytorch                   1.9.0           py3.6_cuda11.1_cudnn8.0.5_0    <unknown>
readline                  8.1                  h27cfd23_0  
regex                     2021.7.6         py36h7f8727e_0  
sacrebleu                 1.4.3                      py_0    powerai
setuptools                52.0.0           py36h06a4308_0  
six                       1.16.0             pyhd3eb1b0_0  
sqlite                    3.36.0               hc218d9a_0  
tk                        8.6.10               hbc83047_0  
torch                     1.8.0+cu111              pypi_0    pypi
torchaudio                0.8.0                    pypi_0    pypi
torchvision               0.9.0+cu111              pypi_0    pypi
tqdm                      4.36.1                     py_0  
typing                    3.10.0.0         py36h06a4308_0  
typing_extensions         3.10.0.0           pyha770c72_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
wheel                     0.37.0             pyhd3eb1b0_0  
xz                        5.2.5                h7b6447c_0  
zlib                      1.2.11               h7b6447c_3

**Comment by shibing624** [comment]
我没看懂出的啥错

**Comment by shibing624** [comment]
更新到最新版本代码，再试下，可以先用cpu预测。
