### ISSUE TITLE
base_demo.py 对输入文本处理后，输出为空

### ISSUE THREAD

**Issue by HuitMahoon** [shibing624/pycorrector#226]
### Describe the Question
已经下载`zh_giga.no_cna_cmn.prune01244.klm`文件，并放在指定文件夹。
安装了所有依赖，运行了一下demo样例，没有输出
`result= pycorrector.correct('少先队员因该为老人让坐')
    print(result)`
输出结果为`('少先队员因该为老人让坐', [])`

加载klm文件时间很长，电脑几乎要卡死。loaded log出来以后，并没有输出结果，为空。
难道是电脑内存不足以支撑吗？

### Describe your attempts
- [x] I walked through the tutorials
- [x] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by HuitMahoon** [comment]
之前出现问题是pip直接安装的。
重新用源码安装了一遍，问题不在出现。

**Comment by shibing624** [comment]
嗯，应该是pip版本与源码版本不一致，源码为最新的。
