### ISSUE TITLE
语言模型阈值

### ISSUE THREAD

**Issue by zhentaoCoding** [shibing624/pycorrector#229]
todo list 中语言模型纠错ppl阈值参数，使用动态调整方法替换写死的阈值。是怎么做的

**Comment by shibing624** [comment]
就是针对语言模型的方法，长句子的ppl均值跟短句子的ppl均值是不一样的，如果使用固定阈值，长句子的纠错会漏召回。方法：使用句子中各token的ppl值算偏移均值距离，疑似错误token就取最离谱的top token结果。
