### ISSUE TITLE
语言模型zh_giga.no_cna_cmn.prune01244.klm的疑问

### ISSUE THREAD

**Issue by expresschen** [shibing624/pycorrector#230]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [x] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
1.people2014corpus_chars.klm和zh_giga.no_cna_cmn.prune01244.klm是字级别的。
2.有词级别的模型，百度网盘有提供训练的。自己也可以训练词级别的模型。
3.评估纠错任务字模型好于词模型，所以默认用字模型。

**Comment by expresschen** [comment]
可以提供一个链接吗？我只找到了people2014corpus_word

**Comment by shibing624** [comment]
zh_giga.no_cna_cmn.prune01244.klm的训练数据无版权，不对外开源。

**Comment by wwfcnu** [comment]
> zh_giga.no_cna_cmn.prune01244.klm的训练数据无版权，不对外开源。

那这个模型除了二进制的，原始的arpa文件有吗

**Comment by shibing624** [comment]
无

**Comment by wwfcnu** [comment]
那有什么工具可以把klm文件转成arpa文件呢



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | Ming Xu ***@***.***> |
| 日期 | 2023年09月04日 17:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [shibing624/pycorrector] 语言模型zh_giga.no_cna_cmn.prune01244.klm的疑问 (#230) |

无

**Comment by shibing624** [comment]
klm是二进制格式；arpa是可读格式；出于数据保密和文件传输小考虑，都是使用过程中用klm格式。

不能转，源数据不开源。
