### ISSUE TITLE
请问您的工具包，只能针对错误字词进行纠正吗? 不能增加或者删除吗？（即只适用于文本对齐的纠正吗？）

### ISSUE THREAD

**Issue by SCU-JJkinging** [shibing624/pycorrector#237]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
规则模型不能，深度模型可以。

**Comment by jinxiang-unique** [comment]
请问是所有深度模型，还是只有seq2seq模型可以呢？

**Comment by daniellibin** [comment]
> 请问是所有深度模型，还是只有seq2seq模型可以呢？

macbert训练时需要错误的位置？只需要err_text和cor_text的训练的是不是只有seq2seq和transformer呢？

**Comment by shibing624** [comment]
1. macbert训练时需要错误的位置.
2. 是
