### ISSUE TITLE
训练seq2seq文件夹下的train.py 在执行验证的时候报错

### ISSUE THREAD

**Issue by jinxiang-unique** [shibing624/pycorrector#238]
![image](https://user-images.githubusercontent.com/59439162/138200829-cdb22903-3f91-4e80-be68-1adfb6930893.png)

![image](https://user-images.githubusercontent.com/59439162/138200679-86e2be8f-ee4a-42ed-92b4-c06e6e2f7bae.png)

**Comment by shibing624** [comment]
升级到最新代码试试
