### ISSUE TITLE
bertseq2seq 训练效果差

### ISSUE THREAD

**Issue by SCU-JJkinging** [shibing624/pycorrector#239]
您好，我用您的seq2seq文件夹下的 bertseq2seq 模型去训练，数据也是您 项目下的中文CGED数据集（约16000条）
![image](https://user-images.githubusercontent.com/59439162/138404513-46411c5a-cdf6-454d-b9a5-9f0960af473c.png)
但是训练完40个epoch后效果也不好。
![image](https://user-images.githubusercontent.com/59439162/138404433-92326dc3-8eb7-4cbe-88ca-cd86ac7804e2.png)
不知道是由于数据量太少的原因吗？

**Comment by shibing624** [comment]
1.6w条数据训练的生成模型，是会有这种不准的情况。
建议：
1.增加数据量，seq2seq任务等于从头学习文本生成，依赖上一个生成的字和输入文本的隐变量，而且模型生成结果容易走偏，可以引入nlpcc数据集，参考readme提供的NLPCC2018-GEC， 训练集trainingdata[解压后114.5MB]。
2.更改模型，纯生成的模型对纠错的拟合能力没有分类模型强，可以试试用macbert模型。检错可以看成一个错字挑选的逻辑，挨个字识别是否为错误；纠错可以看成一个token替换的逻辑，模型判定替换的字是否比没替换的字更通顺。

**Comment by SCU-JJkinging** [comment]
好的，万分感谢您！
