### ISSUE TITLE
小白，请教下word和char训练结果的问题

### ISSUE THREAD

**Issue by renxiaobin** [shibing624/pycorrector#24]
您好，我跑了您的代码，发现基于人民日报语料的模型，char训练的效果比word的好，甚至对于例子“少先队员应该为老人让座”，word给出的结果是 “先对员因该为老人让坐 [[('队', '对', 2, 3)]] ” ，按照我的理解，语料中如果出现了词组，准确率不是应该更高吗？为什么反而低了呢？

**Comment by shibing624** [comment]
准确率关联的点有很多，少先队员 如果成词了，那么就不会出现误杀的情况，否则有可能的。

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话重新open，我来跟进。
