### ISSUE TITLE
是否考虑多模型融合纠错

### ISSUE THREAD

**Issue by SevenMpp** [shibing624/pycorrector#241]
目前得模型都是单一进行纠错，并未将各模型得优点集合起来使用，导致各个模型得缺点都被放大，是否有考虑多模型联合纠错，减少单模型得问题，集合各模型得优点进而提高准确率。

**Comment by mosthandsomeman** [comment]
类似集成学习的思想，但是在自己的数据集上确实性能上不去

**Comment by shibing624** [comment]
工业的做法可以用多模型融合强化特定业务的纠错效果，但开源这块偏模型算法改进，暂不做融合模型硬提升效果。

**Comment by SevenMpp** [comment]
非常感谢您的答复，后续我可以传一些方法代码参与到项目中吗？

**Comment by SevenMpp** [comment]
已解决

**Comment by shibing624** [comment]
欢迎贡献代码。
