### ISSUE TITLE
观察macbert的测试结果，出现很多改成跟原句语义相似的答案，但却不是我们想要的输出。能否通过构造混淆集进一步筛选得出结果?

### ISSUE THREAD

**Issue by mosthandsomeman** [shibing624/pycorrector#242]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
混淆集一般是适配自己领域的数据，建议自己基于纠错集构建。如果是比较paper的sighan数据效果，可以直接用sighan数据生成纠错pair做混淆集。

**Comment by mosthandsomeman** [comment]
非常感谢您的答复!
