### ISSUE TITLE
How to construct Chinese confusion set？

### ISSUE THREAD

**Issue by mosthandsomeman** [shibing624/pycorrector#243]
- [ ] I checked to make sure that this is not a duplicate issue
- [ ] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/shibing624/pycorrector))

### Additional Information
Other things you want the developers to know.

**Comment by mosthandsomeman** [comment]
目前只搜到这个，汉字种子混淆集的构建方法研究

**Comment by shibing624** [comment]
这是个paper吗，你的意思是要自动构建吗？
我觉得手动标注构建比较合适吧。

**Comment by mosthandsomeman** [comment]
http://www.jsjkx.com/CN/article/openArticlePDF.jsp?id=1718是比较早的paper，目前是自己一个人在学习这块，手动标注恐工作量有点大。徐老师，目前企业里都是手动标注吗？还是有新的paper中的方法

**Comment by shibing624** [comment]
一般有标注团队。

加混淆集可能会带来误杀，如：
江大桥 姜大桥

'我的老师江大桥' -》 ('我的老师姜大桥', [('江大桥', '姜大桥', 4, 7)])
'我的心灵支持长江大桥' -》 ('我的心灵支持长姜大桥', [('江大桥', '姜大桥', 7, 10)])
