### ISSUE TITLE
请问在定位confusion错误时，为何不将custom_confusion中的词加入分词词典，然后遍历分词结果，在custom_confusion即为错误？

### ISSUE THREAD

**Issue by chenxiaoyouyou** [shibing624/pycorrector#244]
而是使用这样的方法
https://github.com/shibing624/pycorrector/blob/0ed7db43daf613ee2da782edb3b8e2ab67ec58a8/pycorrector/detector.py#L364
我感觉加入词典的方式速度会更快一点呢，不知道效果会不会有影响

**Comment by shibing624** [comment]
加到分词词典过：https://github.com/shibing624/pycorrector/blob/0ed7db43daf613ee2da782edb3b8e2ab67ec58a8/pycorrector/detector.py#L183

**Comment by chenxiaoyouyou** [comment]
感谢回复，抱歉没有看到tokenizer，这样的话，混淆集检测是常开的，词检测和字符检测是可以开关的，理解啦，再次感谢
