### ISSUE TITLE
请问seq2seq有没有已经训练好的模型呢？

### ISSUE THREAD

**Issue by daniellibin** [shibing624/pycorrector#245]
作者您和，
请问seq2seq有没有已经训练好的模型呢？(nlpcc2018+hsk，130万对句子)训练，train_loss大概需要将到多少才符合预期？

感谢作者解答

**Comment by shibing624** [comment]
在改进训练中，当前效果不够好，没有放出训练好的seq2seq模型。
loss大概0.4以内，跟训练数据质量有关。

**Comment by daniellibin** [comment]
> 在改进训练中，当前效果不够好，没有放出训练好的seq2seq模型。 loss大概0.4以内，跟训练数据质量有关。

请问目前针对语法和拼写均需纠错的，哪种模型效果较好呢？
之前看了以下今年科大讯飞举办的纠错比赛，貌似只有baseline,前几名都没有开源
