### ISSUE TITLE
请问有没有开源的方法生成样本？根据正确句子使用音似或者形似，结合分词策略，生成字粒度和词粒度的错误样本。

### ISSUE THREAD

**Issue by mosthandsomeman** [shibing624/pycorrector#246]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
这不是一个脚本的问题吗，自己写吧。

**Comment by mosthandsomeman** [comment]
应该是想多了，那知道怎么做了，谢谢
