### ISSUE TITLE
请问只能训练对齐语料数据集吗，如果可以训练非对齐语料，请问可以利用哪个模型，怎么构建数据集？

### ISSUE THREAD

**Issue by babyMonkey8** [shibing624/pycorrector#247]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
convseq2seq
