### ISSUE TITLE
seq2seq训练完成后 运行infer.py 结果不显示

### ISSUE THREAD

**Issue by ddddddhy** [shibing624/pycorrector#248]
### Describe the Question
seq2seq训练完成后，生成了decode和encode。但是运行infer.py时结果不显示。训练集有三千多条数据，请问是因为数据量太少了吗？

[  DEBUG 20211209 02:34:54 infer:  29] device: cuda
[  DEBUG 20211209 02:34:54 infer:  62] use bert seq2seq model.
Generating outputs: 100%|██████████| 1/1 [00:02<00:00,  2.53s/it]
input  : 老是较书。
predict:

input  : 感谢等五分以后，碰到一位很棒的奴生跟我可聊。
predict:

input  : 遇到一位很棒的奴生跟我聊天。
predict:

input  : 遇到一位很美的女生跟我疗天。
predict: 

input  : 他们只能有两个选择：接受降新或自动离职。
predict:

input  : 王天华开心得一直说话。
predict:

Press any key to continue . . .

**Comment by babyMonkey8** [comment]
同问，我也遇到这样的情况
