### ISSUE TITLE
你好。我按照pip install pycorrect。安装完毕之后。然后想把纠错的工程用到我自己写的小项目上。但是加载词典和语言模型，都是从安装路径上加载。我想有自己的模型和词典。怎么样才能从data里面加载呢？

### ISSUE THREAD

**Issue by BravHer** [shibing624/pycorrector#25]

**Comment by cloudfool** [comment]
我想把你在云盘里提供的语言模型people2014corpus_chars.klm替换默认的模型，是不是在config.py里把language_model_path 改成'data/kenlm/people2014corpus_chars.klm'， 就可以了？
我这边运行你默认的模型是正常的，可是换成云盘里下载的people2014corpus_chars.klm就报错：illegal instruction (core dumped)， 这个情况你知道原因可能是什么么？谢谢

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话重新open，我来跟进。

**Comment by LMXKO** [comment]
@shibing624 您好，请问加载自定义词典的接口还有吗？

**Comment by shibing624** [comment]
set_custom_word

**Comment by shibing624** [comment]
examples/load_custom_language_model.py
