### ISSUE TITLE
macbert纠错模型检测模块的权重

### ISSUE THREAD

**Issue by core-power** [shibing624/pycorrector#250]
![1640572220(1)](https://user-images.githubusercontent.com/34341180/147428469-b97d4615-3616-4631-aee2-5b791a4d7668.jpg)
pycorrector程序中加载macbert之后，打印模型图层名和权重似乎和macbert4csc.py的模型结构不一样，想问下pycorrector加载的macbert纠错模型的检测模块权重图层名叫啥名字，谢谢大佬。

**Comment by shibing624** [comment]
detection

**Comment by core-power** [comment]
用transformers加载模型推理的例子中打印模型权重并没有看到detection图层

**Comment by zhihanyang2022** [comment]
同问。直接用transformer去from_pretrained并没有看到detection。

**Comment by shibing624** [comment]
same to https://github.com/shibing624/pycorrector/issues/249
