### ISSUE TITLE
win 10 无法按kenlm

### ISSUE THREAD

**Issue by wangjunjx8868** [shibing624/pycorrector#253]
### Describe the Question
win 10 无法按kenlm ，然后用centos 7 也不行 少C++11，结果C++ 环境装不上

**Comment by shibing624** [comment]
docker跑，环境不用安装。

**Comment by realRoc** [comment]
> 
Docker跑的时候发现还需要从https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm
下载data
我遇到的问题是这个地址好像无法解析？
报错信息（很抱歉暂时不方便放上完整信息）：
socket.gaierror: [Error -2] Name or service not known
