### ISSUE TITLE
预训练语言模型ppl打分

### ISSUE THREAD

**Issue by zhentaoCoding** [shibing624/pycorrector#256]
如果想使用transformer类的预训练语言模型做ppl打分，应该怎么做

**Comment by shibing624** [comment]
按PPL公式算下就有了：
![image](https://user-images.githubusercontent.com/10249622/151518015-1c8ac881-b3dd-41f6-877b-c558a276b39b.png)
语言模型下，perplexity = math.exp(loss) 就是。

可以参考https://blog.csdn.net/pearl8899/article/details/112854900
