### ISSUE TITLE
如何提高模型加载速度

### ISSUE THREAD

**Issue by EASTERNTIGER** [shibing624/pycorrector#257]
老师您好，我使用bert模型进行计算，但是发现模型加载和计算速度非常慢，对一句中文进行纠错的时候首先加载bert模型需要几秒，接下来加载语言模型需要几秒，最后加载字典文件也需要几秒，也就是一句话纠错可能总共需要15-20秒的时间，请问老师除了硬件设备外有什么改善方法吗？

**Comment by shibing624** [comment]
自己搭个flask的api服务，直接通过api调用。模型加载时间跟模型预测耗时无关。

**Comment by EASTERNTIGER** [comment]
好的，明白了，谢谢老师~
