### ISSUE TITLE
CGED2018的测试集在哪下载

### ISSUE THREAD

**Issue by dqqcasia** [shibing624/pycorrector#26]
你好，我在https://pan.baidu.com/s/1lAw7Pqrp1VhdtcbfMLjzDA 下载的数据没有看到2018的测试集，所以想问一下你知不知道2018的测试集在哪里下载呢

**Comment by dqqcasia** [comment]
还有就是有没有官方的评测脚本，我也没有找到

**Comment by dqqcasia** [comment]
谢谢你哈，我按照官网给的百度网盘下的zip压缩包里并没有2018的测试集，另外，麻烦问一下2018测试集的Truth文件有吗......

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话重新open，我来跟进。

**Comment by tzuw** [comment]
你好~ @shibing624 ，

（1）最近在看CGED相关论文，在官网没有找到CGED‘2018官方的评测脚本，只有找到前几年的脚本，好像并没有关于纠正任务的评测工具，不知道是不是我漏看了 。

（2）另外，还有一个小问题，想请教 目录 pycorrector/pycorrector/data/ 下 的，common_char_set.txt、custom_confusion.txt、same_pinyin.txt、same_stroke.txt 等文件，是怎么整理出来的呢？觉得是很棒的资源：）

感谢！

**Comment by shibing624** [comment]
1） 2018的评测脚本官方并没给出；
2）数据我搜集整理的。
