### ISSUE TITLE
macbert微调

### ISSUE THREAD

**Issue by ZTurboX** [shibing624/pycorrector#260]
macbert微调，大概迭代到几轮达到了指标

**Comment by shibing624** [comment]
本质是一样，backbone都是BertForMaskedLM

**Comment by okcd00** [comment]
@zhentaoCoding 我这边跑 5 轮 （SIGHAN13-15 除去 SIGHAN15_test；Wang271K）作为训练集，我在模型网络上有加一些其它的东西，可以在第 3 个 epoch 收敛。结论是我这个训练可以达到 repo 里相应指标的高度，也许可以作参考。

@shibing624 老师您好，关于评估指标有个小问题：
我用同一个模型的 predict 结果来跑 evaluation.py 里的句子级别评价指标 F1 和我用 iqiyi 的 FASPELL 的句子级别评价指标[脚本](https://github.com/iqiyi/FASPell/blob/5060b220423181f7bcc66a2a1830cf60f4835da7/faspell.py#L508)算出来的会有些不同（FASPELL 的计算方式 F1 总是会低一些）。想咨询一下 pycorrector 这里的指标对比计算上哪一种会更加常用一些呢？

**Comment by shibing624** [comment]
iqiyi的计算也放这里了的：https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/evaluate_util.py 字和句子粒度的放一起统计的。

我常用句子粒度的F1计算，比较简单。

**Comment by okcd00** [comment]
哈哈，有这一行，那这个 iqiyi 的评测指标函数确实是我写的，不过是在 BBCM 那个 repo 里写的：
``` python
# wrong, correct, predict, d_tgt, d_predict = item
```

那确实两种计算方法得出的结果会不一样呢…… 我好好研究一下区别，谢谢~

**Comment by zhentaoCoding** [comment]
> @zhentaoCoding 我这边跑 5 轮 （SIGHAN13-15 除去 SIGHAN15_test；Wang271K）作为训练集，我在模型网络上有加一些其它的东西，可以在第 3 个 epoch 收敛。结论是我这个训练可以达到 repo 里相应指标的高度，也许可以作参考。
> 
> @shibing624 老师您好，关于评估指标有个小问题： 我用同一个模型的 predict 结果来跑 evaluation.py 里的句子级别评价指标 F1 和我用 iqiyi 的 FASPELL 的句子级别评价指标[脚本](https://github.com/iqiyi/FASPell/blob/5060b220423181f7bcc66a2a1830cf60f4835da7/faspell.py#L508)算出来的会有些不同（FASPELL 的计算方式 F1 总是会低一些）。pycorrector 这里的指标计算看起来更加直观简单一些，所以想了解一下在指标对比计算上，这两种的哪一种会更加常用一些呢？

我用paddle改写了macbert方法，用Wang271K训练，效果远没达到指标，感觉是我有地方写的有问题

**Comment by okcd00** [comment]
@zhentaoCoding 我的做法是上面我说的训练集按9:1分训练集和验证集。用验证集loss最低时的模型参数来做评估。使用pycorrector 这边的评测方法可以达到差不多的效果。一个想法是你仅在Wang271k上（看起来你是没有加入其他的sighan数据）拟合好了之后，和SIGHAN15的错误类型分布有较大不同？

但我在网络基础上有加一些额外的结构和loss，没有做过原版网络的实验，所以也说只能是仅作参考啦。

**Comment by zhentaoCoding** [comment]
> @zhentaoCoding 我的做法是上面我说的训练集按9:1分训练集和验证集。用验证集loss最低时的模型参数来做评估。使用pycorrector 这边的评测方法可以达到差不多的效果。一个想法是你仅在Wang271k上（看起来你是没有加入其他的sighan数据）拟合好了之后，和SIGHAN15的错误类型分布有较大不同？
> 
> 但我在网络基础上有加一些额外的结构和loss，没有做过原版网络的实验，所以也说只能是仅作参考啦。

我加入SIGHAN15训练数据试试

**Comment by zhentaoCoding** [comment]
> @zhentaoCoding 我的做法是上面我说的训练集按9:1分训练集和验证集。用验证集loss最低时的模型参数来做评估。使用pycorrector 这边的评测方法可以达到差不多的效果。一个想法是你仅在Wang271k上（看起来你是没有加入其他的sighan数据）拟合好了之后，和SIGHAN15的错误类型分布有较大不同？
> 
> 但我在网络基础上有加一些额外的结构和loss，没有做过原版网络的实验，所以也说只能是仅作参考啦。

加了SIGHAN15训练数据，指标就上去了
