### ISSUE TITLE
请问 macbert 如何进行误杀矫正？

### ISSUE THREAD

**Issue by bingxin3chen** [shibing624/pycorrector#262]
### Describe the Question
macbert 对于误杀的矫正要怎么做呢。例如：'春节发货不', '春节发货部', [('不', '部', 4, 5)] ，明明正确的句子矫正成错的了。

### Describe your attempts
我知道训练需矫正数据格式要怎么构建，eg：'请问是从那里发过来的', '请问是从哪里发过来的', [('那', '哪', 4, 5)]
但对于误杀的情况要怎么减少模型误杀呢？可否请作者给个例子，或教一下方法。

Ps：我所用的 pycorrector 版本为  0.4.2

**Comment by shibing624** [comment]
1. 把badcase改正后加到训练集：'春节发货部' -> '春节发货不', 
2. 自己写个词典过滤掉误杀的词。

**Comment by bingxin3chen** [comment]
哦，再反着来一遍吗，懂了懂了，谢谢

**Comment by bingxin3chen** [comment]
对于第 2 点，写个词典过滤掉误杀的词，能详细说下吗，没怎么懂。(新手，请见谅)

**Comment by shibing624** [comment]
输入句子中，遇到词语 ’发货不‘，过滤。

**Comment by bingxin3chen** [comment]
谢谢作者大佬指点，经过漫长的标注、训练后，效果确实得到了不错的改善。
Ps：顺便贴上自己训练数据的格式，希望对其他人也有帮助^_^
![image](https://user-images.githubusercontent.com/89672905/158333404-619aedde-afae-4306-a5b1-ddee5cc0c03d.png)
