### ISSUE TITLE
convseq2seq训练loss为0

### ISSUE THREAD

**Issue by Hachiiiiii** [shibing624/pycorrector#264]
使用convseq2seq训练的时候，loss一直为0，但是最开始加载的时候能正常计算loss，不知道哪里出了问题，请问您有遇到过这样的情况吗？有没有什么解决办法呀

**Comment by shibing624** [comment]
1、补充样本，数据集小了的话loss就下降比较离谱。
2、使用我release的convseq2seq模型（readme有下载地址），可以在上面继续训练。
