### ISSUE TITLE
关于句子级别评价标准

### ISSUE THREAD

**Issue by wangwang110** [shibing624/pycorrector#266]
### Describe the bug
测了一下macbertcsc的评价指标，发现测出来的结果，比我自己写的评价代码要高出许多
![clipboard](https://user-images.githubusercontent.com/21475557/160791064-06564254-515c-41c0-883e-df4ea67760e8.png)

原有的代码是不是忽略了一种情况，原句和目标句不一样，预测句修改了，但是改得和目标句不一样，这些没算进p值得分母。

据我了解，很多论文都是用，所有修改过的句子总数，作为分母。虽然指标上低一点，但是我认为更加合理。

### To Reproduce
Please provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) here. We hope we can simply copy/paste/run it. It is also nice to share a hosted runnable script (e.g. Google Colab), especially for hardware-related problems.

### Describe your attempts
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
我觉得严格按照precision的定义来算p没啥问题，如果要看准确率看acc就可以。
