### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by YuanJingtai** [shibing624/pycorrector#267]
您好，我在使用pip安装时
Python\Lib\site-packages\pycorrector目录下
并没有ernie_csc文件夹

**Comment by shibing624** [comment]
1）pip下一版本0.4.3加上
2）当前用源码安装。

**Comment by shibing624** [comment]
fixed: pip install pycorrector>=0.4.4

pypi link: https://pypi.org/project/pycorrector/0.4.4/

**Comment by YuanJingtai** [comment]
**我重新安装，问题已经解决！**
