### ISSUE TITLE
能提供其他載點下載 people2014corpus_chars.klm 嗎?

### ISSUE THREAD

**Issue by shadowjohn** [shibing624/pycorrector#268]
shibing624 您好,

因為您提供的 people2014corpus_chars.klm 放在百度盤，國外註冊百度相當麻煩，一直無法成功
請問您方便傳到其他地方，如 https://deepspeech.bj.bcebos.com/zh_lm/people2014corpus_chars.klm 
供下載嗎

希望您能幫忙，感恩不盡

**Comment by shibing624** [comment]
[people_chars_lm.klm](https://github.com/shibing624/pycorrector/releases/download/0.4.3/people_chars_lm.klm)

release 里面就有https://github.com/shibing624/pycorrector/releases，最新代码也能直接从github下载该模型。

**Comment by shadowjohn** [comment]
謝謝您~~~
