### ISSUE TITLE
一次只能检测两个错误吗？

### ISSUE THREAD

**Issue by moguangjian** [shibing624/pycorrector#269]
### Describe the bug
我输入了“少仙队员因该为老人让坐”，只检测出了少先队与应该，“让坐”没检测出来

### To Reproduce
corrected_sent, detail = pycorrector.correct('少仙队员因该为老人让坐')
print(corrected_sent, detail)

### Describe your attempts
- [ ] I checked the documentation and found no answer
- [ ] I checked to make sure that this is not a duplicate issue

You should also provide code snippets you tried as a workaround, StackOverflow solution that you have walked through, or your best guess of the cause that you can't locate (e.g. cosmic radiation).

### Context
 - **OS** [e.g. Windows 10, macOS 10.14]: 
 - **Hardware** [e.g. CPU only, GTX 1080 Ti]: 

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

### Additional Information
Other things you want the developers to know.

**Comment by shibing624** [comment]
是模型漏检测了，模型的原因，一般一句话有一个错误比较常见，多个错误比较少，模型没cover这类极端case
