### ISSUE TITLE
大规模语料训练kenlm内存泄漏

### ISSUE THREAD

**Issue by ZTurboX** [shibing624/pycorrector#270]
用大规模语料训练kenlm，使用模型时会内存泄漏

**Comment by shibing624** [comment]
是内存爆了吗？还是kenlm代码本身的原因

**Comment by shibing624** [comment]
maybe this help you  https://github.com/kpu/kenlm/issues/185

**Comment by sunM123** [comment]
训练时可以使用-S 参数来控制内存使用，例如：-S 10%

**Comment by zhentaoCoding** [comment]
> 是内存爆了吗？还是kenlm代码本身的原因

预测时，大量请求，内存会爆满，很久不会释放
