### ISSUE TITLE
请问 zh_giga.no_cna_cmn.prune01244.klm(2.8G) 这个模型的语料如何获取？

### ISSUE THREAD

**Issue by qurikuduo** [shibing624/pycorrector#272]
### Describe the Question
我想在zh_giga.no_cna_cmn.prune01244.klm(2.8G)的基础上继续强化这个模型。

### Describe your attempts
- [ ] 请问哪里能找到产生这个模型的语料？
- [ ] 或者请问这个语料的名字叫什么？

多谢。

**Comment by shibing624** [comment]
语料不开源。

**Comment by qurikuduo** [comment]
好的，多谢。
