### ISSUE TITLE
macbert预测长文本时(经过split_text_by_maxlen方法切割后)，结果的下标会出错。

### ISSUE THREAD

**Issue by Deep-sea-boy** [shibing624/pycorrector#275]
`    error_sentences = [
        '6、在陈刚担任公司董事、监事、高级管理人员期间，每年转让本公司持有的公司股份数量不超过直接或间接持有公司股份总数的25%，所持股份总数不超过1,000股的除外；在陈刚离职六个月内，不转让本公司所持有的公司股份；陈刚在担任公司董事、监事、高级管理人员任期届满前离职的，在其就任时确定的任期内和任期届满后6个月内，本公司每年转让持有的公司股份数量不超过直接或间接持有公司股份总数的25%，离职陈刚后半年内，本公司不转让所持本公司股份。'
    ]`

run的文件位置： pycorrector/macbert/macbert_corrector.py

程序运行结果：
`original sentence:6、在陈刚担任公司董事、监事、高级管理人员期间，每年转让本公司持有的公司股份数量不超过直接或间接持有公司股份总数的25%，所持股份总数不超过1,000股的除外；在陈刚离职六个月内，不转让本公司所持有的公司股份；陈刚在担任公司董事、监事、高级管理人员任期届满前离职的，在其就任时确定的任期内和任期届满后6个月内，本公司每年转让持有的公司股份数量不超过直接或间接持有公司股份总数的25%，离职陈刚后半年内，本公司不转让所持本公司股份。 => 6、在陈刚担任公司董事、监事、高级管理人员期间，每年转让本公司持有的公司股份数量不超过直接或间接持有公司股份总数的25%，所持股份总数不超过1,000股的除外；在陈刚离职六个月内，不转让本公司所持有的公司股份；陈刚在担任公司董事、监事、高级管理人员任期届满先离职的，在其就任时确定的任期内和任期届满后6个月内，本公司每年转让持有的公司股份数量不超过直接或间接持有公司股份总数的25%，离职离满后半年内，本公司不转让所持本公司股份。 err:[('前', '先', 0, 1), ('陈', '离', 66, 67), ('刚', '满', 67, 68)]`

**Comment by shibing624** [comment]
fixed.
