### ISSUE TITLE
MacBERT等深度模型误纠解决思路

### ISSUE THREAD

**Issue by ZTurboX** [shibing624/pycorrector#276]
MacBERT等深度模型结合ngram规则纠错效果相对很好，但深度模型误纠比较高，请问有什么解决思路呢

**Comment by shibing624** [comment]
1、模型优化：补充负例case（无错样本），把误纠的填进去；
2、专名过滤：人名、地名、专名等词加到 confusion dict，过滤处理；
3、输出macbert纠错置信度，只纠正高置信度错误。

**Comment by zhentaoCoding** [comment]
> 1、模型优化：补充负例case（无错样本），把误纠的填进去； 2、专名过滤：人名、地名、专名等词加到 confusion dict，过滤处理； 3、输出macbert纠错置信度，只纠正高置信度错误。

macbert纠错置信度是怎么算的

**Comment by shibing624** [comment]
softmax的概率值就是
