### ISSUE TITLE
针对文本的输入出输出不对齐，即经过asr处理之后有不少重叠字、多字、少字，应该怎么处理。

### ISSUE THREAD

**Issue by xiaohuzi1996** [shibing624/pycorrector#277]
针对文本的输入出输出不对齐，即经过asr处理之后有不少重叠字、多字、少字，应该怎么处理。

**Comment by xiaohuzi1996** [comment]
用了seq2seq感觉效果太差了

**Comment by xiaohuzi1996** [comment]
疑似错误检测用了，pycorrector.detect。
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”
输入：
pycorrector.detect('尼你你你你你你你你你你是不是一个大傻子啊，这个题题木木你不会吗')
输出：
[['尼', 0, 1, 'char'], ['题题', 23, 25, 'word'], ['木木', 25, 27, 'word']]
“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”“”
对于多字的情况，检测不到‘你’的错误。有推荐的方法来检测疑似错误吗？

**Comment by shibing624** [comment]
1、方法上面有写。
2、单这个case看，’你‘并不是多字错误。

**Comment by xiaohuzi1996** [comment]
‘你’不属于多字错误吗？那是属于什么呢

**Comment by yuzhang112** [comment]
专业名词的多词、少词问题的纠错有什么好方法吗

**Comment by vFire** [comment]
这都不明白嘛，你你你你你，可以是语气重复使用。。。
你你你你你真坏！这句子没错。
打你你你你你你哦！ 这句子就错了！
兄弟~

**Comment by xiaohuzi1996** [comment]
呃呃呃，看你怎么理解吧，不同人的理解角度不一样啊，我问你，重复的字符串的长度有没有增加。长度增加了算不算多的呢

**Comment by shibing624** [comment]
用T5试下多字少字。
