### ISSUE TITLE
bertseq2seq预测每次都是空

### ISSUE THREAD

**Issue by xiaohuzi1996** [shibing624/pycorrector#278]
针对seq2seq，convseq2seq预测的结果正常，但是对于bertseq2seq预测每次都是空，id输出如下图。

![image](https://user-images.githubusercontent.com/55837663/170214174-8cab897f-afee-4dbf-b9aa-06072e612759.png)

![1653466448(1)](https://user-images.githubusercontent.com/55837663/170214785-01314680-18a3-40b9-b8bf-ee0bfdcd1193.png)

**Comment by xiaohuzi1996** [comment]
这个推理问题麻烦有时间跟进一下哈

**Comment by yc930401** [comment]
我运行也是这样

**Comment by shibing624** [comment]
使用bartseq2seq模型训练和预测吧，该部分代码我写到textgen库了，https://github.com/shibing624/textgen/blob/main/examples/seq2seq/training_bartseq2seq_zh_demo.py

pycorrector中的bertseq2seq代码下个版本会删除。
