### ISSUE TITLE
运行模型badcase记录

### ISSUE THREAD

**Issue by wangyingshuai** [shibing624/pycorrector#28]
楼主，您好！我在运行examples下面的use_custom_confusion.py文件时，遇到下面两个badcase，第一个badcase是：我把iPhone 差=>iPhoneX这一对词语加到了my_confusion.txt中，但是运行结果把iPhone差纠正为iPhone查，并没有输出我期待的iPhoneX，运行结果如下【original sentence:iPhone差。 => correct sentence:('iPhone查。', [['差', '查', 6, 7]])】；
第二个badcase是我把 小明同学=>小茗同学这一对词语也加入到了my_confusion.txt中，然后我输入一句话“我想喝小明同学”，尽管模型正确地把“小明同学”改成了“小茗同学”，但是整句话的分词显然不正确，运行结果如下【original sentence:我想喝小明同学。 => correct sentence:('我像喝小茗同学。', [['我想', '我像', 0, 2], ['喝小明', '喝晓明', 2, 5], ['小明同学', '小茗同学', 3, 7]])
】
希望您能对以上两个问题给出解决方法，非常感谢！

**Comment by shibing624** [comment]
已经修复，请查看examples下面use_custom_confusion.py

**Comment by shibing624** [comment]
由于结巴分词器会把英文转为小写，所以请注意添加英文词时保持小写即可。

**Comment by wangyingshuai** [comment]
恩，明白了，非常感谢楼主，你的github是我看到的最好的文本纠错模型，点赞！

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话请重新open，我来跟进。
