### ISSUE TITLE
kenlm  ngram score

### ISSUE THREAD

**Issue by ZTurboX** [shibing624/pycorrector#280]
用kenlm算出来的ngram score是负数是正常的吗

**Comment by shibing624** [comment]
正常。

score函数输出的是对数概率，分数输出为负数，越接近于0越好。该模块可以用来测试词条与句子的通顺度。model.score("this is a sentence .")是输出 log10 p(this is a sentence . </s> | <s>)的似然概率值。

链接：https://blog.csdn.net/qq_16829085/article/details/102518798
