### ISSUE TITLE
macbert4csc是否支持在目标域数据上进行Further Pre-training

### ISSUE THREAD

**Issue by JingyangXu1991** [shibing624/pycorrector#283]
您好，在之前实验中发现，若bert先用目标域数据进行预训练再finetune，是能够提升一些下游任务效果的，所以想问下macbert4csc是否可以类似于bert，在目标域数据上进行Further Pre-training呢

**Comment by shibing624** [comment]
可以

**Comment by JingyangXu1991** [comment]
> 可以

好的，感谢回复
