### ISSUE TITLE
非对齐文本语法纠错怎么做？

### ISSUE THREAD

**Issue by zhoukaiwei66** [shibing624/pycorrector#285]
您好，对于文本非对齐任务，多字少字问题，我试了生成式unilm模型和序列标注的gector模型 ，效果都不好，请问有什么好一点的解决办法么或者处理这类问题的思路么？谢谢您！！

**Comment by shibing624** [comment]
T5

**Comment by ImXunan** [comment]
您好，我想问一下您对于文本不对齐的情况是如何计算PRF的？

**Comment by zhoukaiwei66** [comment]
> 

你好，我看的文本语法纠错 gector 是基于序列标注进行的，所以PRF和正常的计算方式一样，github有源码，如果是文本生成或者摘要这样的任务，建议看一下BLEU，ROUGE，METEOR，一般用这些方式作为评价指标

**Comment by zhoukaiwei66** [comment]
> 您好，我想问一下您对于文本不对齐的情况是如何计算PRF的？



> 您好，我想问一下您对于文本不对齐的情况是如何计算PRF的？

你好，我看的文本语法纠错 gector 是基于序列标注进行的，所以PRF和正常的计算方式一样，github有源码，如果是文本生成或者摘要这样的任务，建议看一下BLEU，ROUGE，METEOR，一般用这些方式作为评价指标

**Comment by ImXunan** [comment]
您好，目前我看的开源的代码基本上是英文的语法纠错，请问您找到什么关于中文语法纠错的开源代码，可以推荐一下吗？

**Comment by zhoukaiwei66** [comment]
> 您好，目前我看的开源的代码基本上是英文的语法纠错，请问您找到什么关于中文语法纠错的开源代码，可以推荐一下吗？

看一下gector, t5, seq2seq,这些都是我看的别人的纠错方案里面常用的，https://github.com/HillZhang1999/MuCGEC,看一下这个，作者是ctc2021的冠军
