### ISSUE TITLE
运行T5 demo效果有点问题，请问有遇到过吗 谢谢

### ISSUE THREAD

**Issue by shelleyyyyu** [shibing624/pycorrector#290]
直接跑的pycorrecter 里T5的demo 结果好像有点问题 请问有遇到过吗 谢谢
original sentence:妈妈说："别趴地上了，快起来，你还吃饭吗？"，我说："好。"就扒起来了。 => 逮逮逮："逮逮逮逮逮，逮逮逮，逮逮逮逮逮？"，逮逮："逮。"逮逮逮逮逮。 err:[('妈', '逮', 0, 1), ('妈', '逮', 1, 2), ('说', '逮', 2, 3), ('别', '逮', 5, 6), ('趴', '逮', 6, 7), ('地', '逮', 7, 8), ('上', '逮', 8, 9), ('了', '逮', 9, 10), ('快', '逮', 11, 12), ('起', '逮', 12, 13), ('来', '逮', 13, 14), ('你', '逮', 15, 16), ('还', '逮', 16, 17), ('吃', '逮', 17, 18), ('饭', '逮', 18, 19), ('吗', '逮', 19, 20), ('我', '逮', 23, 24), ('说', '逮', 24, 25), ('好', '逮', 27, 28), ('就', '逮', 30, 31), ('扒', '逮', 31, 32), ('起', '逮', 32, 33), ('来', '逮', 33, 34), ('了', '逮', 34, 35)]
original sentence:你说：“怎么办？”我怎么知道？ => 叫他：“他叫他？”那宗叫他叫？叫他 err:[('你', '叫', 0, 1), ('说', '他', 1, 2)

**Comment by shelleyyyyu** [comment]
original sentence:妈妈说："别趴地上了，快起来，你还吃饭吗？"，我说："好。"就扒起来了。 => 逮逮逮："逮逮逮逮逮，逮逮逮，逮逮逮逮逮？"，逮逮："逮。"逮逮逮逮逮。 err:[('妈', '逮', 0, 1), ('妈', '逮', 1, 2), ('说', '逮', 2, 3), ('别', '逮', 5, 6), ('趴', '逮', 6, 7), ('地', '逮', 7, 8), ('上', '逮', 8, 9), ('了', '逮', 9, 10), ('快', '逮', 11, 12), ('起', '逮', 12, 13), ('来', '逮', 13, 14), ('你', '逮', 15, 16), ('还', '逮', 16, 17), ('吃', '逮', 17, 18), ('饭', '逮', 18, 19), ('吗', '逮', 19, 20), ('我', '逮', 23, 24), ('说', '逮', 24, 25), ('好', '逮', 27, 28), ('就', '逮', 30, 31), ('扒', '逮', 31, 32), ('起', '逮', 32, 33), ('来', '逮', 33, 34), ('了', '逮', 34, 35)]

**Comment by shibing624** [comment]
训练不充分。
