### ISSUE TITLE
T5模型效果很好，但是get_errors这个函数有个小bug，麻烦修改一下哦

### ISSUE THREAD

**Issue by yc930401** [shibing624/pycorrector#291]
原文：【各省自治区直辖市人民政府，国院各部委各直属机构，】
错误解读：这里【国务院】错写为【国院】
在get_error()之前，修改正确！=>  【各省自治区直辖市人民政府,国务院各部委各直属机构。】
并且不应该有这句corrected_text = decode_tokens[:len(text)]  因为可能要加字，长度有变。
在get_error()之后，反而错了！ => 【各省自治区直辖市人民政府，国务院各部委各直属机，。】
感觉主要错在 pass not chinese char，不应该pass，不应该把标点符号放回原位。标点符号和中文文字一样，T5模型都能处理好。

**Comment by shelleyyyyu** [comment]
您好，请问您是在哪个pretrained model下跑的呀？我跑的T5用的官方代码出来变成
original sentence:妈妈说："别趴地上了，快起来，你还吃饭吗？"，我说："好。"就扒起来了。 => 逮逮逮："逮逮逮逮逮，逮逮逮，逮逮逮逮逮？"，逮逮："逮。"逮逮逮逮逮。 err:[('妈', '逮', 0, 1), ('妈', '逮', 1, 2), ('说', '逮', 2, 3), ('别', '逮', 5, 6), ('趴', '逮', 6, 7), ('地', '逮', 7, 8), ('上', '逮', 8, 9), ('了', '逮', 9, 10), ('快', '逮', 11, 12), ('起', '逮', 12, 13), ('来', '逮', 13, 14), ('你', '逮', 15, 16), ('还', '逮', 16, 17), ('吃', '逮', 17, 18), ('饭', '逮', 18, 19), ('吗', '逮', 19, 20), ('我', '逮', 23, 24), ('说', '逮', 24, 25), ('好', '逮', 27, 28), ('就', '逮', 30, 31), ('扒', '逮', 31, 32), ('起', '逮', 32, 33), ('来', '逮', 33, 34), ('了', '逮', 34, 35)]

**Comment by yc930401** [comment]
我用t5文件夹下的train.py训练的，可以用27万的那个sighan数据集..训练完以后再用t5_corrector.py 进行batch_t5_correct，batch的比较快..

**Comment by yc930401** [comment]
加载的预训练模型是下面default里写的 Langboat/mengzi-t5-base
parser.add_argument('--model_name_or_path', type=str, default='Langboat/mengzi-t5-base', help='pretrained model')

**Comment by shibing624** [comment]
我本地测试后，输入： ”各省自治区直辖市人民政府，国院各部委各直属机构，“，输出：”各省自治区直辖市人民政府,国院各部委各直属机构,“

需要更改标点，未复现case。

如果情况需要，可自行改get_errors逻辑，适配自己训练的模型，理论上T5是能支持多字少字的错误修正的，当前get_errors逻辑局限于同长度文本修正，后续release出新的变长文本纠错模型，再做修改。
