### ISSUE TITLE
kenlm模型计算速度慢

### ISSUE THREAD

**Issue by EASTERNTIGER** [shibing624/pycorrector#292]
老师您好，我把kenlm模型封装成flask api，调用发现计算速度依然有些慢，大约100字/s的速度，500字需要5s左右，请问有什么方法可以解决吗？

**Comment by shibing624** [comment]
kenlm是有使用C语言改写加速后的库，qps在纯cpu的机器下能到2000以上。你看下本地运行耗时跟flask调用耗时，远程调用时耗时可能主要在网络传输。可以使用jina(内置grpc)替代flask搭建服务，用于提速。

**Comment by EASTERNTIGER** [comment]
> kenlm是有使用C语言改写加速后的库，qps在纯cpu的机器下能到2000以上。你看下本地运行耗时跟flask调用耗时，远程调用时耗时可能主要在网络传输。可以使用jina(内置grpc)替代flask搭建服务，用于提速。

感谢老师回复，我测试后发现由本地加载模型改为封装成flask api调用模型后，速度确实有所提升，模型加载的速度得到了改善，但是目前耗时主要集中在corrected_sent_s,detail_s=pycorrector.correct(text_content)这步的计算上，字数越多速度越慢，研读了您的源码感觉非常合理，无从下手进行自定义修改，请问还有什么方法进行调整吗？

**Comment by shibing624** [comment]
多机器，部署多服务，再负载均衡。

**Comment by EASTERNTIGER** [comment]
> 多机器，部署多服务，再负载均衡。

好的，谢谢您。
