### ISSUE TITLE
macbert模型中，检测网络的预测输出与训练输出不一致

### ISSUE THREAD

**Issue by tianyunzqs** [shibing624/pycorrector#294]
```
# 检错概率
prob = self.detection(bert_outputs.hidden_states[-1])

if text_labels is None:
    # 检错输出，纠错输出
    outputs = (prob, bert_outputs.logits)
else:
    det_loss_fct = FocalLoss(num_labels=None, activation_type='sigmoid')
    # pad部分不计算损失
    active_loss = encoded_text['attention_mask'].view(-1, prob.shape[1]) == 1
    active_probs = prob.view(-1, prob.shape[1])[active_loss]
    active_labels = det_labels[active_loss]
    det_loss = det_loss_fct(active_probs, active_labels.float())
    # 检错loss，纠错loss，检错输出，纠错输出
    outputs = (det_loss,
               bert_outputs.loss,
               self.sigmoid(prob).squeeze(-1),
               bert_outputs.logits)
```  

预测输出的时候，直接输出`prob`，而训练的时候，输出是加了sigmoid，既然输出是每个位置的出错的概率，那么是不是应该加上sigmoid呢

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/softmaskedbert4csc.py#L35 detection是有sigmoid的。

**Comment by tianyunzqs** [comment]
> https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/softmaskedbert4csc.py#L35 detection是有sigmoid的。

softmaskedbert 模型没有问题，macbert模型的detection网络没有sigmoid，不知道是不是我的理解有误，不对之处望大佬指点

**Comment by shibing624** [comment]
macbert训练时有用sigmoid输出概率值，https://github.com/shibing624/pycorrector/blob/099695a1b46d4110ccf9b44161ddd12529b05049/pycorrector/macbert/macbert4csc.py#L48，预测时不需要。

**Comment by shibing624** [comment]
可以加，拿概率值
