### ISSUE TITLE
运行t5_corrector.py时报错OSError: Unable to load weights from pytorch checkpoint file

### ISSUE THREAD

**Issue by Amber921463001** [shibing624/pycorrector#296]
运行t5_corrector.py时出现如下报错：
OSError: Unable to load weights from pytorch checkpoint file for '/home/user/.cache/huggingface/transformers/5ee27a3da3470d37aa20fd15bdf85b1c0c9cc822a6b1342770c6fdce79d8605e.5b747c4bb8a118ce814305e2a1403c3a889bbd52b047e5f7236875ca25cbda60' at '/home/user/.cache/huggingface/transformers/5ee27a3da3470d37aa20fd15bdf85b1c0c9cc822a6b1342770c6fdce79d8605e.5b747c4bb8a118ce814305e2a1403c3a889bbd52b047e5f7236875ca25cbda60'. If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

请问该如何解决？

**Comment by shibing624** [comment]
删除/home/user/.cache/huggingface/transformers/5ee27a3da3470d37aa20fd15bdf85b1c0c9cc822a6b1342770c6fdce79d8605e.5b747c4bb8a118ce814305e2a1403c3a889bbd52b047e5f7236875ca25cbda60，重新下载。
