### ISSUE TITLE
请问pycorror中t5模型在微调时是怎么训练的？

### ISSUE THREAD

**Issue by yuzhang112** [shibing624/pycorrector#300]
是用bert那样的训练任务，还是像传统的seq2seq模型根据encoder的输出，decoder从左往右预测的？

**Comment by shibing624** [comment]
看下T5 的paper。

**Comment by lsx0930** [comment]
@shibing624 麻烦问下 t5 10w数据 max_seq=128 batch=32 v100 数据量为10w，单个epoch 10分钟就训练完了？是不是有点问题？感谢
