### ISSUE TITLE
Macbert train时pytorch_lightning报错：ModelCheckpoint(monitor='val_loss') not found in the returned metrics: ['train_loss_step'].

### ISSUE THREAD

**Issue by Joyce-Ng** [shibing624/pycorrector#303]
请问训练时报错这个错是什么问题呢，网上没有相关的解决方案：pytorch_lightning.utilities.exceptions.MisconfigurationException: ModelCheckpoint(monitor='val_loss') not found in the returned metrics: ['train_loss_step'].

**Comment by shibing624** [comment]
训练参考： https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/README.md

lighting指定版本：

pip install pytorch-lightning==1.1.2

**Comment by Haibarayu** [comment]
> 训练参考： https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/README.md
> 
> lighting指定版本：
> 
> pip install pytorch-lightning==1.1.2

您好，我的 pytorch-lightning 是安装的 1.1.2 版本，仍然出现了这个报错，torch 版本是 1.9.0+cu111。同时我也遇到了https://github.com/shibing624/pycorrector/issues/273 这个报错

**Comment by shibing624** [comment]
我本地环境测试通过。
```
pytorch-lightning                  1.4.9
torch                              1.9.1
transformers                       4.12.0
yacs                               0.1.8
```

**Comment by Haibarayu** [comment]
> 我本地环境测试通过。
> 
> ```
> pytorch-lightning                  1.4.9
> torch                              1.9.1
> transformers                       4.12.0
> yacs                               0.1.8
> ```

感谢回复，运行成功了。
```
pytorch-lightning                  1.4.9
torch                              1.9.0+cu111
torchmetrics                       0.6.0
```

**Comment by Joyce-Ng** [comment]
> 我本地环境测试通过。
> 
> ```
> pytorch-lightning                  1.4.9
> torch                              1.9.1
> transformers                       4.12.0
> yacs                               0.1.8
> ```

十分感谢，果然是版本的问题，在sighan_2015数据上已经能够训练了，不过在自己构造的训练集上跑完几十个step后报错：ValueError: Expected input batch_size (3200) to match target batch_size (3264)，数据格式和的json格式一样，不知道这个问题出在哪里

**Comment by Joyce-Ng** [comment]
> 我本地环境测试通过。
> 
> ```
> pytorch-lightning                  1.4.9
> torch                              1.9.1
> transformers                       4.12.0
> yacs                               0.1.8
> ```

十分感谢，果然是版本问题，已经跑起来了！
