### ISSUE TITLE
执行错误  同#119

### ISSUE THREAD

**Issue by winniechiou** [shibing624/pycorrector#305]
### Describe the Question
我的錯誤與#119相同，
Exception: URL fetch failure on https://deepspeech.bj.bcebos.com/zh_lm/zh_giga.no_cna_cmn.prune01244.klm : None -- [Errno 104] Connection reset by peer

### Describe your attempts
參考文中的解法，但shift+cmd+.後並沒有顯示出.pycorrector 文件夾（如下圖），想請問如何解決呢？謝謝！

<img width="756" alt="截圖 2022-08-09 下午5 31 20" src="https://user-images.githubusercontent.com/45808477/183615472-9e5228d4-2e87-42f0-b88d-9cea73685ca5.png">

pycorrector.__version__ 0.4.6

**Comment by shibing624** [comment]
home目录下的
