### ISSUE TITLE
关于用convseq2seq训练nlpcc语法错误语料，loss值一直在5左右，该怎么调节参数呢？

### ISSUE THREAD

**Issue by roses0203** [shibing624/pycorrector#309]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
lr 调大10倍，batch size double
