### ISSUE TITLE
误杀case:这纸=>这只

### ISSUE THREAD

**Issue by wangyingshuai** [shibing624/pycorrector#32]
楼主，您好！今天新遇到一个badcase是：
第一次运行结果如下：
【这纸厚度如何？质量怎么样	('这只厚度如何？质量怎么样', [['这纸', '这只', 1, 2]])】
然后我把“这纸”加入到word_freq字典中
第二次运行结果如下：
【这纸厚度如何？质量怎么样	('这只厚度如何？质量怎么样', [['纸', '只', 1, 2]])】
然后我把“纸”加入到word_freq字典中
第三次运行结果如下：
这纸厚度如何？质量怎么样	('这只厚度如何？质量怎么样', [['纸', '只', 1, 2]])

综上所述，这个badcase看来是通过加入word_freq解决不了的，请问楼主，有没有解决这个badcase的好方法？

**Comment by shibing624** [comment]
临时解决方法：在自定义混淆集my_confusion.txt中，如下添加

这纸    这纸    1

执行use_costom_confusion.py

**Comment by wangyingshuai** [comment]
是的，楼主，我实验了您说的临时方法，确实可以解决，但是我觉得所有的badcase都可以通过这种加入用户自定义混淆集的方式解决，这其实没有从根本上解决问题。希望您稍后能给出更通用更有价值的解决算法。

**Comment by shibing624** [comment]
更新了支持关闭字错误检测功能，可以使用 examples/enable_char_error_detect.py 。 具体对某些单字的误杀，主要原因是由于语言模型训练数据不足导致的，可以自己重新训练语言模型解决这类问题。
