### ISSUE TITLE
常识性错误如何解决？

### ISSUE THREAD

**Issue by starflag** [shibing624/pycorrector#322]
例如：我到了湖北省长沙市。（湖南长沙）
           湖北、湖南、长沙等省份的天气良好。（长沙不算省份）
这种错误，除了构建混淆集之外还有什么方法解决？
若暂时只能通过构建混淆集来解决，则该如何构建，只能穷举这些常识性错误？

**Comment by shibing624** [comment]
常识性错误的纠错我理解是很难的，可以借鉴知识图谱之类的做，或者用NLP大模型，能懂所谓的常识才行。
