### ISSUE TITLE
为什么训练测试完成后会有一个tmp_end.ckpt文件

### ISSUE THREAD

**Issue by lq-blackcat** [shibing624/pycorrector#324]
[epoch=04-val_loss=0.02.ckpt.md](https://github.com/shibing624/pycorrector/files/9615149/epoch.04-val_loss.0.02.ckpt.md)
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
保留的全部参数的权重文件。

**Comment by lq-blackcat** [comment]
tmp_end.ckptw文件为什么会比之前保存的ckpt文件小，好像不能够加载测试？

**Comment by shibing624** [comment]
ckpt是pytorch lighting的方法加载的，readme有写。

**Comment by lq-blackcat** [comment]
我知道ckpt文件是pytorch lighting的方法加载的，我想知道的是这两个文件有什么区别
<img width="389" alt="1663900381462" src="https://user-images.githubusercontent.com/89464019/191882240-df7088a7-273a-4aa8-9137-bea35f46bc16.png">

**Comment by shibing624** [comment]
:) 这不是临时文件么

**Comment by lq-blackcat** [comment]
感谢！！！
