### ISSUE TITLE
请问Macbert支持不等长的输入输出吗？

### ISSUE THREAD

**Issue by yc930401** [shibing624/pycorrector#329]
如题，想训练输入输出可以不等长的模型，不知道Macbert可以做到吗？

**Comment by shibing624** [comment]
Macbert不支持，T5和seq2seq模型支持。

**Comment by paipaipaidaxing** [comment]
您好，请教一个问题：这些纠错方案中，只有T5和seq2seq支持输入输出不等长的情况吗？
