### ISSUE TITLE
macbert模型如何使用自定义混淆集？

### ISSUE THREAD

**Issue by arashrun** [shibing624/pycorrector#331]
### Describe the Question
看介绍混淆集功能在`correct`方法中生效，我用的是macbert模型。没有这个correct方法。是不是无法在非kenlm模型上使用自定义混淆集

**Comment by shibing624** [comment]
当前是。后续把混淆集作为一个pipeline，其他方法也可以使用。

**Comment by hongge778** [comment]
> 

好兄弟，macbert没有自定义混淆集你是怎么解决的

**Comment by arashrun** [comment]
好兄弟，我直接放弃了

**Comment by shibing624** [comment]
补充了自定义混淆集pipeline功能：https://github.com/shibing624/pycorrector/commit/f43900c6c1faf69f77be1607fa186db18d5d81fd#diff-70511165e8ea601550ab0f6d107738f9114dad770cd7bdcc4968c5acf5f58893

demo见：https://github.com/shibing624/pycorrector/blob/master/examples/use_custom_confusion.py 和macbert加混淆集：https://github.com/shibing624/pycorrector/blob/master/examples/macbert_demo.py
