### ISSUE TITLE
MacBert模型训练如何调整阈值

### ISSUE THREAD

**Issue by EASTERNTIGER** [shibing624/pycorrector#333]
您好，我在使用自己标注的数据集添加到csc数据集中进行MacBert模型训练时，会出现数据集中包含纠错内容但是训练过后MacBert模型依然无法进行纠正的问题。目前打算进行阈值调整的尝试，请问具体该怎么进行阈值调整卡阈值呢。

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/macbert_corrector.py#L58 threshold

**Comment by EASTERNTIGER** [comment]
> https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/macbert_corrector.py#L58 threshold

收到，谢谢。

**Comment by EASTERNTIGER** [comment]
老师您好，我看到了您设置的阈值，但是我发现项目代码和使用pip install pycorrector调用的代码不一致，pycorrector包的macbert_corrector.py中macbert_correct()没有threshold这个参数，我直接将macbert_correct整个方法替换掉运行时，有的字符串没问题，有的会显示decode_tokens_old = self.tokenizer.decode(inputs['input_ids'][idx], skip_special_tokens=True).split(' ')这行报错——IndexError: index 128 is out of bounds for dimension 0 with size 2，请问这是什么原因造成的呢？
