### ISSUE TITLE
macbert微调时报错

### ISSUE THREAD

**Issue by orangeecc** [shibing624/pycorrector#334]
### Describe the bug
macbert微调时报错，使用自己处理的数据集，是在训练到若干个mini_batch时报错的。
错误如下：
  return torch._C._nn.cross_entropy_loss(input, target, weight, _Reduction.get_enum(reduction), ignore_index, label_smoothing)
ValueError: Expected input batch_size (544) to match target batch_size (512).

维度之差为设定的batch_size=32

**Comment by orangeecc** [comment]
解决了！当训练数据里有am等英文时，bert分词会切成一个token，导致input和taget的长度不匹配

**Comment by shibing624** [comment]
嗯，自有数据集需要处理下长度匹配问题。
