### ISSUE TITLE
我使用seq2seq训练了一版纠错模型我想降低下误杀率，请问有什么好方法啊？

### ISSUE THREAD

**Issue by xuhongtian** [shibing624/pycorrector#336]
### Describe the Question
Please provide a clear and concise description of what the question is.
我训练参数目前embed_size：128，hidden_size：256，dropout：0.12.我是还可以需要调试model_agrs脚本内参数来降低误杀率吗？目前误杀率为43%，模型纠错准确率为87%。
### Describe your attempts
- [x] I walked through the tutorials
- [ ] I checked the documentation
- [x] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.
pycorrect版本为当前master最新版本

**Comment by shibing624** [comment]
1、可以抛些badcase看下吗？
2、训练集有校对过吗？
3、可以使用macbert或者t5训练比对下模型
