### ISSUE TITLE
您好，mengzi-t5-base-chinese-correction使用问题

### ISSUE THREAD

**Issue by swx-10** [shibing624/pycorrector#338]
### Describe the Question
您好，我使用mengzi-t5-base-chinese-correction模型的时候，预测的结果感觉和没用训练过的模型是一样的，和hugging face上测试的完全不一样，请问是怎么回事？
pycorrector版本是 0.4.6
![1668138517692](https://user-images.githubusercontent.com/81468192/201259332-95ac8011-9791-4852-b4b2-23b504f22faf.jpg)

**Comment by shibing624** [comment]
你不应该print(res)吗？

**Comment by swx-10** [comment]
额，我想着，是一样的😂。res的结果如下
![image](https://user-images.githubusercontent.com/81468192/201295473-c31fb366-1ebe-410e-8f54-19aa164568df.png)

**Comment by shibing624** [comment]
```
    def __init__(self, model_dir=config.t5_model_dir):
        self.name = 't5_corrector'
        bin_path = os.path.join(model_dir, 'pytorch_model.bin')
        if not os.path.exists(bin_path):
            model_dir = "shibing624/mengzi-t5-base-chinese-correction"
            logger.warning(f'local model {bin_path} not exists, use default HF model {model_dir}')
```
训练后模型下面的模型文件名是`pytorch_model.bin'`，才能找到。否则用下载的模型。

**Comment by swx-10** [comment]
我是在hugging face上下的模型文件，名字也是pytorch_model.bin
![image](https://user-images.githubusercontent.com/81468192/201334229-89e06ab2-c4ab-4247-9a78-895e35fe5731.png)

**Comment by peter65374** [comment]
先用example目录下的T5 demo试一下吧，我试了可用。

**Comment by swx-10** [comment]
> 先用example目录下的T5 demo试一下吧，我试了可用。

我用的就是example目录下的T5 demo里的代码

**Comment by ViewWholeWorld** [comment]
> 

你是不是用的那个 copyt5_corrector.py? 我用这个也是同样的问题, 但是用 t5_corrector.py 就是正常的, 两份代码在初始化 tokennizer 的地方用的不一样。

**Comment by shibing624** [comment]
那我顺便把`copyt5_corrector.py`删了，我调研这个copyt5的效果不如原生t5的，也没必要存在了，易混淆。
