### ISSUE TITLE
误杀case列举

### ISSUE THREAD

**Issue by wangyingshuai** [shibing624/pycorrector#34]
楼主，您好！用您最新的模型跑了一些测试数据，部分badcase列举如下：
（1）这个跟 原木纯品   那个啥区别？不是原木纸浆做的？ | 这个跟 原木唇品 那个啥区别？不是原木纸浆做的？' | [" [['纯品'", " '唇品'", '   6', ' 8]]']
（2）能充几次呢？ | '能重几次呢？' | [" [['能充'", " '能重'", ' 0', ' 2]]']
（3）这是酸奶还是像饮料一样的奶？ | '这时酸奶还是像饮料一样的奶？' | [" [['这是'", " '这时'", ' 0', ' 2]]']
（4）现在银色的K2P是MTK还是博通啊？ | '现在银色的K2P是MTK还是拨通啊？' | [" [['博通'", " '拨通'", ' 14', ' 16]]']
（5）是浓稠的还是稀薄的？ | '是浓周的还是稀薄的？' | [" [['浓稠'", " '浓周'", ' 1', ' 3]]']
（6）这个到底有多辣？ | '这个到底有多拉？' | [" [['有多辣'", " '有多拉'", ' 4', ' 7]]']
（7）U盘有送挂绳吗 | 'U盘又送挂绳吗' | [" [['盘有'", " '盘又'", ' 1', ' 3]]']
（8）果子酸吗？有烂的吗？ | '果子酸吗？有蓝的吗？' | [" [['有烂'", " '有蓝'", ' 5', ' 7]]']
（9）刚下单买了一箱，需要明天到货，先问下味道如何😄 | '刚下单买了一箱，需要明天到货，现问下味道如何😄' | [" [['先问'", " '现问'", ' 15', ' 17]]']
（10）2周岁22斤宝宝用多大的啊？ | '2周岁22斤宝宝用多达的啊？' | [" [['用多大'", " '用多达'", ' 8', ' 11]]']
（11）请问这茶是一条装的吗 | '请问这差是一条装的吗' | [" [['这茶'", " '这差'", ' 2', ' 4]]']
（12）有坏的果吗 | '有怀的果吗' | [" [['有坏'", " '有怀'", ' 0', ' 2]]']
（13）生产日期怎么样 新嘛 | '生产日期怎么样 心嘛' | [" [['新嘛'", " '心嘛'", ' 8', ' 10]]']
（14）插上去的时候是驱蚊液放下面的吗？ | '插上去的时候是驱蚊以放下面的吗？' | [" [['液放'", " '以放'", ' 9', ' 11]]']
（15）橄榄的和这款哪个比较好用？味道都是一样的么？ | '橄榄的和这款哪个比较好永？味道都是一样的么？' | [" [['好用'", " '好永'", ' 10', ' 12]]']

**Comment by shibing624** [comment]
感谢提供，后续会跟进。

**Comment by wangyingshuai** [comment]
感谢楼主，期待早日看到优化后的版本！

**Comment by zhangxiangchn** [comment]
对于误杀的案例（我目前使用的是基于规则的纠错模型），是不是最有效的方法就是添加纠错词库的方法。我目前的应用场景主要是在一些垂直领域。

**Comment by shibing624** [comment]
是。

**Comment by shibing624** [comment]
bert模型的误杀会少很多。
