### ISSUE TITLE
macbert怎么在作者训练好的模型pytorch_model.bin的基础上继续训练

### ISSUE THREAD

**Issue by hongge778** [shibing624/pycorrector#341]
自己从头训练的模型效果不佳，想请问一下如何在作者给出的已经训练好的模型的基础上继续训练

**Comment by hongge778** [comment]
已经弄好了，十分感谢

**Comment by wnntju** [comment]
> 预训练模型从hfl/macbert 改为 shibing624/macbert4csc-base-chinese 就行。
请问从头训练的话使用hfl/chinese-macbert-base还是hfl/macbert。我做的中文asr文本纠错
