### ISSUE TITLE
macbert训练时报错 TypeError: batch_text_or_text_pairs has to be a list (got <class 'tuple'>)

### ISSUE THREAD

**Issue by ChingKwanCheung** [shibing624/pycorrector#342]
macbert训练时报错：raise TypeError(f"batch_text_or_text_pairs has to be a list (got {type(batch_text_or_text_pairs)})")
TypeError: batch_text_or_text_pairs has to be a list (got <class 'tuple'>)

我安装的版本：
torch 1.9.1
transformers 4.12.0
pytorch-lightning 1.4.9
yacs 0.1.8

请问是什么原因呢？

**Comment by ChingKwanCheung** [comment]
把train.py中的：
tokenizer = BertTokenizerFast.from_pretrained(cfg.MODEL.BERT_CKPT)
改成：
tokenizer = BertTokenizer.from_pretrained(cfg.MODEL.BERT_CKPT)
就能跑起来了

**Comment by shibing624** [comment]
可以改为BertTokenizer，区别不大，我这边BertTokenizerFast也能正常训练，安装版本是：
```
pytorch-lightning                  1.5.1
transformers                       4.20.1
```

**Comment by forevercc0303** [comment]
我这训练的时候也报错 
python3 preprocess.py
Traceback (most recent call last):
File "preprocess.py", line 201, in
main()
File "preprocess.py", line 188, in main
test_lst = proc_test_set(sighan15_dir)
File "preprocess.py", line 101, in proc_test_set
with open(os.path.join(fp, 'SIGHAN15_CSC_TestInput.txt'), 'r', encoding='utf-8') as f:
File "/usr/local/lib/python3.7/codecs.py", line 904, in open
file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/pycorrector/macbert/../data/cn/sighan_2015/SIGHAN15_CSC_TestInput.txt'

python3 train.py
Traceback (most recent call last):
File "train.py", line 131, in
main()
File "train.py", line 55, in main
cfg = args_parse()
File "train.py", line 38, in args_parse
cfg.merge_from_file(config_file)
File "/usr/local/lib/python3.7/site-packages/yacs/config.py", line 211, in merge_from_file
with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'train_macbert4csc.yml'
