### ISSUE TITLE
尝试去训练数据集 执行py脚本报错，说缺少文件

### ISSUE THREAD

**Issue by forevercc0303** [shibing624/pycorrector#347]
python3 preprocess.py
Traceback (most recent call last):
File "preprocess.py", line 201, in
main()
File "preprocess.py", line 188, in main
test_lst = proc_test_set(sighan15_dir)
File "preprocess.py", line 101, in proc_test_set
with open(os.path.join(fp, 'SIGHAN15_CSC_TestInput.txt'), 'r', encoding='utf-8') as f:
File "/usr/local/lib/python3.7/codecs.py", line 904, in open
file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/pycorrector/macbert/../data/cn/sighan_2015/SIGHAN15_CSC_TestInput.txt'

python3 train.py
Traceback (most recent call last):
File "train.py", line 131, in
main()
File "train.py", line 55, in main
cfg = args_parse()
File "train.py", line 38, in args_parse
cfg.merge_from_file(config_file)
File "/usr/local/lib/python3.7/site-packages/yacs/config.py", line 211, in merge_from_file
with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'train_macbert4csc.yml'

**Comment by shibing624** [comment]
本地执行不用安装库，pip uninstall pycorrector

**Comment by forevercc0303** [comment]
> 
执行了pip uninstall pycorrector 后 macbert 文件中只有两个目录 ：output和__pycache__ ，没有训练文件了呀？

**Comment by forevercc0303** [comment]
我是在linux服务器执行的

**Comment by forevercc0303** [comment]
我找到了缺失的train_macbert4csc.yml文件并执行训练完成，请问训练完后是直接用快速加载的pycorrector调用就可以看到训练的效果吗？

**Comment by shibing624** [comment]
是

**Comment by forevercc0303** [comment]
您好 我想请问一下，output中存放三个文件：dev.json,test.json,train.json。分别都是有什么用处呢？ 我想训练自己的数据语言的话是在三个文件都加入还是只用加入其中一个文件中。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shibing624/pycorrector"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月30日(星期三) 晚上7:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shibing624/pycorrector] 尝试去训练数据集 执行py脚本报错，说缺少文件 (Issue #347)





 
是

**Comment by forevercc0303** [comment]
我按照格式添加了下面的数据
`{
        "id": "Y2-1297-3",
        "original_text": "海上声明月，天涯共此石。",
        "wrong_ids": [
            2,
            10
        ],
        "correct_text": "海上生明月，天涯共此时。"
    }`
训练完成后，调用pycorrector出来的结果为
`('。海上有明月，天涯共此人', [('海', '。', 0, 1), ('上', '海', 1, 2), ('声', '上', 2, 3), ('明', '有', 3, 4), ('月', '明', 4, 5), ('，', '月', 5, 6), ('天', '，', 6, 7), ('涯', '天', 7, 8), ('共', '涯', 8, 9), ('此', '共', 9, 10), ('石', '此', 10, 11), ('。', '人', 11, 12)])`
调用自己训练的语句出来的结果前面都有个句号或者是逗号，这是怎么回事？

**Comment by forevercc0303** [comment]
调用方法为
`from pycorrector.macbert.macbert_corrector import MacBertCorrector
nlp = MacBertCorrector("shibing624/macbert4csc-base-chinese").macbert_correct
print(nlp('海上声明月，天涯共此石。'))`

**Comment by forevercc0303** [comment]
调用方法为
`from pycorrector.macbert.macbert_corrector import MacBertCorrector`
`nlp = MacBertCorrector("shibing624/macbert4csc-base-chinese").macbert_correct`
`print(nlp('海上声明月，天涯共此石'))`

**Comment by forevercc0303** [comment]
调用方法为
from pycorrector.macbert.macbert_corrector import MacBertCorrector
nlp = MacBertCorrector("shibing624/macbert4csc-base-chinese").macbert_correct
print(nlp('海上声明月，天涯共此石。'))

**Comment by forevercc0303** [comment]
您好，有看到的话 可以麻烦回复一下吗

**Comment by shibing624** [comment]
多训练10个epoch看下，针对单个badcase，看不出模型的问题。
