### ISSUE TITLE
关于word_freq在detector与corrector中同时使用的问题

### ISSUE THREAD

**Issue by FeelCoolOne** [shibing624/pycorrector#349]
### Describe the bug
基于规则的纠错方法中，Detector与Corrector使用的是同一个word_freq，导致在Corrector当中对于无效候选词过滤几近失去效果。

### Detail
由于文本中错误的出现，在对文本进行分词是必然会产生很零碎的分词结果，例如，‘我爱北京天俺门’，分词后的结果为‘我/爱/北京/天/俺/门’。 错误词语片段无法构成独立的词语，‘天/俺/门’，当corrector中输入word为'俺'时，通过混淆构建的候选结果，需要通过known()函数对无效结果进行初步过滤，但‘俺‘相关的‘安’由于并不是一个完整的词，可能并没有在word_freq中，word_freq中只有‘天安门'。因此会导致此处的word_freq失去应有的效果。

### Suggestion
建议使用unigram/bigram/trigram的方法对word_freq进行重构，重构后得到的结果替换corrector中的word_freq来进行无效候选词过滤。

**Comment by shibing624** [comment]
confusion_dict的混淆集词典会动态修改word_freq，`天俺门`也能使用混淆集纠正过来。
