### ISSUE TITLE
T5只能训练一轮，怎么设置训练多个epoch呢？

### ISSUE THREAD

**Issue by szj2ys** [shibing624/pycorrector#352]
- [ + ] I checked to make sure that this is not a duplicate issue
- [ + ] I'm submitting the request to the correct repository (for model requests, see [here](https://github.com/shibing624/pycorrector))

### Additional Information
Other things you want the developers to know.

T5只能训练一轮，设置epochs参数也不起作用，请问目前T5支持设置训练多个epoch吗，如果支持怎么设置训练多个epoch呢？如果不支持请问有添加多轮训练的计划吗，谢谢。

**Comment by shibing624** [comment]
改大max_steps就是

**Comment by shibing624** [comment]
已经更新了，默认只用num_epochs,如果设置了max_steps才会生效max_steps参数。https://github.com/shibing624/pycorrector/commit/072eb18d64bf66102bc836005910667efa57e768
