### ISSUE TITLE
训练多字少字的情况,json格式怎么写

### ISSUE THREAD

**Issue by jangjun21** [shibing624/pycorrector#354]
{
"id": "-",
"wrong_ids": [
1,
2
],
"original_text": "年检话",
"correct_text": "年检电话"
}， {
"id": "-",
"wrong_ids": [
0,
1
],
"original_text": "念粘检电话",
"correct_text": "年检电话"
},
我想训练多字少字的情况,这个wrong_ids是不是一定要填，怎么填，有没有这种情况的example

**Comment by shibing624** [comment]
用T5训练，tsv格式的，不用wrong_ids

**Comment by jangjun21** [comment]
我训练多字少字的情况，"original_text": "年检话",
"correct_text": "年检电话"来训练，在使用t5_corrector.py来测试发现没有被纠错还是“年检话”，不知道是什么原因，语料一共20000条，其中多字少字的站15%左右

**Comment by shibing624** [comment]
具体case需要具体分析，模型是概率预测，并不保证每个case都能处理到。如果需要强制替换，可以用混淆集规则来处理。

**Comment by jangjun21** [comment]
好像是以original_text的最大长度来对齐的，如果correct_text大于original_text长度，纠正的长度还是original_text的长度，比如上面的"年检话"只纠正为"年检电"，“话"好像被戒掉了，其他的这种情况也类似,你是否有遇到这个情况

**Comment by shibing624** [comment]
会，macbert只处理对齐文本纠错，多字少字的情况模型结构不支持。
