### ISSUE TITLE
macbert预训练和微调超参数设置

### ISSUE THREAD

**Issue by wnntju** [shibing624/pycorrector#356]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by wnntju** [comment]
是否可以提供下训练的训练和微调的参数，是用默认的就可以吗？还有请问是多卡训练吗？

**Comment by shibing624** [comment]
模型的就是建议值

**Comment by jangjun21** [comment]
微调是冻结了哪些层呢,好像训练的参数,没有冻结的设置？所有的参数会全部更新吗

**Comment by shibing624** [comment]
没冻结
