### ISSUE TITLE
T5模型设置纠错概率

### ISSUE THREAD

**Issue by jangjun21** [shibing624/pycorrector#357]
1T5是概率纠错,是否有地方设置阈值,只有大于这个阈值的纠错,否则不纠错
2能否返回一个纠错概率,让应用层决定是否纠错

**Comment by wnntju** [comment]
> 1T5是概率纠错,是否有地方设置阈值,只有大于这个阈值的纠错,否则不纠错 2能否返回一个纠错概率,让应用层决定是否纠错

请问你用T5效果如何？我用的macbert和T5，准确率和F1都能到90%多，但是改错的比改对的多太多了。如果有纠错概率的话或许可以帮助缓解这个问题。

**Comment by shibing624** [comment]
macbert有纠错概率值，拿的softmax后的概率。T5暂没加。

**Comment by jangjun21** [comment]
如果我们想自己在T5上加概率,怎么加了,有什么思路或者步骤吗？

**Comment by shibing624** [comment]
我觉得可以拿T5模型的输出logits，做个softmax，取最大概率就是。
