### ISSUE TITLE
t5训练完之后生成的模型文件内没有 tokenizer.json

### ISSUE THREAD

**Issue by shangzhensen** [shibing624/pycorrector#361]
运行推理代码时报未找到这个文件，需要把mengzi-t5-base-chinese-correction文件内的 tokenizer.json放过去吗？
![image](https://user-images.githubusercontent.com/48047942/217135607-0c14ce2e-17f5-493f-bbf7-16339395e57b.png)

**Comment by shangzhensen** [comment]
预训练模型使用的是mengzi-t5-base-chinese-correction文件下的模型

**Comment by shangzhensen** [comment]
生成的文件只有这些，预测的时候缺少文件
![image](https://user-images.githubusercontent.com/48047942/217136778-296a5bc6-bf98-496b-8cf7-dcfc0ac26ef3.png)

**Comment by shangzhensen** [comment]
@shibing624  大佬，帮忙看一下这个问题吧

**Comment by shibing624** [comment]
你用的是best epoch的结果，需要将外层文件夹的tokenizer.json copy进去即可。
