### ISSUE TITLE
macbert后台运行信息显示

### ISSUE THREAD

**Issue by EASTERNTIGER** [shibing624/pycorrector#363]
老师您好，我在linux服务器进行macbert/train.py 后台运行时，使用如下代码：nohup python -u train.py > train.log 2>&1 &，运行后会有一行数字显示：
![image](https://user-images.githubusercontent.com/97668973/221514185-0aec7daa-f31e-4153-b50b-0c9be3e2aa85.png)
，这个数字每次都会变化，有时候是几千，有时候是几万几十万，但是今天当数字非常大，179w的时候，日志显示代码没有运行，只有一行——nohup: 忽略输入
请问这是什么原因造成的呢，换其他服务器则能正常运行代码，显示的数字也没有这么大

**Comment by shibing624** [comment]
1. `tail -f nohup.out` 查看日志输出；
2. 数字是pid进程号；
3. 查下nohup的用法，linux基础。
