### ISSUE TITLE
无法识别出文本中错误

### ISSUE THREAD

**Issue by git3210** [shibing624/pycorrector#364]
### Describe the Question
git clone 最新分支代码，用git上默认专用词文本，直接使用Corrector类方法中correct方法无法检测以下文本中错误。请问是什么原因？
1. 绿水青山就是银山金山
2. 想象难以
3. 少先队员因该给老人让座

**Comment by shibing624** [comment]
你看下readme呗？规则方法并不保证所有case都能纠错，当然深度模型也不保证。

**Comment by git3210** [comment]
这些例子都是readme中的测试用例，里面写的可以正确识别
