### ISSUE TITLE
训练自有数据集

### ISSUE THREAD

**Issue by ASLYY** [shibing624/pycorrector#365]
不太清楚怎么进行自有数据集的训练
如果使用自有数据集是替换train_macbert4csc.yml中的dataset的train.json,test.json和dev.json文件部分 然后运行train.py就可训练模型了吗 
train,test,dev的json是指定了某句话里面的错误信息，那如果想要判断一个json文件中从未出现过的句子，还能实现纠错吗？
期待得到您的回复，谢谢！

**Comment by shibing624** [comment]
模型有泛化性

**Comment by ASLYY** [comment]
谢谢您的回答！
那可以请教一下如何进行标注成模型所需要的数据格式的吗？是否有工具能够使用呢？
![image](https://user-images.githubusercontent.com/87521581/223354550-1044be0a-4ff2-4251-9cad-562d8e858207.png)

**Comment by shibing624** [comment]
我没用工具，excel标注的。你可以看看[duocan](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/uie/doccano.md) , 不过建议还是excel标，反正比较简单。

**Comment by xicunwu** [comment]
您好，才接触这类知识，也不太清楚怎么进行自有数据集的训练
在训练时是把自己的数据集补充至这三个文件中，还是进行文件替换呢？另外dev.json是什么作用呢？我看readme中还新建output文件，并把三个作者提供的文件丢进去，请问自有数据增量训练需要这一步骤吗。
嗯对，我主要是想知道增量训练步骤

**Comment by xicunwu** [comment]
十分惊喜居然能这么得到作者的回复！
我的做法是将BERT_CKPT设置为shibing624/macbert4csc-base-chinese；将DATASETS设置为我自己的数据集的路径，就可以做到在您的基础上进行我所需要的增量训练吗，这样的话，train.json里是只需要有我自己数据集，还是说之前的也需要而我的是补充至原train.json里

**Comment by xicunwu** [comment]
十分惊喜居然能这么快得到作者的回复！
我的做法是将BERT_CKPT设置为shibing624/macbert4csc-base-chinese；将DATASETS设置为我自己的数据集的路径，就可以做到在您的基础上进行我所需要的增量训练吗，这样的话，train.json里是只需要有我自己数据集，还是说之前的也需要而我的是补充至原train.json里

**Comment by xicunwu** [comment]
十分感谢作者的解答
