### ISSUE TITLE
求一份 未切词文本数据people2014_words.txt 数据 或者提取文章的pyhton脚本

### ISSUE THREAD

**Issue by mosthandsomeman** [shibing624/pycorrector#367]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
你写个脚本把切分的join起来不就是吗？

`''.join([i.split('/')[0] for i in split_sents.split()])`

**Comment by mosthandsomeman** [comment]
我看到里面join之后有些中括号，目前已经解决了。
