### ISSUE TITLE
pert模型

### ISSUE THREAD

**Issue by Godlikemandyy** [shibing624/pycorrector#368]
请问有没有可用的pert模型来测试下纠错的效果？

**Comment by shibing624** [comment]
上次跑完，效果不如macbert就没保留，在macbert文件夹下实验，把预训练模型从 `hfl/chinese-macbert-base` 改为 `hfl/chinese-pert-base` 就可以train了。

**Comment by Godlikemandyy** [comment]
好的，多谢！
pert不是针对位置错误的纠错效果比较好吗？这种整体的效果不好是吗

**Comment by shibing624** [comment]
看pert的paper显示pert对长文本的处理比较好，短文本的位置关系是很重要的，所以短文本的乱序可能会造成理解不清。

不过我是比较认可pert模型的方法的，如果用来做字词颠倒的纠错，其效果应该会好很多。

当前在SIGHAN15数据集评估pert模型效果不如macbert。

**Comment by Godlikemandyy** [comment]
可能和场景有关系，多谢了
