### ISSUE TITLE
使用pycorrector报错Cannot read model

### ISSUE THREAD

**Issue by mm0137** [shibing624/pycorrector#369]
您好，刚开始接触pycorrector，遇到了报错无法解决，请问该如何解决这个问题。
在windows系统下安装了pycorrector，在尝试使用所给代码样例运行时报错。
Cannot read model 'C:\Users\Windows/.pycorrector/datasets/zh_giga.no_cna_cmn.prune01244.klm' (util\mmap.cc:225 in util::HugeMalloc threw ErrnoException because `!to.get()'. Not enough space Failed to allocate 2953349384 bytes)
RuntimeError: util\mmap.cc:225 in util::HugeMalloc threw ErrnoException because `!to.get()'.
Not enough space Failed to allocate 2953349384 bytes
下载了官方文档中的模型替换了自动联网下载的，也检查了文件的访问权限，依然无法解决本问题。

**Comment by shibing624** [comment]
不是写了错误原因了吗？C盘存储不够，zh_giga.no_cna_cmn.prune01244.klm 模型需要3G空间，如果你电脑空间不够，可以用小模型：https://github.com/shibing624/pycorrector#%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%AD%E8%A8%80%E6%A8%A1%E5%9E%8B

**Comment by mm0137** [comment]
c盘还有90G左右，远大于所需的3G，怎么还会报错呢？我会试试小模型的。

**Comment by shibing624** [comment]
模型重新下载一次，删除 C:\Users\Windows/.pycorrector/datasets/zh_giga.no_cna_cmn.prune01244.klm，会自动重新下载

**Comment by mm0137** [comment]
<img width="415" alt="image" src="https://user-images.githubusercontent.com/126863166/222945953-c0b65bba-9708-4669-b579-0cb0f5a8939f.png">
<img width="416" alt="image" src="https://user-images.githubusercontent.com/126863166/222945961-0b8c9d64-4ca7-4b20-93dc-3177cbc27e43.png">
重新联网下载和从网页中给的链接下载都尝试过了，还是同样的报错。请问这个和电脑的运行内存大小有关系吗？

**Comment by shibing624** [comment]
和电脑的运行内存有关的，模型需要加载到内存呀。你用小模型跑下吧

**Comment by mm0137** [comment]
好的，谢谢你
