### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by shjtshtj** [shibing624/pycorrector#37]
对于提高纠错效果，在下有些拙见。近音错误往往是由于我们使用输入法的时候不小心选错了序号造成的，而实际正确的词就在旁边。但是这种错误可能比较难通过博主的拼音纠错模块进行纠错，因为拼写的时候我们往往喜欢简拼，而相同简拼的词太多了，而且输入法还附带有词语联想功能，以至于有可能那些在拼音上完全不相关的词语也弄了进去，纠错根本找不出来。所以能不能有某种方式，当我们在拼写的时候，我们能获取到输入框里的候选词，用所有的候选词去跑一遍，感觉这样效率更高，而且效果应该更好。而且这个能在打字的时候实时纠错，实用性更强，用户体验更好

**Comment by shibing624** [comment]
谢谢建议。
只是可行性有待商榷，中文输入法是一个比文本纠错更复杂的应用。
