### ISSUE TITLE
语法纠错模型

### ISSUE THREAD

**Issue by wnntju** [shibing624/pycorrector#371]
中文拼写纠错模型我试了macbert4cs效果很不错，感谢作者大大的开源。接下来想尝试下语法纠错模型，我看作者使用了seq2seq模型来做，是基于预训练模型bart。想请问下具体代码：
[textgen](https://github.com/shibing624/textgen)和pycorrector中的这套代码有什么区别嘛

**Comment by shibing624** [comment]
1. textgen是专门用于文本生成的模型，包括各种生成模型，如T5、bart、seq2seq、gpt等；
2. pycorrector是专注于纠错业务的代码库，生成模型可以用来做纠错，但纠错不仅限于用生成模型来做，还可以用bert做。

**Comment by wnntju** [comment]
> 1. textgen是专门用于文本生成的模型，包括各种生成模型，如T5、bart、seq2seq、gpt等；
> 2. pycorrector是专注于纠错业务的代码库，生成模型可以用来做纠错，但纠错不仅限于用生成模型来做，还可以用bert做。

好滴 非常感~ 我最近尝试了一些语法纠错模型，但是基于生成的语法纠错模型似乎会增加很多的删除和插入错误，替换错误反而召回率特别低。我看了一i啊，一般都是添加了一些连词，比如“和、在、根据、从、的、了 等词，这种的话肯定会降低模型的性能。但是整体上又不影响文本内容，类似这种错误是可以接受的，但是要好其他的评价指标了，作者有没有尝试其他指标去评价纠错质量。

**Comment by shibing624** [comment]
那你分错误类别评估各类别的纠错效果呗，不一起看。
