### ISSUE TITLE
macbert_correct & batch_macbert_correct差异

### ISSUE THREAD

**Issue by andy23andy7980** [shibing624/pycorrector#372]
想请问macbert_correct 和 batch_macbert_correct这两个function为何做出来的结果有差异?

纯粹是threshold影响的吗? 还是算法部分也有不同?

**Comment by shibing624** [comment]
macbert_correct 是单字处理的，后处理逻辑比batch的多一些，batch是纯模型预测结果。后处理逻辑你们可以自己写。

**Comment by andy23andy7980** [comment]
thx~
