### ISSUE TITLE
macbert结果多字疑问

### ISSUE THREAD

**Issue by andy23andy7980** [shibing624/pycorrector#373]
original sentence:诊酶证明书 => 诊断证明书明 err:[('酶', '断', 1, 2)]

以上情形是错字更改为正确字，但结尾却多一个"明"
想请问是为什么出问题的?

original sentence:病么号码 => 的什么号码码 err:[('病', '的', 0, 1), ('么', '什', 1, 2), ('号', '么', 2, 3), ('码', '号', 3, 4)]
也有这种前后都多字的情形。

因为有些结果是正确的，但因为长度跟旧输入不一样(多字)被舍弃，因此想询问一下是什么问题

**Comment by shibing624** [comment]
使用 correct 方法看下。

我的demo里面示例结果：
```
"text": "诊酶证明书",
["items"](https://www.mulanai.com/product/corrector/): [
"('酶', '断', 1, 2)"
],
"corrected_text": "诊断证明书"
```

**Comment by andy23andy7980** [comment]
作者老师好

我是使用自己训练的模型，您的原模型似乎没有这问题，
使用macbert_correct得出的
decode_tokens_new会是['诊', '断', '证', '明', '书', '明']
因此与原句'诊酶证明书'长度不一样

训练模型是使用bert-base-chinese 
资料集是SIGHAN+Wang271K中文纠错数据集

感谢回覆

**Comment by shibing624** [comment]
有几个可能的原因：1.训练集混入了标点，多预测了字；
2.纠错场景，bert效果不如macbert；
3.等长字词替换下，可以截取输入长度的字符：`output = output_str[:input_len]`

**Comment by andy23andy7980** [comment]
感谢作者老师回覆
