### ISSUE TITLE
macbert训练后如何转化为onnx模型呢

### ISSUE THREAD

**Issue by lazywangyuan** [shibing624/pycorrector#374]
if ckpt_path and os.path.exists(ckpt_path):
        model.load_state_dict(torch.load(ckpt_path)['state_dict'])
        # 先保存原始transformer bert model
        tokenizer.save_pretrained(cfg.OUTPUT_DIR)
        bert = BertForMaskedLM.from_pretrained(cfg.MODEL.BERT_CKPT)
        bert.save_pretrained(cfg.OUTPUT_DIR)
        state_dict = torch.load(ckpt_path)['state_dict']
        new_state_dict = OrderedDict()
        if cfg.MODEL.NAME in ['macbert4csc']:
            for k, v in state_dict.items():
                if k.startswith('bert.'):
                    new_state_dict[k[5:]] = v
        else:
            new_state_dict = state_dict
        # 再保存finetune训练后的模型文件，替换原始的pytorch_model.bin
        torch.save(new_state_dict, os.path.join(cfg.OUTPUT_DIR, 'pytorch_model.bin'))

**Comment by shibing624** [comment]
还没做，稍后我补充下。

**Comment by Yazooliu** [comment]
> 还没做，稍后我补充下。

Could I update code and PR to support this exchange model to onnx format ? thanks.

**Comment by shibing624** [comment]
可以

**Comment by Yazooliu** [comment]
> 可以

Thanks. I will update it as soon as possible

**Comment by ChenchenJT** [comment]
你好，想问一下这个issue实现了吗，在项目没找到相应的代码或者PR

**Comment by shibing624** [comment]
后续我不添加该功能，官方教程就可以转换为onnx。
