### ISSUE TITLE
batch_size 报错

### ISSUE THREAD

**Issue by andy23andy7980** [shibing624/pycorrector#375]
想请问老师，加入自己资料集训练会跳这个错误

ValueError: Expected input batch_size (1568) to match target batch_size (1504).

batch_size我是设32，是我有哪边没调好吗

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/issues/350

**Comment by andy23andy7980** [comment]
感谢作者神速支援

**Comment by andy23andy7980** [comment]
想再请教作者，
有办法找出是哪个资料的问题吗?
目前确定我的资料是字串长度一致、没有英文大小写字母
不过仍然报错

**Comment by shibing624** [comment]
自己写脚本遍历一遍就知道了。
```
for line in sys.stdin:
    terms = line.split('\t')
    if len(terms[0])!=len(terms[1])
        print('error', line)
```

**Comment by andy23andy7980** [comment]
作者好，
目前确定是字符串都是等长的，
想请教资料集是否还有其他规则会造成这种状况。
再次感谢作者

**Comment by shibing624** [comment]
1. 检查是否空字符，剔除空的；
2. 用示例训练集跑下，没问题加10条自己的数据再跑；
3. 都没问题再加自己全部数据集。

**Comment by andy23andy7980** [comment]
作者好，
第一步第二步都没问题，
自己的资料集全加下去就报错了...

**Comment by andy23andy7980** [comment]
想请教有没有可能是因为一些标点符号进去会导致长度不一样?
是否只能留"，" "。"等中文标点符号?

**Comment by andy23andy7980** [comment]
解决了!
我只留下"，" "。" "、"等标点符号后就没问题了
再次谢谢作者多次帮我解决问题
