### ISSUE TITLE
1

### ISSUE THREAD

**Issue by 2kkkkk** [shibing624/pycorrector#378]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by 2kkkkk** [comment]
i=nlp('今天你好')
print(i)
<<<('', [])

**Comment by 2kkkkk** [comment]
发现是在自有训练集训练完之后，出现的这种情况。如果用nlp = MacBertCorrector("/home/hisense/macbert4csc-base-chinese").macbert_correct，就不会出现。

**Comment by 2kkkkk** [comment]
发现是在自有数据集训练完之后的模型，预测时出现的这种情况。如果直接用shibing624/macbert4csc-base-chinese就不会出现这种情况

**Comment by shibing624** [comment]
训练没拟合？样本集太少吗

**Comment by 2kkkkk** [comment]
> 训练没拟合？样本集太少吗

训练集是4000条数据，我的训练集里包含了大量的无错误数据，正负样本比例大概是1：9，也就是大部分的样本的wrong_ids是[]，这个会有影响吗？

**Comment by shibing624** [comment]
会影响，训练集里设置全是带错误数据就行。

**Comment by 2kkkkk** [comment]
感谢解答，您的开源项目对我帮助很大
