### ISSUE TITLE
module 'pycorrector' has no attribute 'correct'

### ISSUE THREAD

**Issue by zzybj** [shibing624/pycorrector#379]
pip安转完最新版本0.4.8，使用时，报一下错误，可否看下什么原因？
AttributeError: module 'pycorrector' has no attribute 'correct'
测试代码：
import pycorrector
corrected_sent, detail = pycorrector.correct('少先队员因该为老人让坐')
print(corrected_sent, detail)

**Comment by shibing624** [comment]
不至于吧，这个版本发布半年了。

**Comment by shibing624** [comment]
pip install pycorrector -U

**Comment by ttxs001** [comment]
你好，使用pip install pycorrector -U的时候会报如下错误，但我已经通过pip install pypi-kenlm
pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pypi-kenlm下载了kenlm，能否看一下怎么解决
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kenlm
Failed to build kenlm
ERROR: Could not build wheels for kenlm, which is required to install pyproject.toml-based projects

**Comment by shibing624** [comment]
pip install kenlm -U

**Comment by ttxs001** [comment]
> pip install kenlm -U
还是存在相同问题，在安装了网上查的各种前置条件之后仍然是报错 ERROR: Failed building wheel for kenlm
Failed to build kenlm
ERROR: Could not build wheels for kenlm, which is required to install pyproject.toml-based projects，麻烦看一下

**Comment by shibing624** [comment]
1.用linux安装
2.环境搞不定的，用docker测试并实验。
