### ISSUE TITLE
请问作者先生，如何在训练完模型之后对macbert和seq2seq进行测试正确率，召回率，新手小白求教

### ISSUE THREAD

**Issue by 031902518** [shibing624/pycorrector#383]
请问作者先生，如何在训练完模型之后对macbert和seq2seq进行测试正确率，召回率，新手小白求教

**Comment by shibing624** [comment]
用eval 函数算acc,recall, F1： https://github.com/shibing624/pycorrector/blob/master/pycorrector/utils/eval.py#L254

**Comment by 031902518** [comment]
![image](https://user-images.githubusercontent.com/90022064/232232233-fb3fc8c7-327e-463c-be22-950ad722419a.png)
请问先生，我运行eval时候出现了这个错误

**Comment by 031902518** [comment]
那么请问seq2seq的如何测试呀

**Comment by shibing624** [comment]
一样的。严格按句子纠正后是否一致计算。
