### ISSUE TITLE
报错信息“ Binary file has size 21086208 but the headers say it should be at least 2953349384)”

### ISSUE THREAD

**Issue by Gaia-Wu** [shibing624/pycorrector#389]
在此之前是可以成功运行的
![截屏2023-05-09 09 39 14](https://user-images.githubusercontent.com/94101986/236972429-669a0653-1f4f-4ea4-bd94-953aaf6e09c0.png)
我重新下载了文件还是不行
请问有解决办法吗

**Comment by Gaia-Wu** [comment]
貌似是因为我使用的本地模型路径没有生效？
![截屏2023-05-09 10 54 28](https://user-images.githubusercontent.com/94101986/236982116-9e01d9ef-dc63-4c27-9cd3-b07459d0e512.png)
运行的时候却出现：
![截屏2023-05-09 10 54 58](https://user-images.githubusercontent.com/94101986/236982193-0d9c5714-e8b3-4962-9d8b-e86e620848a3.png)
提问：
模型路径一定需要放在‘～/.pycorrector/datasets/’下才可以嘛？

**Comment by Yazooliu** [comment]
源码里面应该可以追踪到路径配置信息

**Comment by Yazooliu** [comment]
> 貌似是因为我使用的本地模型路径没有生效？ ![截屏2023-05-09 10 54 28](https://user-images.githubusercontent.com/94101986/236982116-9e01d9ef-dc63-4c27-9cd3-b07459d0e512.png) 运行的时候却出现： ![截屏2023-05-09 10 54 58](https://user-images.githubusercontent.com/94101986/236982193-0d9c5714-e8b3-4962-9d8b-e86e620848a3.png) 提问： 模型路径一定需要放在‘～/.pycorrector/datasets/’下才可以嘛？


源码里面写的是这个：
![image](https://user-images.githubusercontent.com/39296687/236985990-627970e8-3ce0-4aed-bb8f-2ca4aca28b1f.png)

**Comment by Yazooliu** [comment]
> 貌似是因为我使用的本地模型路径没有生效？ ![截屏2023-05-09 10 54 28](https://user-images.githubusercontent.com/94101986/236982116-9e01d9ef-dc63-4c27-9cd3-b07459d0e512.png) 运行的时候却出现： ![截屏2023-05-09 10 54 58](https://user-images.githubusercontent.com/94101986/236982193-0d9c5714-e8b3-4962-9d8b-e86e620848a3.png) 提问： 模型路径一定需要放在‘～/.pycorrector/datasets/’下才可以嘛？

代码里看是的
# -----用户目录，存储模型文件-----
USER_DATA_DIR = os.path.expanduser('~/.pycorrector/datasets/')
os.makedirs(USER_DATA_DIR, exist_ok=True)
language_model_path = os.path.join(USER_DATA_DIR, 'zh_giga.no_cna_cmn.prune01244.klm')

**Comment by shibing624** [comment]
updated. 可以用
```
import os
os.environ["PYCORRECTOR_DATA_DIR"] = "/your_new_path/"

```
改变默认的模型路径 `~/.pycorrector/datasets/` 为 `/your_new_path/`
