### ISSUE TITLE
关于seq2seq_attention的问题

### ISSUE THREAD

**Issue by Hxiaodou** [shibing624/pycorrector#39]
您好，我使用您的代码和语料进行训练，但是我训练完进行测试的结果特别差，并不能和你截图的效果一样，想问一下除了按照您的使用说明上的要求，还有什么步骤吗
![2018-11-19 09-12-23](https://user-images.githubusercontent.com/23566676/48681128-7fd79480-ebdb-11e8-9da9-f9063b167421.png)

**Comment by igorhuangchao** [comment]
一样的问题， 估计是模型本身不够好，作者的结果也贴了， 都不太理想
