### ISSUE TITLE
利用softmaskedbert4csc预测为空的问题

### ISSUE THREAD

**Issue by koalasix-sky** [shibing624/pycorrector#392]
### Describe the Question
您好，我利用train_softmaskedbert4csc.yml配置文件对模型进行训练，在预测时利用utils/eval.py进行预测（路径已对应），但是在预测结果中大多数预测都为空，利用macbert时未出现此类情况，进行debug时发现利用训练的softmasked模型输出基本都为错，代码中预测使用的argmax函数，想请问下是不是不可以直接用utils/eval.py进行预测，目前有可以直接进行推理的脚本吗？或者是其他问题造成了softmasked模型预测为空的问题呢？
期待您的回复！

**Comment by shibing624** [comment]
1. 嗯，不可以直接用utils/eval.py进行预测
2. 用https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/infer.py 预测
