### ISSUE TITLE
可能存在一些包冲突，版本不对应的问题

### ISSUE THREAD

**Issue by Hzzhang-nlp** [shibing624/pycorrector#393]
![image](https://github.com/shibing624/pycorrector/assets/39661319/00256ebf-99fc-4e6d-abe1-b0b34738b565)

**Comment by Hzzhang-nlp** [comment]
希望可以帮忙解决的大佬，给个回复

**Comment by shibing624** [comment]
pip install yaml

**Comment by Hzzhang-nlp** [comment]
![image](https://github.com/shibing624/pycorrector/assets/39661319/08ec7543-c7f7-43e9-8561-057810c00d7f)

**Comment by Hzzhang-nlp** [comment]
这种很简单的问题我还是会的！
![image](https://github.com/shibing624/pycorrector/assets/39661319/433731ba-d30d-4d93-b5d2-f0450eec8037)

**Comment by Hzzhang-nlp** [comment]
> pip install yaml

![image](https://github.com/shibing624/pycorrector/assets/39661319/4bfcb590-2827-4a8b-a307-f02a90cd14e5)

**Comment by shibing624** [comment]
pip3 install pyyaml

**Comment by shibing624** [comment]
你百度都不愿意。。。

**Comment by Hzzhang-nlp** [comment]
> 你百度都不愿意。。。

是多个包不匹配的问题，我想是不是用一步更新就全部解决了，而不是一个个包的安装

**Comment by Hzzhang-nlp** [comment]
![image](https://github.com/shibing624/pycorrector/assets/39661319/f37abee1-87e1-4354-af0b-ba1ce59418ee)
