### ISSUE TITLE
cpu如何并行预测

### ISSUE THREAD

**Issue by seetimee** [shibing624/pycorrector#394]
### Describe the Question
Please provide a clear and concise description of what the question is.
我服务器安装了paddle版的ernie_corrector,CPU版本的,但是进行预测时cpu只占25%,有没有哪个参数是可以使用全部cpu进行预测的呢?
### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

You may also provide a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) you tried as a workaround, or StackOverflow solution that you have walked through. (e.g. cosmic radiation).

In addition, figure out your version by running `import pycorrector; pycorrector.__version__`.

**Comment by shibing624** [comment]
开多进程呢

**Comment by seetimee** [comment]
> 开多进程呢

请问单篇文章怎么加速呢?

**Comment by shibing624** [comment]
默认是512切分为短句处理的，加速技巧我不知道。 macbert模型用一般的gpu就可以相对于cpu提速10倍以上。

**Comment by seetimee** [comment]
> 默认是512切分为短句处理的，加速技巧我不知道。 macbert模型用一般的gpu就可以相对于cpu提速10倍以上。

好的,感谢
