### ISSUE TITLE
使用Docker和直接使用源码效果不一样

### ISSUE THREAD

**Issue by lizhiqingli** [shibing624/pycorrector#395]
直接使用docker run -it -v ~/.pycorrector:/root/.pycorrector shibing624/pycorrector:0.0.2　所的到的效果与下载源码所的到的效果不一致，模型文件都是使用2.8的那个默认文件。
Docker中的：
![image](https://github.com/shibing624/pycorrector/assets/5219494/73a76c66-44c9-4942-992a-7b256b2a919f)
自己部署的：
![image](https://github.com/shibing624/pycorrector/assets/5219494/0d9419bf-1900-413b-942c-bd6e27253428)

**Comment by shibing624** [comment]
fixed了，是专名词表带来的错误。https://github.com/shibing624/pycorrector/commit/9069caac06401b83f8009e36aa5e5d52acc1f68a

**Comment by lizhiqingli** [comment]
感谢大师，从新pull一下代码
