### ISSUE TITLE
重复字或词删除

### ISSUE THREAD

**Issue by wanghai345** [shibing624/pycorrector#403]
### Describe the Question
Please provide a clear and concise description of what the question is.
https://github.com/shibing624/pycorrector/tree/master/pycorrector/t5  这个模型可以处理重复字或者词删除纠正吗。
就是前后文本字数不一样的情况。

**Comment by shibing624** [comment]
是

**Comment by lancorrect** [comment]
请问release到huggingface上的shibing624/mengzi-t5-base-chinese-correction是不是不能处理重复字或者词的删除纠正？我测试下来对于重复字的语句不会有任何改动。
例如，"夏夏夏天到了"的结果依然是“夏夏夏天到了”

**Comment by wanghai345** [comment]
没有用相关的训练数据来训练，结果应该是这样的。

**Comment by lancorrect** [comment]
> 没有用相关的训练数据来训练，结果应该是这样的。

好的感谢回复
