### ISSUE TITLE
是否可以进行药品领域纠错和模型更换

### ISSUE THREAD

**Issue by us-ydd** [shibing624/pycorrector#404]
1.当进行药品名称领域的纠错时，是否可以将BERT_CKPT: "hfl/chinese-macbert-base"设置为“9pinus/macbert-base-chinese-medicine-recognition”?
2.如果不可以，是否需要修改一部分代码，具体可以修改哪部分？

**Comment by shibing624** [comment]
第三方模型，我没测评过，可以自行测试。
