### ISSUE TITLE
字形错误检测与纠错

### ISSUE THREAD

**Issue by tianyongliu** [shibing624/pycorrector#405]
搜索了源码，好像只有一个文件有关于字形检测方面的内容。没看到这个类具体用在哪里，希望解答下？
实际场景是，我想要召回形近字引起的错误，具体点就是由于五笔输入或者笔画输入带来的错误，但是代码中没有看到这块具体是如何体现的，谢谢！

**Comment by shibing624** [comment]
detect里面

**Comment by tianyongliu** [comment]
谢谢，看到了。非常感谢分享。
