### ISSUE TITLE
标点符号的纠错

### ISSUE THREAD

**Issue by aaronliu7** [shibing624/pycorrector#406]
支持对标点符号进行纠错吗？

**Comment by shibing624** [comment]
支持，方法一样，改下训练集就可以。

**Comment by aaronliu7** [comment]
感谢回复，请问如果要同时支持文字和标点符号的纠错应该怎么做？是需要将文字纠错和标点符合纠错的数据集联合训练吗？

**Comment by shibing624** [comment]
是

**Comment by shibing624** [comment]
https://huggingface.co/raynardj/classical-chinese-punctuation-guwen-biaodian
