### ISSUE TITLE
confusion_correct func 逻辑有问题？

### ISSUE THREAD

**Issue by josh-zhang** [shibing624/pycorrector#407]
[pycorrector](https://github.com/shibing624/pycorrector/tree/0.4.8)/[pycorrector](https://github.com/shibing624/pycorrector/tree/0.4.8/pycorrector)/confusion_corrector.py

line 59: text_new = text[:idx] + truth + text[(idx + len(err)):]

是不是应该是 text_new = text_new[:idx] + truth + text_new[(idx + len(err)):]    ？

**Comment by shibing624** [comment]
没问题。
