### ISSUE TITLE
./util/pool.hh:4:10: fatal error: 'cassert' file not found

### ISSUE THREAD

**Issue by heppytt** [shibing624/pycorrector#41]
你好 我按照依赖包的时候 报这个错误 请问是怎么回事啊？
在安装pip install kenlm==0.0.0的时候，我的系统是mac系统。
@./util/pool.hh:4:10: fatal error: 'cassert' file not found

**Comment by qubo** [comment]
我在kenlm下安装python setup.py install 也有同样报错
./util/pool.hh:4:10: fatal error: 'cassert' file not found

**Comment by qubo** [comment]
我在kenlm下安装python setup.py install 也有同样报错
./util/pool.hh:4:10: fatal error: 'cassert' file not found

**Comment by shibing624** [comment]
这错误提示太少，我看不懂呀。。。你装kenlm出错，还是装啥出错的？
