### ISSUE TITLE
将多个短句子合并在一起之后使用macbert4csc就无法识别到错别字了，是什么原因呢？

### ISSUE THREAD

**Issue by helloHKTK** [shibing624/pycorrector#410]
将多个短句子合并在一起之后使用macbert4csc就无法识别到错别字了：
["真麻烦你了。希望你们好好的跳无。少先队员因该为老人让坐。机七学习是人工智能领遇最能体现智能的一个分知。"]
而单条句子却可以识别出来：
["真麻烦你了。希望你们好好的跳无",
"少先队员因该为老人让坐"，
"机七学习是人工智能领遇最能体现智能的一个分知"]

**Comment by shibing624** [comment]
模型训练时用的短句训练的，具体可以查看训练集。预测时一般用标点符号切分为短句

**Comment by helloHKTK** [comment]
您好：    很高兴收到您的来信，我会尽快阅读并回复您！祝您工作顺利、生活愉快！

**Comment by helloHKTK** [comment]
您好：    很高兴收到您的来信，我会尽快阅读并回复您！祝您工作顺利、生活愉快！
