### ISSUE TITLE
怎么训练多语种模型？简繁体中文日文韩文英文等

### ISSUE THREAD

**Issue by nissansz** [shibing624/pycorrector#418]
怎么训练多语种模型？简繁体中文日文韩文英文等

**Comment by shibing624** [comment]
加多语种的训练集即可，tokenzier处理时注意下，可能需要分别处理。

**Comment by shibing624** [comment]
可以，但不建议。你可以选个原生多语言的base model，在其上做多语言支持。

**Comment by ILG2021** [comment]
> 可以，但不建议。你可以选个原生多语言的base model，在其上做多语言支持。

谢谢了，我用mt5训练了。但我有个顾虑是，如果句子没有语法错误，会不会出问题？因为mt5模型预训练也会产出结果吧。这跟语法纠错器的预期不太一致。

**Comment by shibing624** [comment]
没错的就是负例，原句输出
