### ISSUE TITLE
纠正OCR误识别的结果

### ISSUE THREAD

**Issue by lwppwl** [shibing624/pycorrector#419]
作者你好，请问一下，pycorrector库能否对OCR的误识别的字进行纠错呢，比如0和O,B和8这种，哪种模型效果会比较好呢？谢谢。

**Comment by shibing624** [comment]
本库是从语言模型角度做文本纠错的，理论上可以处理数字和字母，但一般这种错误是长尾的，默认是关闭数字 字母纠错。

**Comment by xunhang1007** [comment]
作者你好，请问如何开启数字、字母纠错？

**Comment by shibing624** [comment]
1.数据纠错不支持；
2.字母纠错，可以调用enspell开启英文字母纠错。见：

https://github.com/shibing624/pycorrector?tab=readme-ov-file#%E8%8B%B1%E6%96%87%E6%8B%BC%E5%86%99%E7%BA%A0%E9%94%99
