### ISSUE TITLE
关于detector.py文件中的问题

### ISSUE THREAD

**Issue by maozezhong** [shibing624/pycorrector#42]
您好，两个问题请教一下：
1） 关于detecor.py这个文件有个问题，在第282行开始，我理解的逻辑是结合2-gram和3-gram两个模型的评分，那么不应该是分别导入两个模型吗？但是在kenlm/文件夹下只有一个模型，即您这边只导入了一种模型做了两种情况的操作？
2） kenlm文件夹下的模型是基于charater切分后的文件训练的吗？n-gram中的n取的是几呢？

**Comment by shibing624** [comment]
1）一个3元模型。
2）3

**Comment by maozezhong** [comment]
多谢回复！
所以对于给定的n，一个训练好的n-gram模型可以用来评测1到n的长度的字表对吗？

**Comment by shibing624** [comment]
是的。
