### ISSUE TITLE
get_errors方法对于漏词的情况无法检测

### ISSUE THREAD

**Issue by jinxiqinghuan** [shibing624/pycorrector#422]
例如：
输入模型会错误的把“振聋发聩”修改成“振聋发”，但是get_error方法，会输出没有错误。
**振聋发聩  =>  振聋发 []**
![image](https://github.com/shibing624/pycorrector/assets/44440158/4ead66f6-51bc-4b80-b1d5-5ecc505fdada)

**Comment by shibing624** [comment]
聩 需要添加到unk words

**Comment by jinxiqinghuan** [comment]
感谢！实测问题已解决，请问这个unk words是什么原因导致的呀，数据集中没有见过就会不识别吗？谢谢！

**Comment by shibing624** [comment]
遇到unk words，pass

**Comment by jinxiqinghuan** [comment]
好的，谢谢！
