### ISSUE TITLE
使用大词库时，proper correct的效率特别低

### ISSUE THREAD

**Issue by jinxiqinghuan** [shibing624/pycorrector#423]
为了获得更好的结果，在项目中使用了十万级的大词库，
但是在实际使用中，大词库会导致纠错速度特别特别慢。
请问大佬，这个问题是否有解决方案？
或者有什么其他更好的思路吗？
谢谢！

**Comment by shibing624** [comment]
1. 加前缀树匹配；
2. 加redis缓存机制，遇到过的直接读缓存结果；
3. 总结常遇到的错误，用confusion dict替代proper correct。

**Comment by jinxiqinghuan** [comment]
谢谢大佬！
