### ISSUE TITLE
bart纠错耗时问题

### ISSUE THREAD

**Issue by EASTERNTIGER** [shibing624/pycorrector#425]
老师您好，我试着用了下bart做纠错，发现有时候模型运行很快，有时候很慢，同一条相同内容的新闻耗时可能都会有变化，而且如果一条文本中如果夹杂了大量的html标签，有时候耗时正常，有时候会非常慢，用时极其不稳定，请问这是什么原因造成的呢？

**Comment by EASTERNTIGER** [comment]
还有就是bart模型会比macbert在处理同样的内容时耗时慢非常多，请问这有什么解决的策略呢？

**Comment by shibing624** [comment]
耗时长短跟输入长度有关。
