### ISSUE TITLE
请问Pycorrector默认使用的纠错模型是哪个

### ISSUE THREAD

**Issue by yeless** [shibing624/pycorrector#426]
`import pycorrector`
`corrected_sent, detail = pycorrector.correct('少先队员因该为老人让坐')`

请问Pycorrector默认使用的纠错模型是哪个，翻了下代码好像是用Kenlm加载了一个模型，但是具体没看出来是加载的哪个。

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/blob/master/pycorrector/config.py#L14
