### ISSUE TITLE
macbert微调保存模型结构的问题

### ISSUE THREAD

**Issue by evanchenhi** [shibing624/pycorrector#427]
我看pycorrector/macbert/train_macbert4csc.yml配置文件里BERT_CKPT是原始 hfl/chinese-macbert-base 模型

微调完保存的也是原始模型，链接如下，并没有保存MacBert4Csc模型结构，只保存了权重参数
`bert = BertForMaskedLM.from_pretrained(cfg.MODEL.BERT_CKPT)`
`bert.save_pretrained(cfg.OUTPUT_DIR)`
[https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/train.py#L114](https://github.com/shibing624/pycorrector/blob/master/pycorrector/macbert/train.py#L115)

不知道我看的是否正确

**Comment by shibing624** [comment]
嗯
