### ISSUE TITLE
如何不纠错人名

### ISSUE THREAD

**Issue by lucasjinreal** [shibing624/pycorrector#436]
人名千奇百怪，有时候本来人名不用管的，会被错误的纠正，如何规避这个问题。想过分词但是分词本身也不准。

**Comment by Qian-z** [comment]
我用的百度的LAC命名实体识别过滤的，效果还可以

**Comment by xhw205** [comment]
> 我用的百度的LAC命名实体识别过滤的，效果还可以

MACBERT这直接给纠错了，怎么防止误纠？

**Comment by shibing624** [comment]
自定义混淆集`ConfusionCorrector`类，除了上面演示的和`Corrector`类一起使用，还可以和`MacBertCorrector`一起使用，也可以独立使用。示例代码 [examples/macbert/model_correction_pipeline_demo.py](https://github.com/shibing624/pycorrector/blob/master/examples/macbert/model_correction_pipeline_demo.py)
