### ISSUE TITLE
漏词、多词的wrong_ids的设置逻辑问题

### ISSUE THREAD

**Issue by jinxiqinghuan** [shibing624/pycorrector#437]
您好，在训练漏词和多词时，数据集的wrong_ids应该怎样设置比较合理呢。例如：
原句：早上，有一个小狗跑过来。
病句：早，有一个小狗跑过来。

错误的id应该是：
[1,2,3,4,5,6,7,8,9,10,11]
还是：
[1]

这两种设置是否会影响T5的训练呢？谢谢您！

**Comment by shibing624** [comment]
T5的训练集不需要wrong_ids

**Comment by jinxiqinghuan** [comment]
谢谢大佬
