### ISSUE TITLE
环境问题

### ISSUE THREAD

**Issue by tianyongliu** [shibing624/pycorrector#439]
### Describe the Question
想请问下该环境的基本信息，我目前是：
python:3.8
transformers:4.4.2

但是测试gpt模型的时候遇到这个问题：
ImportError: cannot import name 'LlamaForCausalLM' from 'transformers' (unknown location)

所以想问下基础环境应该怎么样比较好：
python:  ?
transformers: ?
torch:   ?

谢谢！

**Comment by shibing624** [comment]
transformers升级。

**Comment by tianyongliu** [comment]
谢谢啦！
