### ISSUE TITLE
被MacBERT误纠错的名词，如何添加到白名单，防止下次继续出错？

### ISSUE THREAD

**Issue by xhw205** [shibing624/pycorrector#443]
kenlm可以将误纠错的名词强制放入混淆字典，Macbert呢？

**Comment by shibing624** [comment]
macbert 也能加混淆词典功能。

**Comment by tianyongliu** [comment]
Macbert 确实也有错纠，这时候需要一个白名单。请问有相关demo提供下吗？

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector?tab=readme-ov-file#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%B7%B7%E6%B7%86%E9%9B%86 可以做到加白。

**Comment by tianyongliu** [comment]
感谢回复，上面给出的例子好像是Kenlm模型的加白。我想用macbert模型，但是也需要加白。

另外一个问题：
text = ['表决结果：11票同意、0票弃权、0票反对。', '表决结果：11 票同意、0 票弃权、0 票反对']
text = ['证券简称：中成股份证券代码：000151公告编号：2024-34本公司及董事会全体成员保证信息披露内容的真实、准确、完整，没有虚假记载、误导性陈述或者重大遗漏', '中成进出口股份有限公司', '第九届董事会第十一次会议决议公告', '中成进出口股份有限公司（以下简称“公司”）董事会于2024 年 7 月 8 日以书面及电子邮件形式发出公司第九届董事会第十一次会议通知，公司于 2024 年 7 月 11 日以现场会议和通讯表决相结合的方式在公司会议室召开第九届董事会第十一次会议', '本次会议应到董事 11 名，实到董事 11 名，会议的召开符合《公司法》等有关法律、行政法规和《公司章程》的规定', '董事长张朋先生主持了本次董事会会议，会议采用举手', '表决方式，由主持人计票并宣布表决结果', '列席本次董事会会议的有公司监事及高级管理人员', '本次董事会会议审议并表决了如下议案：', '一、关于审议《公司控股股东中国成套设备进出口集团有限公司延长股权激励承诺履约时限》的议案', '表决结果：6票同意、0票弃权、0票反对', '关联董事张朋、韩宏、张晖、王晓菲、罗鸿达对本议案回避表决', '本议案尚需提交公司二〇二四年第一次临时股东大会审议', '本议案已经独立董事专门会议审议通过', '具体内容详见', '同日在《中国证券报》《证券日报》《证券时报》及巨潮资讯网（www.cninfo.com.cn）发布的《关于公司控股股东中国成套设备进出口集团有限公司延长股权激励承诺履约时限的公告》', '二、关于审议《公司向中信银行、民生银行申请综合授信》的议案', '表决结果：11 票同意、0 票弃权、0 票反对', '为满足公司经营发展需要，保障公司业务顺利开展，同', '意公司向中信银行申请 3 亿元人民币综合授信额度，期限为一年，业务品种为流动资金贷款、银行承兑汇票、国内信用证及项下融资，国内无追索权保理融资、非融资性保函、国际保理、国际贸易进口融资、国际贸易出口融资等', '向民生银行申请 2.5 亿元人民币综合授信额度，期限为一年，业务品种为流动资金贷款、银行承兑汇票、国内无追索权保理融资、非融资性保函等']

这里有两个数组，使用macbert模型预测第一个数组时，结果没有问题，预测第二个数组时，第一个数组的第二个文本(也在第二个数组中)，会得到这样的结果，即使过滤掉空格也有问题：
 {'errors': [('票', '对', 20), ('对', '意', 22)],
  'source': '表决结果：11 票同意、0 票弃权、0 票反对',
  'target': '表决结果：11 票同意、0 票权0、0 对。意。'},

 {'errors': [('弃', '票', 13)],
  'source': '表决结果：11票同意、0票弃权、0票反对',
  'target': '表决结果：11票同意、0票票权、0票反对对'},

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/blob/master/examples/macbert/model_correction_pipeline_demo.py 混淆集加白是个独立的功能模块，各模型都能调用。

**Comment by tianyongliu** [comment]
收到，谢谢大佬！！！
