### ISSUE TITLE
Pycrorrector支持语义级别的错误检测吗？

### ISSUE THREAD

**Issue by suchstar** [shibing624/pycorrector#446]
最近在搞一个项目，需要针对行业内容做中文错误检测并给出提示，因为是特定行业场景，所以会有一些语义上的错误检测识别：比如“中国的首都南京”——>"中国的首都北京"这种检测功能。

以上不知道Pycorrectro是否支持？期待回复，感谢。

**Comment by shibing624** [comment]
可以。
