### ISSUE TITLE
使用GPT，如何保证对人名不纠错

### ISSUE THREAD

**Issue by suchstar** [shibing624/pycorrector#449]
### Describe the Question
Please provide a clear and concise description of what the question is.
![2023-12-06_154519](https://github.com/shibing624/pycorrector/assets/128674457/1c1d645d-362e-483d-918a-b21ced172b37)
使用gpt方式对中文纠错，发现过程中针对名人的名字也检查出了错误，并给出了建议，针对此类场景，gpt有啥办法做到针对人名不检查吗？
[text.txt](https://github.com/shibing624/pycorrector/files/13578034/text.txt)

检测输入为：附件text.txt
检测配置为：按照中文标点拆句

**Comment by shibing624** [comment]
加前置过滤，人名NER识别的过滤。不传入纠错。
