### ISSUE TITLE
知识型纠错有什么好的方向

### ISSUE THREAD

**Issue by 1215thebqtic** [shibing624/pycorrector#451]
你好，

比如说我有一个知识库，比如说“A说了XXX”。我现在写了“B说了XXX”，但根据知识库是A说的，所以要把B改成A。

这种知识型的纠错，有什么比较成熟的解决方案吗？谢谢！

**Comment by shibing624** [comment]
GPT类比较合适，这种属于改写润色，不是传统意义的拼写纠错了。
