### ISSUE TITLE
基于语言模型错误检测过程中平均绝对离差计算疑问

### ISSUE THREAD

**Issue by dazhaxie0526** [shibing624/pycorrector#452]
在基于语言模型进行错误检测过程中，使用平均绝对离差方式进行识别，y_score = ratio * margin_median / med_abs_deviation 这个的作用是什么？ration这个参数代表什么意思？谢谢！

<img width="889" alt="image" src="https://github.com/shibing624/pycorrector/assets/5484115/f54bc26e-8549-4e8f-90d8-94a26f868e14">

**Comment by shibing624** [comment]
看下MAD就知道了
