### ISSUE TITLE
发现GPT模型和MacBERT模型检错结果各有优势，情问下如何选择

### ISSUE THREAD

**Issue by suchstar** [shibing624/pycorrector#453]
[错别字库.xlsx](https://github.com/shibing624/pycorrector/files/13622519/default.xlsx)
![GPT](https://github.com/shibing624/pycorrector/assets/128674457/9c2e4f75-c024-44b2-8ad4-d5f5ca41d2df)
![MacBERT](https://github.com/shibing624/pycorrector/assets/128674457/1b564123-ed82-4cf9-87eb-1d3cd8e7384a)
本次验证发现，针对附件的错别字库进行检错验证，我们发现GPT模型要比MacBERT模型好很多。
之前验证发现，针对一相对正确的文章进行检错验证，我们发现MacBERT模型要比GPT模型好很多。

正确文件的检错结果参见：
https://github.com/shibing624/pycorrector/issues/450

以上就带给我一个迷惑的感觉，所以本次想咨询：
（1）不知道什么场景使用GPT模型，什么场景使用MacBERT模型？
（2）我们理解两种模型场景下，都支持我们再次训练这些模型的，对吧？这块的训练方法有啥注意的吗？

**Comment by shibing624** [comment]
1. 理论上GPT模型比macbert能力更强；
2. 构造训练数据，加入实际纠错数据，数据清洗很重要，质量比数据重要。
