### ISSUE TITLE
关于Pycorrector纠错模型的选取问题咨询

### ISSUE THREAD

**Issue by suchstar** [shibing624/pycorrector#454]
感谢老大的一直以来的快速响应，我们最近针对pycorrector做了很多的验证，总体感觉都还行，也了解到后期可以通过继续训练模型的方式进一步提高检错成功率。

本次想再次咨询老大：在Pycorector推荐的四种模型（T5，ERNIE_CSC，MacBERT，GPT）方案中，我们该选取哪一种，我们当前想优先采用MacBert，因为测试验证下来，它的效率高，识别准确性也相对还行。但是其他模型比如GPT也识别出来了MacBERT未识别的错误。

我们的产品的使用场景是：（1）客户发布一篇文章前的检错。（2）客户自己故意写错一段话进行检错。

期待老大指导一下方向：是优先选择MacBERT还是几种模型配合起来使用？

![模型推荐](https://github.com/shibing624/pycorrector/assets/128674457/1ee79541-7b48-461c-8d77-556850c692e9)

**Comment by shibing624** [comment]
可以用gpt，选一个最优的base模型，如qwen-72b  https://huggingface.co/Qwen/Qwen-72B-Chat ，再训练下。

**Comment by suchstar** [comment]
好的，我们先这条路走走，谢谢
