### ISSUE TITLE
您好，示例测试，高心 纠错为 高新，不是该高兴吗？ 请问是我哪里没有配对吗？

### ISSUE THREAD

**Issue by cloudAndMonkey** [shibing624/pycorrector#455]
<img width="1436" alt="image" src="https://github.com/shibing624/pycorrector/assets/12228225/4cff17a0-07b0-4f07-93bb-6c56811b4352">

demo.py执行也是一样
<img width="1232" alt="image" src="https://github.com/shibing624/pycorrector/assets/12228225/520444e1-fdf0-4594-8bb4-b4dfa16f0eea">

**Comment by shibing624** [comment]
识别错误，算badcase。
