### ISSUE TITLE
fine-tune没效果，是不是哪里设置不对

### ISSUE THREAD

**Issue by shuxiangguo** [shibing624/pycorrector#458]
谢谢大大的工作。我测试时发现有几句话没有纠错，
![image](https://github.com/shibing624/pycorrector/assets/19200688/18ff45ea-658b-4b5d-ae23-5b539e862b08)
所以我将这几句话加入到train.json里，
![image](https://github.com/shibing624/pycorrector/assets/19200688/3d881cba-3e30-43db-8772-69621173c275)
无论是重新训练还是fine-tune，训练了100个epoch，重新测试发现还是无法纠错，请问是什么原因呢，是数据量太少了吗？

**Comment by shuxiangguo** [comment]
MacBERT模型

**Comment by DataXujing** [comment]
我也遇到这个问题了。

**Comment by shibing624** [comment]
```
def correct_batch(
            self,
            sentences: List[str],
            max_length: int = 128,
            batch_size: int = 32,
            threshold: float = 0.7,
            silent: bool = True
    ):
```

这里threshold改为0.5或者更低。

**Comment by DataXujing** [comment]
我发现predict.py与predict_ckpt.py返回的纠错结果是不同的，相同模型，阈值下，oredict_ckpt.py的推断结果才是正确的

**Comment by shibing624** [comment]
predict_ckpt.py是用原始权重预测的，predict是convert to hf的权重预测的。

**Comment by nevermorez** [comment]
> predict_ckpt.py是用原始权重预测的，predict是convert to hf的权重预测的。

作者大大，经过测试，我这边也发现了原始权重预测和转换为hf权重预测结果大规模不一致，原始权重表现出了匹配训练结果的性能，转换为hf后效果如同未训练之前，训练数据在hf模型上验证都完全不起作用，请问这是因为转换为hf权重的过程中哪里出现问题了吗？还请作者在百忙之中可以看一下，感激不尽！

**Comment by shibing624** [comment]
updated

**Comment by shibing624** [comment]
https://github.com/shibing624/pycorrector/commit/9fe431b52c87157300eb60e282f1ecbf44826385

**Comment by shibing624** [comment]
threshold改为0.1
