### ISSUE TITLE
pip安装时报错 Could not build wheels for kenlm

### ISSUE THREAD

**Issue by 385628424** [shibing624/pycorrector#460]
安装时报错：
      cl: 命令行 warning D9002 :忽略未知选项“-std=c++11”
      read_compressed.cc
      util\read_compressed.cc(16): fatal error C1083: 无法打开包括文件: “zlib.h”: No such file or directory
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Preview\\VC\\Tools\\MSVC\\14.37.32820\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for kenlm
Failed to build kenlm
ERROR: Could not build wheels for kenlm, which is required to install pyproject.toml-based projects

[notice] A new release of pip is available: 23.2.1 -> 23.3.2
[notice] To update, run: python.exe -m pip install --upgrade pip

**Comment by shibing624** [comment]
pip install kenlm, use linux.

**Comment by 385628424** [comment]
用的是windows

**Comment by shibing624** [comment]
> 用的是windows

换linux，不支持win，没测试过win
