### ISSUE TITLE
chatglm3-6b-csc-chinese-lora

### ISSUE THREAD

**Issue by Guozonghai** [shibing624/pycorrector#464]
### Describe the Question
可以把模型chatglm3-6b-csc-chinese-lora放到魔塔社区吗？huggingface无法下载

**Comment by shibing624** [comment]
https://hf-mirror.com/shibing624/chatglm3-6b-csc-chinese-lora   下载方法：https://hf-mirror.com

**Comment by Guozonghai** [comment]
下载还是困难
![Uploading af3934642c1f6466c2ec9cd0d810d28c_680699.png…]()
