### ISSUE TITLE
通过接口调用correct_batch  纠错结果不对

### ISSUE THREAD

**Issue by Guozonghai** [shibing624/pycorrector#467]
<img width="503" alt="912d755dc13bbe2837a2320f177fdcd" src="https://github.com/shibing624/pycorrector/assets/9956235/e75bc9cc-48b5-450d-8adf-4ddcb299a12a">
<img width="1113" alt="c905712752d2cbabbe6906a015a351d" src="https://github.com/shibing624/pycorrector/assets/9956235/e78c8b5a-a6cb-417c-8c87-187ce7aa6a11">

通过接口调用correct_batch 这个方法，遇到回答结果不对，并且每次请求的时候模型输入非常慢，请问这是什么原因导致的？

**Comment by shibing624** [comment]
gpt是大模型，本来就慢；取决于机器，用A100。

**Comment by Guozonghai** [comment]
我用的就是A100  调用接口返回结果也不对   直接执行demo.py没问题
