### ISSUE TITLE
有一点点小疑惑，same_pinyin.txt第一个字符有的出现两次

### ISSUE THREAD

**Issue by yongzhuo** [shibing624/pycorrector#468]
### Describe the Question
Please provide a clear and concise description of what the question is.
有一点点小疑惑，same_pinyin.txt第一个字符有的出现两次，去重后只有3401个（默认有3513个），这个算正常吗

![image](https://github.com/shibing624/pycorrector/assets/31341349/92a150cb-b420-424c-89e6-c1a0b590dbf0)
![image](https://github.com/shibing624/pycorrector/assets/31341349/8982a633-dd03-44a8-b829-7090d384a41d)

**Comment by shibing624** [comment]
dict, 会自动去重。不用管。
