### ISSUE TITLE
MacBERT-CSC的tokenzier编码可能会导致不等长

### ISSUE THREAD

**Issue by yongzhuo** [shibing624/pycorrector#469]
### Describe the Question
Please provide a clear and concise description of what the question is.
图书信息作\u3000者：张丽珊出版社：天津人民出版社ISBN：978-7-201-08411-4出版时间：2014-01-02定\u3000价：￥34.魃0内容简介没有经过婚姻治疗的离婚是人世间最不负责任的务定，完整的家庭是父母给予孩子最好的礼物

冰河漂流  沸腾阿尔山之冬

![image](https://github.com/shibing624/pycorrector/assets/31341349/aab83bbe-d01e-446d-b452-39163a19946d)
![image](https://github.com/shibing624/pycorrector/assets/31341349/33a68c04-a86c-42a5-9779-b7835049cad9)

**Comment by shibing624** [comment]
模型不能保证100%准确，这种单个case的问题不要提issue了，意义不大。

**Comment by yongzhuo** [comment]
其实还是编码问题，一类是之前同[issues/448](https://github.com/shibing624/pycorrector/issues/448)那样的某个字符没有；
还有就是同这个issue提到的“￥34.魃0”，他纠了魃为8，然后数据就合起来了当成一个id，导致编码和原来的不一样，就会导致后边全按错了。
bpe不是一个字符对应一个id或多或少会引入该问题

**Comment by shibing624** [comment]
有道理，我修复下。

**Comment by hudaoling** [comment]
这个问题已经处理了吗？

**Comment by yongzhuo** [comment]
> 这个问题已经处理了吗？
一点小建议：
1.忽略，不等长导致错误比较多的可以不纠（比如一个句子超过3个错误的就忽略）；
2.除非改tokenizer, 按char来，否则比较难枚举所有的未登录词。
有的csc竞赛获奖队伍是这么做的，但是这样改了以后，就会造成预训练输入和微调输入不一致，要不要改你还得根据实际情况考虑(比如说必须获取准确错别字位置信息的时候)。
例如下面的重写tokenizer：
```
from transformers import BertTokenizer
class PretrainTokenizer(BertTokenizer):
    """ 强制单个字token, 避免自带的tokenize删除空白、或者是其他特殊字符的情况 """
    def tokenize(self, text):
        tokens = []
        for t in text:
            if self.do_lower_case:
                t = t.lower()
            if t in self.vocab:
                tokens.append(t)
            elif t == " ":
                tokens.append("[unused1]")
            else:
                tokens.append("[UNK]")
        return tokens
```
