### ISSUE TITLE
How can i use the other listed model to correct sentence?

### ISSUE THREAD

**Issue by seven-linglx** [shibing624/pycorrector#47]
There are six models in your package, what is the default one in your sample code, and how can i choose others model to use?  In my opinion,  the sample code is not enough in readme.

Your sample code is 
```
import pycorrector

corrected_sent, detail = pycorrector.correct('少先队员因该为老人让坐')
print(corrected_sent, detail)
```

**Comment by shibing624** [comment]
想用哪个模型，就进入模型命名的文件夹即可。preprocess.py -> train.py -> infer.py

**Comment by seven-linglx** [comment]
How to use the BERT model and get the 'pytorch_model.bin' ?
