### ISSUE TITLE
gpt纠错模型的评估结果和展示不一致？

### ISSUE THREAD

**Issue by muzhi1991** [shibing624/pycorrector#473]
您好，我在执行`python evaluate_models.py --model chatglm`想要复现你在README里面的评估结果都时候发现执行的结果好像不太一一致，差距还挺大，请问是什么原因呢？

我的执行结果如下
Sentence Level: acc:0.2627, precision:0.2472, recall:0.2413, f1:0.2442, cost time:131.01 s, total num: 1100

看代码里面用的模型是chatglm3-6b和一个您训练的lora，都是用的库里的，没有修改

**Comment by shibing624** [comment]
可能base模型版本变更了，你可以在自己下载的base上训练一遍lora再评测。
