### ISSUE TITLE
使用macbert时输入的参数中有空格，会导致无法成功纠错。使用T5时就可以成功纠错

### ISSUE THREAD

**Issue by yuanjingtai** [shibing624/pycorrector#479]
使用macberts时
没有空格：
![图片](https://github.com/shibing624/pycorrector/assets/58925704/3fcedc50-4d33-4593-93c9-630347155456)
![图片](https://github.com/shibing624/pycorrector/assets/58925704/f22d9d4d-775e-46c3-9456-1586e9ad1074)
有空格：
![图片](https://github.com/shibing624/pycorrector/assets/58925704/b5da21a1-bf2a-4ce3-939b-3467270ea366)
![图片](https://github.com/shibing624/pycorrector/assets/58925704/aadd4020-0b6f-4cdb-bd75-eb9a20a2e24f)

使用T5时：
没有空格：
![图片](https://github.com/shibing624/pycorrector/assets/58925704/2fdb1076-d882-48de-a78d-5f0f849f9c47)
![图片](https://github.com/shibing624/pycorrector/assets/58925704/4cd2f99e-5994-4c21-9c1c-4df3a7c539e1)

有空格：
![图片](https://github.com/shibing624/pycorrector/assets/58925704/f8ce7251-2c3b-4de0-b467-87243c784d08)
![图片](https://github.com/shibing624/pycorrector/assets/58925704/8fd547ce-b1d5-4fe0-a2e4-5a000e184418)

**Comment by shibing624** [comment]
macberts对空格敏感，训练时预处理去除了空格的，你可以在传入model之前做strip()。
