### ISSUE TITLE
现在使用给定的数据基进行训练，后期我想自己寻找其他的数据集训练

### ISSUE THREAD

**Issue by suchstar** [shibing624/pycorrector#485]
### Describe the Question
当前我已经采用样例数据集进行训练了，后期我想自己引入数据集训练。
我想问下，后期我引入的数据集训练的时候，还需要带上原来的训练数据集吗？还是只是增量的就可以？
如果增量的不可以，我有啥办法增量训练吗？

**Comment by shibing624** [comment]
带上原来的训练数据集
