### ISSUE TITLE
T5模型预测的时候一直为0

### ISSUE THREAD

**Issue by XOng-lzh** [shibing624/pycorrector#489]
Generating outputs:   0%|          | 0/1 [00:00<?, ?it/s]
部署在了Linux的一个容器里面，但是每次调用的时候，log进度一直为0%

**Comment by shibing624** [comment]
需要gpu，不然速度慢。

**Comment by funworl** [comment]
t5模型可以处理多字少字问题吗

**Comment by shibing624** [comment]
嗯
