### ISSUE TITLE
能不能把 /data/bert_pytorch/multi_cased_L-12_H-768_A-12  /data/bert_pytorch/multi_cased_L-12_H-768_A-12/vocab.txt 这两个数据分享一下 

### ISSUE THREAD

**Issue by zhaolulul** [shibing624/pycorrector#49]

**Comment by shibing624** [comment]
https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip

**Comment by zhaolulul** [comment]
谢谢你

**Comment by ECNUHP** [comment]
> https://storage.googleapis.com/bert_models/2018_11_23/multi_cased_L-12_H-768_A-12.zip
> 数据来自：https://github.com/google-research/bert

您好,非常感谢您提供下载链接,但是程序运行的时候提示:No such file or directory: ../multi_cased_L-12_H-768_A-12/pytorch_model.bin'   模型文件不是这个pytorch_model.bin  不知道怎么回事

**Comment by shibing624** [comment]
这个文件需要通过pytorch版本的bert转换，具体转换方法见https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/convert_tf_checkpoint_to_pytorch.py PS: 如果是个人研究，建议熟悉bert的思路对nlp在深度方法的理解会很有帮助。

**Comment by ECNUHP** [comment]
> 这个文件需要通过pytorch版本的bert转换，具体转换方法见https://github.com/huggingface/pytorch-pretrained-BERT/blob/master/pytorch_pretrained_bert/convert_tf_checkpoint_to_pytorch.py PS: 如果是个人研究，建议熟悉bert的思路对nlp在深度方法的理解会很有帮助。

恩恩,问题解决了,真的很感谢您的解答,点赞!!!
