### ISSUE TITLE
可以基于你发布的hf的模型再训练吗？

### ISSUE THREAD

**Issue by hudaoling** [shibing624/pycorrector#497]
你好，请问下，可以基于你发布的模型，只用自己的数据再训练吗？
![image](https://github.com/shibing624/pycorrector/assets/63828645/fd14e392-862b-419d-a91f-f71cf3e16ca3)

1w条样本领域内的样本句子，进行数据增强（替换谐音词，英文单词增删改字母），生成了11w增强样本你，
采用这种方式，训练下来感觉train样本纠错还勉强能看，迁移到测试集上以后就比较差，好纠结啊。

**Comment by shibing624** [comment]
可以再训练；建议融合我的训练集从头训练。

**Comment by Jamie2898** [comment]
如果从头微调macbert，是不是直接把train_macbert4csc.yml文件里的BERT_CKPT改为hfl/chinese-macbert-base就行？

**Comment by shibing624** [comment]
可以

**Comment by Jamie2898** [comment]
谢谢。另外，找了一些公开数据集，有的case没有错误，也就json中没有wrong_ids，这种数据放进训练集模型可以跑吗？会对模型效果产生负面影响吗？

**Comment by shibing624** [comment]
可以放
