### ISSUE TITLE
指定纠错

### ISSUE THREAD

**Issue by joseph16388** [shibing624/pycorrector#499]
请问可以指定纠错的target和source的基本发音不要改变吗？举例：干净的胡面，只能改为干净的湖面，不要改为干净的画面。

**Comment by shibing624** [comment]
1.训练集里面指定，只纠错音似错误就可以；
2.用自己改好的训练集，再训练一版模型。

**Comment by joseph16388** [comment]
> 1.训练集里面指定，只纠错音似错误就可以； 2.用自己改好的训练集，再训练一版模型。

好的,3Q！
