### ISSUE TITLE
能发篇博客讲讲具体实现的过程和算法结构么

### ISSUE THREAD

**Issue by LightR0** [shibing624/pycorrector#5]
如上，Thank u

**Comment by shibing624** [comment]
嗯，在写。本来用于参加CGED2018测评的，这个测评时间也刚过，放出来也没关系了。

**Comment by LightR0** [comment]
好的，等大佬的博客

**Comment by djk111** [comment]
大佬，您的博客发了吗？想看看

**Comment by willduan** [comment]
@shibing624 大佬，博客发了吗，想观摩

**Comment by huangshenno1** [comment]
建议修改一下参考文献那，Neural Language Correction with Character-Based Attention 的作者姓 谢

**Comment by huangshenno1** [comment]
很好的工作，加油！

**Comment by shibing624** [comment]
终于就着别人的论文，写了一个博客：6. [基于文法模型的中文纠错系统](https://blog.csdn.net/mingzai624/article/details/82390382)

**Comment by shibing624** [comment]
此问题暂时关闭， 如果未解决的话重新open，我来跟进。
