### ISSUE TITLE
关于使用rnn作为语言模型训练和预测的一些问题请教

### ISSUE THREAD

**Issue by maozezhong** [shibing624/pycorrector#50]
您好，参考了下您的代码，最近在用biLSTM+attention的方式做中文检错，希望对于一个输入句子得到可能错误的位置。问下细节问题。

在训练的时候训练数据构造如下：
输入： "[start] 今 天 天 气 很 好"

label："今 天 天 气 很 好 [end]"

2. 预测的时候，假设输入句子为“今天添气横好”

把"[start] 今 天 添 气 横 好"输入模型， infer后可以得到各个字对应的概率，然后根据概率卡阈值得到可能错误的位置。

请问数据构造和预测的逻辑有问题吗？

我用上述的预测逻辑得到输入句子每个位置的概率基本上接近1.我想了下，因为训练的时候模型拟合的方向是将输入句子往其左移1位偏的，这样的话模型在forward的时候只要无脑使得预测输出为输入左移1位就行，所以对于输入句子不管有没错误，每个位置的预测概率基本接近1. 感觉是预测的逻辑有问题，应该如何预测呢？

**Comment by shibing624** [comment]
rnn模型作为语言模型，只是一个句子似然概率判断的手段，无法直接端到端作为文本纠错的模型。判断错别字的概率是根据该字在句子中结合上下文判断得到的一个似然概率，我在代码中有用到一个绝对方差的方法给出的。如果你对rnn模型做纠错感兴趣，推荐一篇论文里可以参考一下：context2vec，和 https://www.isca-speech.org/archive/SLaTE_2017/pdfs/SLaTE_2017_paper_5.pdf ，附上我的一些零碎的笔记：https://blog.csdn.net/mingzai624/article/details/82809968。   希望可以帮到你，如果你有其他其他更好的方法找到错字位置，有更好的准召率，欢迎交流。

**Comment by maozezhong** [comment]
多谢
