### ISSUE TITLE
如何提升检出率

### ISSUE THREAD

**Issue by rickywu** [shibing624/pycorrector#500]
本合同文本供用人单位与建立劳动关系的劳动者签定劳动合同时使用。

签定应该纠正为签订，但没检查出来

**Comment by shibing624** [comment]
用混淆集纠错。

**Comment by TW-NLP** [comment]
可以使用语法错误增强工具，来提高模型的鲁棒性，代码如下：https://github.com/TW-NLP/ChineseErrorCorrector/tree/main

**Comment by rickywu** [comment]
@TW-NLP 不能一次检查多个错误吗

**Comment by TW-NLP** [comment]
@rickywu 模型没有检出是因为，在训练预料中没有涵盖此类问题，可以用工具进行拼写错误的数据增强，然后提高模型鲁棒性，目前博主的macbert拼写纠错是可以一次检测多个错误的。

**Comment by rickywu** [comment]
@TW-NLP 你意思是要用你这个微调模型？

**Comment by TW-NLP** [comment]
@rickywu 还是用博主的，但是可以用增强的数据，在博主给出的模型上进行二次微调，来打造自己行业的纠错模型。
