### ISSUE TITLE
AttributeError: 'MacBertCorrector' object has no attribute 'correct_batch'

### ISSUE THREAD

**Issue by sakuradiss** [shibing624/pycorrector#501]
AttributeError: 'MacBertCorrector' object has no attribute 'correct_batch'

**Comment by shibing624** [comment]
pip install pycorrector -U

**Comment by sakuradiss** [comment]
> pip install pycorrector -U
大佬，我在执行本地模型的时候不能设置成相对路径是什么原因呢

**Comment by shibing624** [comment]
看下python的sys.path的作用，不懂的话就写绝对路径。
