### ISSUE TITLE
老师你好！关于数据集的问题

### ISSUE THREAD

**Issue by Duer666** [shibing624/pycorrector#503]
想请问wang271k+sighan数据集的train、dev、test 具体是如何分配的 这段描述还是有些不清晰 

test.json 和 dev.json 为 SIGHAN数据集， 包括SIGHAN13 14 15，来自 [官方csc.html](http://nlp.ee.ncu.edu.tw/resource/csc.html) ，文件大小：339kb，4千条。
train.json 为 Wang271k数据集，包括 Wang271k ，来自 [Automatic-Corpus-Generation dimmywang提供](https://github.com/wdimmy/Automatic-Corpus-Generation/blob/master/corpus/train.sgml) ，文件大小：93MB，27万条。

**Comment by shibing624** [comment]
问题是啥？ 

train：27w；
test： 4k；
dev：无，不需要。

**Comment by Duer666** [comment]
抱歉没有描述清楚 https://huggingface.co/datasets/shibing624/CSC

**Comment by Duer666** [comment]
感谢您的回答，抱歉没有描述清楚 
https://huggingface.co/datasets/shibing624/CSC
在这个网址中 train.json 、dev.json 、test.json 分别为251835条、 27981条、1100条，可以看出test.json是sighan15的测试集。但是train.json和dev.json的具体构成我想了解清楚，是由哪几个数据集的训练集或者测试集混合的。因为我用这个数据集跑其他模型的过程中发现训练损失和验证损失差距较大，猜想是否是数据分布问题
