### ISSUE TITLE
英文纠错en_spell_corrector.py的性能问题

### ISSUE THREAD

**Issue by yongzhuo** [shibing624/pycorrector#504]
- [ ] I checked to make sure that this is not a duplicate issue

### Is your feature request related to a problem? Please describe.

英文纠错en_spell_corrector.py中的probability每次都需要重新计算所有词频率总和N，如果初始化的时候计算好，速度能提升10倍以上。
```
    def probability(self, word):
        """
        probability of word
        :param word:
        :return:float
        """
        N = sum(self.word_freq_dict.values())
        return self.word_freq_dict.get(word, 0) / N
```
实测官方代码中的3w+英文词频，
短文本：修改前为0.092571s/sentence，修改后为0.001562s/sentence；
长文本：修改前为0.025783s/sentence，修改后为0.001795s/sentence；

如果是全量12w+英文词频，
短文本：修改前为0.012908s/sentence，修改后为0.000565s/sentence；
长文本：修改前为0.091642s/sentence，修改后为0.001529s/sentence；

速度提升还是很明显的，可以优化。

**Comment by shibing624** [comment]
感谢，fixed。
