### ISSUE TITLE
训练MacBert4Csc时报错

### ISSUE THREAD

**Issue by s19293949** [shibing624/pycorrector#510]
数据是根据样例生成的，报错信息如下：
![image](https://github.com/user-attachments/assets/6a0cb6b9-c467-4877-9570-34e90261907c)
是由于这段代码造成吗：
![image](https://github.com/user-attachments/assets/11b7c7d1-3d77-4734-9255-5c01ee9fd1ed)

**Comment by s19293949** [comment]
训练代码中添加 max_length似乎没有作用

**Comment by bigdogaaa** [comment]
> 训练代码中添加 max_length似乎没有作用

使用自己的语料时，如果存在长度超过512的现象，需要给tokenizer设置参数`truncation=True`

**Comment by s19293949** [comment]
> > 训练代码中添加 max_length似乎没有作用
> 
> 使用自己的语料时，如果存在长度超过512的现象，需要给tokenizer设置参数`truncation=True`

是的，已经解决了
