### ISSUE TITLE
使用 chatglm3-6b-csc-chinese-lora 出現 config.json 找不到的錯誤

### ISSUE THREAD

**Issue by akalanning** [shibing624/pycorrector#515]
你好，以下錯誤提供給您參考。

我在 colab 上執行：
from transformers import AutoModelForSequenceClassification, AutoTokenizer
model = AutoModelForSequenceClassification.from_pretrained("shibing624/chatglm3-6b-csc-chinese-lora")

然後它報錯：
Entry Not Found for url: https://huggingface.co/shibing624/chatglm3-6b-csc-chinese-lora/resolve/main/config.json.

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_gated_repo, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    454         if revision is None:
    455             revision = "main"
--> 456         raise EnvironmentError(
    457             f"{path_or_repo_id} does not appear to have a file named {full_filename}. Checkout "
    458             f"'[https://huggingface.co/{path_or_repo_id}/tree/{revision}'](https://huggingface.co/%7Bpath_or_repo_id%7D/tree/%7Brevision%7D') for available files."

OSError: shibing624/chatglm3-6b-csc-chinese-lora does not appear to have a file named config.json. Checkout 'https://huggingface.co/shibing624/chatglm3-6b-csc-chinese-lora/tree/main' for available files.

**Comment by shibing624** [comment]
使用merged模型。
