### ISSUE TITLE
老师你好，想请教一下GPT纠错模型微调相关的问题

### ISSUE THREAD

**Issue by Wwwwei** [shibing624/pycorrector#517]
您好，我尝试了您提供的chatglm纠错模型 （https://huggingface.co/shibing624/chatglm3-6b-csc-chinese-lora） 效果很好，但没法纠错一些特定领域（例如医疗、金融）内文本。

想请问一下，如果我想补充一些领域内的的纠错语料，是直接在chatglm3-6b-csc-chinese-lora上进行微调吗？还是需要加上您提供的数据集在chatglm3上从头微调？

**Comment by shibing624** [comment]
1. 可以在在chatglm3-6b-csc-chinese-lora上继续微调；
2. 建议从头微调，还需要补充通用对话数据，如sharegpt等，避免领域数据过拟合。

**Comment by Wwwwei** [comment]
感谢老师回复~
还想请教一下，如果继续在chatglm3-6b-csc-chinese-lora微调的话，特定领域的纠错数据集大概需要什么量级呢？

**Comment by shibing624** [comment]
建议：
1.重新从chatglm3-6b或者glm4 开始训练；
2.1w条 纠错数据，10w条通用数据。

**Comment by Wwwwei** [comment]
谢谢老师回复。
