### ISSUE TITLE
这是什么奇怪的bug？

### ISSUE THREAD

**Issue by hanxu49** [shibing624/pycorrector#519]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
![image](https://github.com/user-attachments/assets/b07d0a82-4cd1-4033-88ea-7e012fd392f4)

**Comment by shibing624** [comment]
触发了多字？

**Comment by hanxu49** [comment]
> 触发了多字？

大佬好，有什么办法可以解决吗？

**Comment by shibing624** [comment]
加后处理。
