### ISSUE TITLE
请问为何编译的时候会报'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte

### ISSUE THREAD

**Issue by QiuRoy** [shibing624/pycorrector#522]
![screenshot-1728760389319](https://github.com/user-attachments/assets/720ef884-eac2-4dc2-9e7c-c8f4a76ba49a)

**Comment by QiuRoy** [comment]
import os
from pycorrector import Corrector

pwd_path = os.path.abspath(os.path.dirname(__file__))
lm_path = os.path.join(pwd_path, './zh_giga.no_cna_cmn.prune01244.klm')
m = Corrector(lm_path)
print(m.correct_batch(['少先队员因该为老人让坐', '你找到你最喜欢的工作，我也很高心。']))

**Comment by QiuRoy** [comment]
不行，还是同样的报错

**Comment by shibing624** [comment]
用macbert4csc模型

**Comment by QiuRoy** [comment]
请问使用ErnieCscCorrector是无法自定义模型路径吗？
from pycorrector import ErnieCscCorrector
import os

pwd_path = os.path.abspath(os.path.dirname(__file__))
lm_path = os.path.join(pwd_path, 'csc-ernie-1.0.pdparams')
print(lm_path)
m = ErnieCscCorrector(model_name_or_path=lm_path)
print(m.correct_batch(['今天新情很好', '你找到你最喜欢的工作，我也很高心。']))
![screenshot-1729002145784](https://github.com/user-attachments/assets/5e9ffe2c-4908-44a3-8757-f9b59c6c2fcb)

**Comment by shibing624** [comment]
无法自定义模型路径
