### ISSUE TITLE
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/configuration_validator.py:101: UserWarning: you defined a validation_step but have no val_dataloader. Skipping val loop   rank_zero_warn(f"you defined a {step_name} but have no {loader_name}. Skipping {stage} loop") LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

### ISSUE THREAD

**Issue by 11ddde** [shibing624/pycorrector#523]
两个警告：
/usr/local/lib/python3.8/dist-packages/pytorch_lightning/trainer/configuration_validator.py:101: UserWarning: you defined a validation_step but have no val_dataloader. Skipping val loop
  rank_zero_warn(f"you defined a {step_name} but have no {loader_name}. Skipping {stage} loop")
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

和

/usr/local/lib/python3.8/dist-packages/pytorch_lightning/callbacks/model_checkpoint.py:689: UserWarning: ModelCheckpoint(monitor='val_loss') not found in the returned metrics: ['train_loss', 'train_loss_step', 'train_loss_epoch']. HINT: Did you call self.log('val_loss', value) in the LightningModule?
  warning_cache.warn(m)
  
  
  库版本与readme中一致
  transformers==4.12.0 
  pytorch-lightning==1.4.9 
  torch==1.9.0 yacs 
  torchmetrics==0.6.0 
  
  请问是什么原因

**Comment by 11ddde** [comment]
训练macbert时出现的

**Comment by shibing624** [comment]
忽略
