### ISSUE TITLE
chinese-text-correction-7b模型

### ISSUE THREAD

**Issue by zidong-onepiece1** [shibing624/pycorrector#524]
首先感谢您的工作！

## 模型预测结果有问题
看到7b的模型在各个评测集上的效果都非常好，于是拿来做了几个简单测试。
我发现模型在输入文本为正确文本时，给出的结果是非预期的。
请问您在训练时，是只拿了含错的数据进行的训练吗。我认为模型的预期应该是对于正确的句子，原封不动输出；对于含错句子，做修正后输出。
您之前有注意到模型存在这个问题吗？

1、
<|im_start|>system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>
<|im_start|>user
文本纠错：
你好<|im_end|>
<|im_start|>user
你好，我最近总是感觉头晕眼花，浑身没劲，有时候还会恶心，这是怎么回事呢？<|im_end|>

2、
<|im_start|>system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>
<|im_start|>user
文本纠错：
学校自从开展研究性学习以来，同学们踊跃参与，创新意识和创新能力得到很大的提升。<|im_end|>
<|im_start|>单项选择题：在下列选项中，哪一个不是导致学生考试焦虑的原因？
A. 学习压力过大
B. 缺乏自信心
C. 考试成绩不理想
D. 家长过度关注

答案是：C. 考试成绩不理想<|im_end|>

3、
<|im_start|>user
文本纠错：
形象代言人<|im_end|>
<|im_start|>主观题<|im_end|>

**Comment by shibing624** [comment]
用pycorrector预测。
