### ISSUE TITLE
有关[chinese-text-correction-1.5b]的纠错问题

### ISSUE THREAD

**Issue by Dryilv** [shibing624/pycorrector#526]
首先感谢您的工作，我在使用[chinese-text-correction-1.5b]进行j纠错的时候出现了以下问题[chinese-text-correction-7b]，并且不止有这一个样本，重复多次都是一样的结果。
{'source': '“这些都来自我曾经的敌人，他们无一不难难缠。', 'target': '“这些都来自我曾经的敌人，他们个个难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠难缠', 'errors': [('无', '个', 15), ('一', '个', 16), ('不', '', 17), ('', '缠', 18)]}

**Comment by shibing624** [comment]
大模型的输出不可控，加长度截断。
