### ISSUE TITLE
关于Qwen训练的数据集

### ISSUE THREAD

**Issue by TW-NLP** [shibing624/pycorrector#530]
您好，现在训练的Qwen纠错模型，是使用 README中的那些big train data 吗？是怎么进行数据处理的，这块可以进行详细的说一下吗？是将拼写和语法的数据都放进去了吗？是迭代训练的还是汇总后放入的？

**Comment by shibing624** [comment]
是big data;合并；汇总的，加通用问答数据，纠错数据：通用数据=1:5 ，做sft。

**Comment by TW-NLP** [comment]
好的 ，谢谢
