### ISSUE TITLE
Qwen2.5-7B-CTC在MCSC数据集的训练集上效果远差于测试集。

### ISSUE THREAD

**Issue by DouHappy** [shibing624/pycorrector#533]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

首先感谢你们的开源工作。我看到项目中有一个Qwen2.5-7B-CTC模型，这个模型在MCSC上的效果出奇的高，远高于我在MCSC上的训练结果，我下载了对应模型权重并且用我自己的测试脚本也测得了相近的f1指标。但是我还发现Qwen2.5-7B-CTC在MCSC的训练集上的效果要远差于测试集。我的详细测试结果如下：
|测试集名称|测试数据条数|acc|precision|recall|f1|
|:---:|:---:|:---:|:---:|:---:|:---:|
|MCSC-test|19650|0.9697|0.9907|0.9964|0.9936|
|MCSC-train|157194|0.8099|0.9730|0.9790|0.9760|

我想问一下您有没有测试过这个模型在MCSC训练集上的表现呢？有没有具体的指标可以共享出来对比一下？

**Comment by shibing624** [comment]
差多少？是跟0.9959的差别吗？

**Comment by DouHappy** [comment]
> 差多少？是跟0.9959的差别吗？可能过拟合而已。

抱歉我的意思好像没表达清楚。我意思是说Pycorrector项目中给出的Qwen2.5-7B-CTC这个模型在MCSC的训练集和测试集上的准确率差距较大。我使用的是项目中开源的模型参数，这个模型用我的测试脚本在MCSC测试集上能基本复现出Pycorrector项目的结果（f1 0.9936 很接近给出的指标0.9959），但是理应在训练集上也能得到相似的指标。我在训练集上运行相同的测试脚本得到的指标下降了很多（acc从0.9697->0.8099，f1从0.9936->0.9760）。
所以想询问一下你们有没有测试过在MCSC测试集上的指标效果。

**Comment by DouHappy** [comment]
> 训练Qwen2.5-7B-CTC时，用的混合数据集，包括sighan、EC-LAW等一大堆纠错类的数据集，在MCSC的训练集上评估效果差是正常的。主要是训练实用的模型，没有专门为哪个数据集单独训练模型，价值不大。

个人认为如果MCSC的数据分割合理，保证训练集和测试集的分布尽量一致的前提下，模型应该在MCSC的训练集和测试集上的效果也基本保持一致？除非是模型的训练数据中混入了MCSC测试集的数据，否则MCSC训练集上的正确率不应该比MCSC测试集的正确率高这么多？
