### ISSUE TITLE
nlp新人请教代码意思

### ISSUE THREAD

**Issue by kelly2016** [shibing624/pycorrector#54]
在求ngram平均值的时候，一开始进行这段操作，不知道是气什么作用的？为啥要把n个近值相加平均？
 avg_scores = [sum(scores[i:i + n]) / len(scores[i:i + n]) for i in range(len(sentence))]
  ngram_avg_scores.append(avg_scores)

**Comment by shibing624** [comment]
先计算ngram 的值，再平均。
