### ISSUE TITLE
如果有平行语料，如何进行检错或纠错？

### ISSUE THREAD

**Issue by marianasignal** [shibing624/pycorrector#542]
- [x] I checked to make sure that this is not a duplicate issue
比如：
1、他说等他脸好了再发给我，他说等他练好了再发给我
2、明天陪你们出站，明天排你们出战
同时可能有文本所属领域，比如医疗、语音输入等

**Comment by shibing624** [comment]
明天陪你们出站——》明天排你们出战   你觉得合理吗？

**Comment by marianasignal** [comment]
不合理，想问下，如果选个更合适的，是不是计算句子的ppl就行

**Comment by shibing624** [comment]
训练纠错模型就可以

**Comment by marianasignal** [comment]
感谢回复，不过训练的前提是得先知道哪个更可能是对的，所以判断更对的依据，是不是计算ppl就行？

**Comment by shibing624** [comment]
ppl没法判断哪个对，需要人工标注，或者llm辅助。

**Comment by marianasignal** [comment]
明白，我试了gptcorrector，直接纠错也纠不出来，得换个思路用llm了

**Comment by marianasignal** [comment]
ppl 至少还是可以判断出”明天排你们出战“这种明显不顺的结果吧
