### ISSUE TITLE
get_errors函数中delete操作问题

### ISSUE THREAD

**Issue by zwkatgithub** [shibing624/pycorrector#544]
https://github.com/shibing624/pycorrector/blame/df68a3624e513bf396ecb6f9dfc0fe60234f6b73/pycorrector/utils/error_utils.py#L27

difflib文档关于操作的描述：

值 | 含意
-- | --
'replace' | a[i1:i2] 应由 b[j1:j2] 替换。
'delete' | a[i1:i2] 应被删除。 请注意在此情况下 j1 == j2。
'insert' | b[j1:j2] 应插入到 a[i1:i1]。 请注意在此情况下 i1 == i2。
'equal' | a[i1:i2] == b[j1:j2] (两个子序列相同)。

根据上述描述，get_errors中delete操作，新的纠错文本是否不需要拼接删除文本？

**Comment by shibing624** [comment]
有道理，已经fix了。
