### ISSUE TITLE
关于训练数据的格式

### ISSUE THREAD

**Issue by Weirdo233** [shibing624/pycorrector#55]
有具体的格式要求吗？必须采用xml？

**Comment by shibing624** [comment]
没有要求，自己改写reader 就可以。采用xml是为了更文本纠错比赛对齐，通用格式，便于扩展。

**Comment by Weirdo233** [comment]
> 没有要求，自己改写reader 就可以。采用xml是为了更文本纠错比赛对齐，通用格式，便于扩展。

好的，谢谢
