### ISSUE TITLE
一些小疑问

### ISSUE THREAD

**Issue by Springzcf** [shibing624/pycorrector#58]
您好，在您的代码学习到了很多东西，非常感谢。但是我有以下小问题，是否可以解答一下，多谢。@shibing624
1：代码中采用单个字计算score，但是kemln训练生成的n-gram模型，却是经过中文分词后的概率得分。这样做合适吗？
```python 
for i in range(len(sentence) - n + 1): 
  word = sentence[i:i + n]  
  score = self.ngram_score(list(word))  
  scores.append(score)
```
_代码位于detector.py->detect函数_
2：我看代码在进行detect和correct的时候，都是采用的n-gram，没有采用rnn_crf等相关的神经网络，请问应该怎么样通过神经网络来进行detect或者correct？

**Comment by shibing624** [comment]
1. 单字有单个字的模型处理，分词有分词的kenlm模型。代码跟模型是对应的。
2. detect.py 和 correct 是规则处理的。rnn_crf的代码单独在对应的文件夹中。

**Comment by Springzcf** [comment]
这样啊 了解了多谢了

**Comment by Springzcf** [comment]
啊，对了，因为有自己的语料，想生成自己的语料库。
所以想再咨询一下样本是怎么生成的问题？比如怎么样对数字、符号进行处理？比如在训练n-gram的时候，单个字的模型您这边是怎么样进行处理样本的？是直接将每个字之间都插入空格符吗？有没有可以参考的步骤？
多谢了

**Comment by shibing624** [comment]
数字、英文、符号、停用词等按nlp处理的一般步骤过滤，然后以字切分，至于字之间加不加空格不重要，只要能分开放到列表就可以。

**Comment by Springzcf** [comment]
这样啊 非常感谢
