### ISSUE TITLE
关于人名问题

### ISSUE THREAD

**Issue by duguiming111** [shibing624/pycorrector#63]
你好，检测的句子里面涉及到人名都会检测错误

**Comment by shibing624** [comment]
好，我添加一下todo: 补充人名、地名、机构等的实体识别功能，并过滤。

**Comment by duguiming111** [comment]
比如张林，就会纠正为：张琳

**Comment by duguiming111** [comment]
比如“张林..........” 纠正为：“张琳...........”，因该是基于未登录词，后者比前者概率高，感觉针对名字可以做点东西。

**Comment by duguiming111** [comment]
# return confusion_sorted[:len(confusion_word_list) // fraction + 1]
 confusion_sorted[:len(confusion_word_list) // fraction + 1].append(word)
 return confusion_sorted
纠错候选集应该加上这个疑是错误的词吧！

**Comment by duguiming111** [comment]
pip安装的版本没有将疑是错误的词加入到最后的评分里

**Comment by shibing624** [comment]
嗯，已经更新。
