### ISSUE TITLE
关于纠错的评价标准

### ISSUE THREAD

**Issue by zhazl** [shibing624/pycorrector#64]
嗨 您好 请教个问题 不同模型下得到的infer.txt 如何评价它们之间的纠错效果好坏呢？

**Comment by shibing624** [comment]
人眼看吧。😆

**Comment by zhazl** [comment]
哦哦 另外再请教个问题 confusion set在不同的任务下一般怎么获取呢 如果是收集通用的confusion set，这个效果是不是不够理想？

**Comment by shibing624** [comment]
这个具体任务具体分析了，该工具支持自定义添加，我这边只能补充一些通用的confusion set.

**Comment by NotToday** [comment]
可以使用字错误率(CER)和句错误率(SER)的降低程度来衡量
