### ISSUE TITLE
如何利用Kenlm训练基于字的语言模型呢

### ISSUE THREAD

**Issue by tianyunzqs** [shibing624/pycorrector#65]
我把训练语言用空格隔开每个字，用kenlm训练语言模型，报错：
cause `s.n[j] == 0'.
Could not calculate Kneser-Ney discounts for 3-grams with adjusted count 2 because we didn't observe any 3-grams with adjusted count 1; Is this small or artificial data?
Try deduplicating the input.  To override this error for e.g. a class-based model, rerun with --discount_fallback
kenlm的输入训练语料必须是分词后的文件，那基于字的语言模型该如何训练呢？

**Comment by shibing624** [comment]
以字切分就ok了呀。

**Comment by shibing624** [comment]
暂时关闭此问题，如果有疑问，欢迎再次打开。
