### ISSUE TITLE
关于示例的结果

### ISSUE THREAD

**Issue by Vincentkitty** [shibing624/pycorrector#66]
请问图片里展示的结果中，模型参数就是按照config里面的进行训练的嘛？ 我自己运行了一遍效果很差

**Comment by shibing624** [comment]
不是。config.py 的设置只是为了让程序跑通过，置于效果需要调整参数，图片的效果是使用全部数据集，然后epochs是60轮以上。

**Comment by Vincentkitty** [comment]
了解啦，多谢：）
