### ISSUE TITLE
我使用bert成功运行起来了，但结果不能理解

### ISSUE THREAD

**Issue by liujiahao88** [shibing624/pycorrector#68]
结果1：original text is: ['[CLS]', '少', '先', '队', '员', '因', '该', '为', '老', '人', '让', '[MASK]', '.', '机', '七', '学', '习', '是', '人', '工', '智', '能', '领', '遇', '最', '能', '体', '现', '智', '能', '的', '一', '个', '分', '知', '[SEP]']
Mask predict is: కన్నా 
original text is: ['[CLS]', '少', '先', '队', '员', '因', '该', '为', '老', '人', '让', 'క', 'న', '్', 'న', 'ా', '.', '机', '七', '学', '习', '是', '人', '工', '[MASK]', '能', '领', '遇', '最', '能', '体', '现', '智', '能', '的', '一', '个', '分', '知', '[SEP]']
Mask predict is: ##اتی
original sentence:少先队员因该为老人让座.机七学习是人工智能领遇最能体现智能的一个分知 => correct sentence:('少先队员因该为老人让కన్నా.机七学习是人工##اتی能领遇最能体现智能的一个分知', [['座', 'కన్నా', 10, 11], ['最', '##اتی', 23, 24]])
结果2：original sentence:少先队员因该为老人让座 => correct sentence:('少先队员因该为老人让座', [])
并不能实现纠错，请问，问题在哪

**Comment by shibing624** [comment]
你的bert模型选对了吗？

bert_model_dir = '../data/bert_pytorch/multi_cased_L-12_H-768_A-12'
bert_model_vocab = '../data/bert_pytorch/multi_cased_L-12_H-768_A-12/vocab.txt'

请在谷歌官方库下载。

**Comment by liujiahao88** [comment]
> 你的BERT模型选对了吗？
> 
> bert_model_dir ='../data/bert_pytorch/multi_cased_L- 
> 12_H- 768_A- 12'bert_model_vocab ='../data/bert_pytorch/ multi_cased_L- 12_H-768_A-12/vocab.txt'
> 
> 请在谷歌官方库下载。

你好。确实是根据你的链接下载的。但内部需要的是pytorch_model.bin
我下载完后目录文件：
![image](https://user-images.githubusercontent.com/52027469/59995559-15fbfd80-968a-11e9-9ffb-b1eb79feff25.png)

**Comment by wulouzhu** [comment]
@liujiahao88 请问你那个pytorch_model.bin文件是怎么生成的，谢谢

**Comment by shibing624** [comment]
官方库有工具，可以生成。

**Comment by shibing624** [comment]
已经更新，并提供fine-tuned模型，欢迎大家提出问题、意见。

**Comment by wulouzhu** [comment]
楼主，你用的数据量有多大，处理之后的数据长什么样能看一下吗

**Comment by shibing624** [comment]
已经更新readme. https://github.com/shibing624/pycorrector/tree/master/pycorrector/bert

**Comment by wulouzhu** [comment]
楼主，有以下两个问题：
1.每次代码修改之后都得将代码更新到/root/anaconda3/lib/python3.6/site-packages中才能生效。

2. 运行 python tests/bert_corrector_test.py报错：
File "/root/anaconda3/lib/python3.6/site-packages/pycorrector/bert/bert_corrector.py", line 43, in initialize_bert_corrector
    self.model = BertForMaskedLM.from_pretrained(self.bert_model_dir)
  File "/root/anaconda3/lib/python3.6/site-packages/pytorch_pretrained_bert-0.6.2-py3.6.egg/pytorch_pretrained_bert/modeling.py", line 645, in from_pretrained
    load(model, prefix=start_prefix)
  File "/root/anaconda3/lib/python3.6/site-packages/pytorch_pretrained_bert-0.6.2-py3.6.egg/pytorch_pretrained_bert/modeling.py", line 638, in load
    state_dict, prefix, local_metadata, True, missing_keys, unexpected_keys, error_msgs)
TypeError: _load_from_state_dict() takes 7 positional arguments but 8 were given

**Comment by shibing624** [comment]
当前master上的代码比pip上release的代码版本要新，建议卸载pip uninstall pycorrector，再运行最新代码。

**Comment by wulouzhu** [comment]
楼主，你使用的pytorch_pretrained_bert是什么版本的，我看pytorch_pretrained_bert里面没有BertForMaskedLM这个函数啊。对于上面提到的第2个问题运行 python tests/bert_corrector_test.py报错，查了很久都不知道问题出在哪

**Comment by wulouzhu** [comment]
找到问题了，原来是torch的版本不对

**Comment by wulouzhu** [comment]
@shibing624 
楼主,那个CGED是没有篇章信息的吧,你是怎么拿它来训练bert的?每一句都当作一篇文章?
还有训练的时候是不是只拿CGED语义正确的句子做训练?

**Comment by shibing624** [comment]
只拿了CGED正确的句子训练。

**Comment by HonayKing** [comment]
@shibing624 
楼主，纠错的fine-tuning具体是怎么实现的？
能提供下思路或代码吗？

**Comment by shibing624** [comment]
bert下readme有详细说明
