### ISSUE TITLE
特定领域词语纠错

### ISSUE THREAD

**Issue by wulouzhu** [shibing624/pycorrector#69]
你好，我想请问一下，对于特定领域的词语纠错，是不是把词汇加入到word_freq.txt文件中就可以了，如果不是的话，该怎么做呢？万分感谢

**Comment by shibing624** [comment]
加到 my_confusion.txt， 运行 examples/use_custom_confusion.py 。

**Comment by wulouzhu** [comment]
@shibing624  感谢回复！还有几个问题想再请教一下您
1. 是不是错别字包含在custom_confusion.txt中才能被纠正，如果是的话是不是要穷举很多一个词对应的可能的错别字，如果不是的话针对不包含在custom_confusion.txt的错别字情况是怎么纠错的
2. 如果我想要在人民日报或CGED的语料上加上自己的语料进行训练，但自己的语料中包含错别字的很少，这样会不会有影响
3. 我看配置文件默认的语言模型使用的是kenlm，楼主有没有对比过kenlm，seq2seq_attention，transformer，bert等语言模型的性能。楼主最近新增的transformer和bert是否已经可以使用？

麻烦楼主了，万分感谢！！

**Comment by shibing624** [comment]
1. custom_confusion.txt是用户自定义的纠错集，优先级最高，不包含在custom_confusion.txt的错别字也会默认执行规则纠错逻辑，具体见规则方法。
2. 需要用纠错语料训练，中文纠错语料确实很少，数据集也是制约中文该领域发展的主要原因之一，英文的纠错在Collin数据集上比赛结果已经很好了，现在已经发展到语法纠错级别了。
3. 性能比较：1）速度上统计模型的kenlm最快，也是本工具默认实现的原因。2）效果上：bert, 由于我只是在bert上比较浅显的fine-tune，未深入优化；trainsformer还未训练完成；seq2seq_attn的效果短文本稍好，但模型本身并不是针对纠错设计，改进loss针对错字位置和错字类型的优化效果会好些。

**Comment by wulouzhu** [comment]
谢谢楼主！
发现个bug，使用楼主自带的my_confusion.txt, 运行python use_custom_confusion.py之后，重启python，重新导入pycorrector
结果是这样的
>>> corrected_sent, detail = pycorrector.correct('交通先行了怎么过去啊？')
>>> print(corrected_sent, detail)
交通先行了怎么过去啊？ []
>>> corrected_sent, detail = pycorrector.correct('交通限行了怎么过去啊？')
>>> print(corrected_sent, detail)
交通先行了怎么过去啊？ [['限行', '先行', 2, 4]]

结果：错误的没有纠正过来，本来正确的却被改成错的，是我哪里操作错了吗

**Comment by shibing624** [comment]
本地测试，未复现问题，请升级版本后重试。或者写清楚复现方法，便于解决问题。
