### ISSUE TITLE
请教您 rnn_crf rnn_lm seq2seq这三个文件夹

### ISSUE THREAD

**Issue by orangetwo** [shibing624/pycorrector#7]
在程序运行时，这三个文件夹下的文件是不是独立的 并没有调用
因为 我在pip install pycorrector后查看源文件 并没有发现在这三个 文件
还是说我 安装的有问题？

蟹蟹。

**Comment by shibing624** [comment]
后来新增的，调研深度模型用于文本纠错的，还未集成上线。开发中，欢迎fork及提建议。

**Comment by willduan** [comment]
@shibing624 您好，请问深度模型在文本纠错中使用了吗，谢谢！

**Comment by shibing624** [comment]
调研中使用了，具体见最新代码。
