### ISSUE TITLE
英文纠错性能问题

### ISSUE THREAD

**Issue by wulouzhu** [shibing624/pycorrector#72]
你好，我看项目里面还有英文的语法纠错，请问楼主英文纠错效果如何？ 对于单复数错误的问题能纠正吗？谢谢

**Comment by shibing624** [comment]
英文使用编辑距离处理的词语拼写纠错，如果是语法错误，建议使用context模型，效果较好，也有针对此任务的论文：https://blog.csdn.net/mingzai624/article/details/82809968。
