### ISSUE TITLE
关于相似形状的字库的问题

### ISSUE THREAD

**Issue by fengzuo97** [shibing624/pycorrector#73]
2013年的那个比赛提供了一个相似拼音和相似形状的字库，作者的库里也有这两个文件，但是some_stroke.txt相比较比赛提供的字库少了很多，请问这个字库的来历？是经过自己的筛选过了吗？

**Comment by shibing624** [comment]
经过自己的筛选过了

**Comment by fengzuo97** [comment]
作者筛选的策略好像是去掉偏旁，然后相同即为形状相似的字，这个可以通过什么工具实现呢？而且筛选的也不是很全，本来有5000多个字，库中的same_stroke.txt只有300多个字。而且想“已”和巳”这种就会漏掉，如果只用笔画数来筛选，选择笔画数相近的字为相似字效果怎样呢?

**Comment by shibing624** [comment]
可以尝试，欢迎贡献哈。

**Comment by yudong27** [comment]
还有原始的相似拼音和相似形状的字库吗？ @fengzuo97
