### ISSUE TITLE
代码中的bert模型multi_cased_L-12_H-768_A-12

### ISSUE THREAD

**Issue by zhangxiaofanL** [shibing624/pycorrector#74]
你好，请问你训练得bert模型multi_cased_L-12_H-768_A-12与你readme中的chinese_finetuned_lm有什么不同，可以下载吗

**Comment by zhangxiaofanL** [comment]
另外请问TF_WEIGHTS_NAME = 'bert_model.ckpt'，你提供的链接下载微调好的模型里没有bert_model.ckpt，pytorch版本微调好只生成bert_config.json  pytorch_model.bin  vocab.txt这三个文件，请问bert_model.ckpt这个文件怎么获得的

**Comment by shibing624** [comment]
这个是下载好的模型文件名称。该部分代码正在开发中，常有变动。

**Comment by zhangxiaofanL** [comment]
还有请问下
1.那你现在bert部分用的模型是直接下载的模型还是微调过的模型呢？       
2.我看你的readme中，你现在微调方式是直接用pytorch的版本进行微调生成bert_config.json pytorch_model.bin vocab.txt。pythorch微调是没有生成bert_model.ckpt的，你是直接把下载好的模型的bert_model.ckpt放到微调的文件夹的吗？

**Comment by zhangxiaofanL** [comment]
另外:
1.BERT-Base, Multilingual Cased (New, recommended)
2.BERT-Base, Chinese
你现在好想是用的多语言的版本  多语言版本比中文版本要好吗？

**Comment by shibing624** [comment]
中文版本要好，chinese_finetuned_lm是在中文版本上fine-tuned的。pytorch的模型是微调之后的，bert_model.ckpt是默认的，都测试了一下效果。

**Comment by zhangxiaofanL** [comment]
你好
我成功运行之后的结果:
original sentence:少先队员因该为老人让座 => correct sentence:('少先队员应该为老人让路', [['因', '应', 4, 5], ['座', '路', 10, 11]])
original sentence:少先队员因该为老人让坐 => correct sentence:('少先队员应该为老人安慰', [['因', '应', 4, 5], ['让', '安', 9, 10], ['坐', '慰', 10, 11]])
original sentence:机七学习是人工智能领遇最能体现智能的一个分支 => correct sentence:('机器学习是人工智能领域最能体现智能的一个分支', [['七', '器', 1, 2], ['遇', '域', 10, 11]])
original sentence:机七学习是人工智能领遇最能体现智能的一个分知 => correct sentence:('第一学习是人工智能领域最能体现智能的一部分。', [['机', '第', 0, 1], ['七', '一', 1, 2], ['遇', '域', 10, 11], ['个', '部', 19, 20], ['知', '。', 21, 22]])
好像不能完全纠正错误
pytorch_model.bin是用的你read.me上的链接下载的，bert_model.ckpt是中文版bert下载后拷贝过去的

![image](https://user-images.githubusercontent.com/20238929/61109095-a3c34f80-a4b6-11e9-9f9f-d04e955911d9.png)

**Comment by shibing624** [comment]
嗯，欢迎提出新的意见和建议哈，目前效果暂时是这样哈，我在想办法改进呀。

**Comment by zhangxiaofanL** [comment]
嗯嗯  期待大神的改进。
另外不知道用百度的ERNIE效果会不会好一点

**Comment by shibing624** [comment]
可以试试，或者xlnet在文本生成上的效果也很好。

**Comment by zhangxiaofanL** [comment]
![image](https://user-images.githubusercontent.com/20238929/61113954-edfdfe00-a4c1-11e9-917b-c6061c29813f.png)

另外请问下你这些模型都试过了吗？哪个模型的效果最好呢，能都补充一下详细的readme吗

**Comment by shibing624** [comment]
说实话，规则的效果最好😆。我们追求算法的进步嘛

**Comment by zhangxiaofanL** [comment]
你好
请问我训练你的rnn_lm，你给的网盘下载下来的people2014_words.txt是已经分词的，是直接这个格式就可以喂给rnn训练了吗，还是需要将people2014_words.txt进行分字

**Comment by shibing624** [comment]
字粒度就分字

**Comment by superdu12138** [comment]
你好，bert模型如何预训练呢 pregenerate_training_data.py  在阅读README 文件   没有看到相关的
 pregenerate_training_data.py   这些文件

**Comment by superdu12138** [comment]
> 你好，bert模型如何预训练呢 pregenerate_training_data.py 在阅读README 文件 没有看到相关的
> pregenerate_training_data.py 这些文件

找到了

**Comment by superdu12138** [comment]
我 并不能训练BERT模型，在pregenerate_training_data.py  无法运行这条命令以及其他参数，

**Comment by binhaowang** [comment]
> > 你好，bert模型如何预训练呢pregenerate_training_data.py在阅读自述文件没有看到相关的
> > pregenerate_training_data.py这些文件
> 
> 找到了

在哪呀

**Comment by shibing624** [comment]
pytorch-transformers版本有更新, 可查看git旧版对应使用。
或者 https://github.com/huggingface/pytorch-transformers/blob/master/examples/README.md 参考使用
`python run_lm_finetuning.py \
    --output_dir=output \
    --model_type=roberta \
    --model_name_or_path=roberta-base \
    --do_train \
    --train_data_file=$TRAIN_FILE \
    --do_eval \
    --eval_data_file=$TEST_FILE \
    --mlm`

**Comment by brealisty** [comment]
> 我 并不能训练BERT模型，在pregenerate_training_data.py 无法运行这条命令以及其他参数，

请问下，你现在会弄了吗？

**Comment by binhaowang** [comment]
不会发自我的华为手机-------- 原始邮件 --------发件人： brealisty <notifications@github.com>日期： 2019年10月29日周二 21:21收件人： shibing624/pycorrector <pycorrector@noreply.github.com>抄送： wangbinhao <admihao@163.com>, Comment <comment@noreply.github.com>主    题： Re: [shibing624/pycorrector] 代码中的bert模型multi_cased_L-12_H-768_A-12 (#74)

我 并不能训练BERT模型，在pregenerate_training_data.py 无法运行这条命令以及其他参数，



请问下，你现在会弄了吗？

**Comment by shibing624** [comment]
update readme.
