### ISSUE TITLE
detector.py的计算细节及rnn_lm模型应用

### ISSUE THREAD

**Issue by JohnParken** [shibing624/pycorrector#75]
有没有可能在detect阶段用bert来识别，在correct阶段用规则的方法改呢。

**Comment by shibing624** [comment]
1. 可以的。最先一版bert代码是用规则做detect, bert来correct，最新一版代码更新成了纯bert实现detect和correct。欢迎各位自己调研用规则方法来做correct。
2. 但从我本意来讲，不推荐，如果规则来做correct，那只是字音字形阶段的纠错改正，bert模型更倾向于语义理解。
3. 固然目前的效果看来bert纠错会有语义纠偏的情况，但句子是连贯通顺的，如果仅纠结于字面，那可能并没有发挥模型本身的优势。

**Comment by JohnParken** [comment]
嗯嗯，感谢楼主。

**Comment by JohnParken** [comment]
楼主，我有一个小问题想要请教一下，就是在计算detector.py中的_get_maybe_error_index函数中计算平均绝对离差的时候为什么要用中位数作为基准，而不是用平均数作为基数，这样做有什么考虑吗？

**Comment by shibing624** [comment]
1.中位数不受最大、最小两个极端数值的影响；
2.部分错字得分会变动极大，对平均分影响大，而中位数不会影响；
3.中位数可以反映该句子片段的错字的得分趋势。

**Comment by JohnParken** [comment]
谢谢楼主解答，受教受教。对了楼主前两天更新的margen_median是为了提高计算速度吗

**Comment by JohnParken** [comment]
楼主，rnn_lm的模型有开源吗，在output/model下没有找到呢

**Comment by JohnParken** [comment]
楼主，我看了一下data/kenlm/下的文件是people_chars_lm.klm，看名字是基于字粒度的模型。在训练字粒度模型的时候文件格式需要将每个字都用空格隔开吗？谢谢楼主

**Comment by shibing624** [comment]
1. 更新的margen_median是为了提高计算速度
2. rnn_lm的模型可以自己训练，未公布是由于我评估发现该模型效果差，远比不上统计语言模型，优化到比统计语言模型效果好再公布，不然没有意义
3. 每个字都用空格隔开

**Comment by tianyunzqs** [comment]
@shibing624 楼主，y_score = ratio * margin_median / med_abs_deviation 这个是什么含义呢？出于什么考虑呢？有点没明白

**Comment by tianyunzqs** [comment]
@shibing624 
margin_median是每个字得分偏离总体中位数的绝对误差
med_abs_deviation是margin_median的中位数
但是margin_median / med_abs_deviation代表的是什么意思呢？
望楼主赐教！！！

**Comment by superdu12138** [comment]
rnn_lm 目前训练是占用CPU，能让它调用GPU训练吗？我让它训练，导致重启了。。
