### ISSUE TITLE
关于动态 纠错过程

### ISSUE THREAD

**Issue by codemayq** [shibing624/pycorrector#77]
# 感谢
非常感谢前辈的工作，搭建了一个纠错的典型pipeline，带来了很多指导。（下午我也给项目提了一个优化 numpy计算的PR）

# 问题
不过我在阅读以下源码的过程中也发现了部分问题，

```python
    def correct(self, sentence):
       ········
        # trick: 类似翻译模型，倒序处理
        maybe_errors = sorted(maybe_errors, key=operator.itemgetter(2), reverse=True)
        for item, begin_idx, end_idx, err_type in maybe_errors:
            # 纠错，逐个处理
```

将可疑的位置倒序，但实际处理的时候，只会将已经改过的句子用于计算下一个可疑的位置的PPL，只有这个先后顺序的依赖关系。

# 动态多轮方式
是否有一种动态的修改方式是，先分词一遍，得到分词结果，然后根据当前算法，只修改一处嫌疑最大的地方。然后把修改完的句子，再继续走相同的流程（分词，找错，纠错），直到不需要有任何的修改。

# 效果与需求
这样的效果也不知道是会带来提升或者下降，需要进一步实验。

但是有个问题可以解决，就是能解决纠错候选必须长度与原词相同的问题，比如 “今天我的快递包怎么还没有倒” 可以修改成 “今天我的快递包裹怎么还没有到”（快递包  -》 快递包裹）。因为按照目前的处理过程，下标必须是严格一一对应的，原来多少长度，改完也是多少长度, 如果在同一轮里同时先检测可疑，再修改多处，就有可能引起下标混乱。

**Comment by shibing624** [comment]
可以用动态规划改进，这就是查错和纠错一体的做法了，目前是查错和纠错分开的步骤。

**Comment by shibing624** [comment]
有意义的建议，可以调研效果。
