### ISSUE TITLE
请问有提供bert预训练模型吗？

### ISSUE THREAD

**Issue by alderpaw** [shibing624/pycorrector#78]

**Comment by JohnParken** [comment]
作者有提供，到bert文件夹下面去找就可以

**Comment by superdu12138** [comment]
请问大家是如何自己预训练BERT模型的，在我下载谷歌BERT模型后
运行
python3 pregenerate_training_data.py 
--train_corpus people2014_cged_wiki.txt 
--bert_model 'bert-base-chinese' {chinese_L-12_H-768_A-12/vocab.txt}  ②
--do_lower_case --output_dir training/ 
--epochs_to_generate 3 --max_seq_len 256

在②中  如果我缺少bert-base-chinese
![image](https://user-images.githubusercontent.com/20619835/63018265-fdaaa100-beca-11e9-9f7e-7b57ce9c592e.png)

它会提示我添加它。但是当我添加后 它会提示我chinese_L-12_H-768_A-12/vocab.txt}  
需要一个参数 pregenerate_training_data.py: error: unrecognized arguments: {chinese_L-12_H-768_A-12/vocab.txt}

忽略这个大括号，添加不添加都是提示我这个错误。

**Comment by Growing-bison** [comment]
那个项目的issue有解决思路。如果是国内网络，需要在代码中指定model载入路径，本地载入

**Comment by superdu12138** [comment]
> 那个项目的issue有解决思路。如果是国内网络，需要在代码中指定model载入路径，本地载入

我换成绝对路径还是不行

**Comment by shibing624** [comment]
用最新代码，已经release上了
