### ISSUE TITLE
seq2seq模型预测问题及评估方法

### ISSUE THREAD

**Issue by li-aolong** [shibing624/pycorrector#79]
没动源文件，进行训练，然后运行`infer.py`得到如下结果，为什么这么多重复的字呢
```
input: 少先队员因该给老人让坐 output: 少少先队员因该给老人让坐坐的坐康。
input: 少先队员应该给老人让坐 output: 少少先队员应该给老人让坐坐的坐势。
input: 而且人们之间中常常有问题的人是年轻人和老人。 output: 而而且人们之间中常常有问题的人是年轻人和老人。
input: 由我起开始做。 output: 由由我起开始做。
input: 由我起开始做 output: 由由我起开始做做做做。
input: 不能人类实现更美好的将来。 output: 不不能人类实现更美好的将来。
input: 这几年前时间， output: 这这几年前时间，须时间，
input: 歌曲使人的感到快乐， output: 歌歌曲使人的感到快乐，曲。
```

**Comment by shibing624** [comment]
1.seq2seq训练不足导致的，一般是拟合不足的常见现象，需要补充数据集用于深度模型训练。
2.最近我搜罗到lang8和HSK的中文纠错数据集，整理后共130万对数据，215MB左右，授权后开放出来供大家使用。
3. 以上数据使用seq2seq_attention模型，训练10轮后效果如下：
![seq2seq_atten_out](https://user-images.githubusercontent.com/10249622/62197469-78939800-b3b2-11e9-80f5-bd3e7cd82505.png)
效果稍好，M2的F0.5结果大概是0.3，达到业界先进水平。
4. 业界CGED纠错比赛如下：
<img width="674" alt="industry_out" src="https://user-images.githubusercontent.com/10249622/62197773-0c656400-b3b3-11e9-8f8b-91eff44f9ea9.png">

**Comment by zhangxiaofanL** [comment]
哇哇哇，跪求开放lang8和HSK的中文纠错数据集，万分感谢

**Comment by zhangxiaofanL** [comment]
能请问下
![image](https://user-images.githubusercontent.com/20238929/62198171-c0ff8580-b3b3-11e9-8bc9-be06ea00b0fd.png)这个是哪篇论文吗?

**Comment by HappyShadowWalker** [comment]
> 1.seq2seq训练不足导致的，一般是拟合不足的常见现象，需要补充数据集用于深度模型训练。
> 2.最近我搜罗到lang8和HSK的中文纠错数据集，整理后共130万对数据，215MB左右，授权后开放出来供大家使用。
> 3. 以上数据使用seq2seq_attention模型，训练10轮后效果如下：
> ![seq2seq_atten_out](https://user-images.githubusercontent.com/10249622/62197469-78939800-b3b2-11e9-80f5-bd3e7cd82505.png)
> 效果稍好，M2的F0.5结果大概是0.3，达到业界先进水平。
> 4. 业界CGED纠错比赛如下：
> <img alt="industry_out" width="674" src="https://user-images.githubusercontent.com/10249622/62197773-0c656400-b3b3-11e9-8f8b-91eff44f9ea9.png">

你好，这个什么时候会放出来呀

**Comment by shibing624** [comment]
release with v0.1.9  readme.

**Comment by li-aolong** [comment]
> release with v0.1.9 readme.

非常感谢

**Comment by li-aolong** [comment]
> release with v0.1.9 readme.

你好想问下，那些较大的数据集大概什么时候会放出来呢

**Comment by li-aolong** [comment]
> release with v0.1.9 readme.

NLPCC 2018 GEC官方数据集的trainingdata下下来是30.3MB，没有114.5MB

**Comment by shibing624** [comment]
fix size. the tar.gz is 30MB, the text is 114MB,

**Comment by li-aolong** [comment]
你好想问下，使用提供的语料训练完毕了，怎样能评测以下模型好坏呢？怎样计算精确率，召回率和M2值呢，我看那个m2scorer不太会用，好像还得给句子进行标注才能计算分数

**Comment by wulouzhu** [comment]
楼主，怎么计算精确率，召回率和M2值，能不能提供标准测试集和评估代码，感谢

**Comment by JohnParken** [comment]
楼主，seq2seq_attention的方法现在能超过统计方法的吗

**Comment by TabChenJlu** [comment]
> 1.seq2seq训练不足导致的，一般是拟合不足的常见现象，需要补充数据集用于深度模型训练。
> 2.最近我搜罗到lang8和HSK的中文纠错数据集，整理后共130万对数据，215MB左右，授权后开放出来供大家使用。
> 3. 以上数据使用seq2seq_attention模型，训练10轮后效果如下：
> ![seq2seq_atten_out](https://user-images.githubusercontent.com/10249622/62197469-78939800-b3b2-11e9-80f5-bd3e7cd82505.png)
> 效果稍好，M2的F0.5结果大概是0.3，达到业界先进水平。
> 4. 业界CGED纠错比赛如下：
> <img alt="industry_out" width="674" src="https://user-images.githubusercontent.com/10249622/62197773-0c656400-b3b3-11e9-8f8b-91eff44f9ea9.png">



> 1.seq2seq训练不足导致的，一般是拟合不足的常见现象，需要补充数据集用于深度模型训练。
> 2.最近我搜罗到lang8和HSK的中文纠错数据集，整理后共130万对数据，215MB左右，授权后开放出来供大家使用。
> 3. 以上数据使用seq2seq_attention模型，训练10轮后效果如下：
> ![seq2seq_atten_out](https://user-images.githubusercontent.com/10249622/62197469-78939800-b3b2-11e9-80f5-bd3e7cd82505.png)
> 效果稍好，M2的F0.5结果大概是0.3，达到业界先进水平。
> 4. 业界CGED纠错比赛如下：
> <img alt="industry_out" width="674" src="https://user-images.githubusercontent.com/10249622/62197773-0c656400-b3b3-11e9-8f8b-91eff44f9ea9.png">

我训练的结果在测试集合如下：
Precision : 0.1217
Recall : 0.1374
F_0.5 : 0.1245
和0.3差异巨大，不知道是否可以开放模型出来呢？

**Comment by li-aolong** [comment]
> > 1.seq2seq训练不足导致的，一般是拟合不足的常见现象，需要补充数据集用于深度模型训练。
> > 2.最近我搜罗到lang8和HSK的中文纠错数据集，整理后共130万对数据，215MB左右，授权后开放出来供大家使用。
> > 3. 以上数据使用seq2seq_attention模型，训练10轮后效果如下：
> > ![seq2seq_atten_out](https://user-images.githubusercontent.com/10249622/62197469-78939800-b3b2-11e9-80f5-bd3e7cd82505.png)
> > 效果稍好，M2的F0.5结果大概是0.3，达到业界先进水平。
> > 4. 业界CGED纠错比赛如下：
> > <img alt="industry_out" width="674" src="https://user-images.githubusercontent.com/10249622/62197773-0c656400-b3b3-11e9-8f8b-91eff44f9ea9.png">
> 
> > 1.seq2seq训练不足导致的，一般是拟合不足的常见现象，需要补充数据集用于深度模型训练。
> > 2.最近我搜罗到lang8和HSK的中文纠错数据集，整理后共130万对数据，215MB左右，授权后开放出来供大家使用。
> > 3. 以上数据使用seq2seq_attention模型，训练10轮后效果如下：
> > ![seq2seq_atten_out](https://user-images.githubusercontent.com/10249622/62197469-78939800-b3b2-11e9-80f5-bd3e7cd82505.png)
> > 效果稍好，M2的F0.5结果大概是0.3，达到业界先进水平。
> > 4. 业界CGED纠错比赛如下：
> > <img alt="industry_out" width="674" src="https://user-images.githubusercontent.com/10249622/62197773-0c656400-b3b3-11e9-8f8b-91eff44f9ea9.png">
> 
> 我训练的结果在测试集合如下：
> Precision : 0.1217
> Recall : 0.1374
> F_0.5 : 0.1245
> 和0.3差异巨大，不知道是否可以开放模型出来呢？

我得到的是：
```
Precision   : 22.87
Recall      : 21.68
F_0.5       : 22.62
```
