### ISSUE TITLE
不同语言模型的阈值

### ISSUE THREAD

**Issue by codemayq** [shibing624/pycorrector#80]
非常感谢作者的工作。
看作者的代码中，用了2-gram和3-gram来做detect，同时有一个阈值来控制是否可能是错的。

在这里我想请问一下，2-gram 和3-gram 出来的分数 是否本身的分布有所差异，比如3-gram就普遍偏高一点。 如果有这样的问题， 那么阈值是否是跟 n-gram的n选取有一定关系。

进一步扩展，如果用同样语料训练了一个 4-gram， 把这个模型也加入进来，用2,3,4 一起去打分，如果不修改其他，理论上会对结果产生什么影响。（是否需要更改阈值等）

**Comment by tianyunzqs** [comment]
@codemayq 我根据所训练的语言模型自动生成阈值，测试结果有较大波动，而且测试效果优于默认阈值

**Comment by shibing624** [comment]
1. 建议修改阈值，与n-gram模型的n选择有关。
2. 测试效果更测试数据和训练语言模型的样本数据都有关，建议在客观统一的样本测试集下评估，可以在CGED的测试集下给出评估结论。

**Comment by codemayq** [comment]
> @codemayq 我根据所训练的语言模型自动生成阈值，测试结果有较大波动，而且测试效果优于默认阈值

自动生成阈值是怎么生成呢？

**Comment by tianyunzqs** [comment]
> > @codemayq 我根据所训练的语言模型自动生成阈值，测试结果有较大波动，而且测试效果优于默认阈值
> 
> 自动生成阈值是怎么生成呢？

我是在训练语言模型的时候，计算出每个字的平均得分来设置阈值的，code可参考：
`import kenlm
import numpy as np

from tqdm import tqdm

lm = kenlm.Model(r'../pycorrector/data/kenlm/daily2014.kenlm.model')
scores = []
with open(r'../pycorrector/data/kenlm/wiki_daily_sentences_replace.txt', 'r', encoding='utf-8') as f:
    lines = f.readlines()
    for i, line in enumerate(tqdm(lines)):
        if i % 2 == 0 or not line.strip():
            continue
        line = line.strip()
        score = lm.perplexity(line)
        try:
            scores.append(score / len(line.split()))
        except:
            print(111)

# print(sorted(scores))
scores = np.array(scores)
ave = np.average(scores, axis=0)
print(ave)`

**Comment by shibing624** [comment]
可以借鉴，建议先对比效果。
