### ISSUE TITLE
Python版本支持

### ISSUE THREAD

**Issue by CornWu** [shibing624/pycorrector#82]
为什么限制Python2上不能安装？

**Comment by shibing624** [comment]
主流深度学习库tf, pytorch 等不支持Python2，我个人也由于编码问题不爱用python2。

之前我们曾报道过 Python 2.7 将于 2020 年退休的消息，随着该时间节点的临近，已陆续有一大批 Python 项目宣布将在 2020 年之前放弃对 Python 2.7 的支持，包括 pandas、Zulip、IPython、NumPy 等等。
