### ISSUE TITLE
Bert finetune chinese corpus 是否必须要有标题？

### ISSUE THREAD

**Issue by OctHex2016** [shibing624/pycorrector#84]
我有很多中文作文，应该怎样变成chinese corpus？一编作文？还是一行一段？
我试了用我的corpus去做fine-tune3轮，效果很差，比本身你供使用以上方法fine-tune3轮后的中文bert模型差很多。求指教，感谢！

**Comment by shibing624** [comment]
1. 每篇作文以空行间隔，表示不同的领域及语义，或称为doc
2. 作文的段落切换正常用换行表示
3.数据量需要足够，可以加到我提供的人民日报后面。
4.中文文本不需要手动切词，bert模型会自动以字切分的。

**Comment by OctHex2016** [comment]
謝謝你，我試一下

**Comment by HonayKing** [comment]
@shibing624 
我自己实现了下fine-tune过程，测试后发现效果比较差，能否提供下fine-tune的代码片段或思路？
谢谢！

**Comment by OctHex2016** [comment]
已了解和明白了，謝謝！
