### ISSUE TITLE
rnn_lm文件是如何纠错的

### ISSUE THREAD

**Issue by superdu12138** [shibing624/pycorrector#86]
你好，我今天测试rnn_lm模型。我运行了preprocess.py   train.py ,最后我测试python  infer ，在begin_char = ’少先队员该应为老人让座‘，输出并没有纠正。这模型的纠错在哪里。 该项目的demo环境用的是kenlm模型， 在检错上用的也不是rnn_lm,我觉得rnn_lm应该是有一套自己的纠错吧？现在还未找到。 我现在想测试各个模型在纠错上的效果，运用深度学习模型的，现在最好效果是哪个模型呢？

**Comment by JohnParken** [comment]
rnn 纠错需要在 pycorrector/detector.py文件中将 enable_rnn 设为True

**Comment by shibing624** [comment]
see https://github.com/shibing624/pycorrector/issues/74

**Comment by superdu12138** [comment]
> 见[＃74](https://github.com/shibing624/pycorrector/issues/74)

bert在哪里？？ 
deep context文件夹下
train.py
for iterator in dataset.get_batch_iter(batch_size):  这语句到底要循环多久？？
都没有输出，这有意义吗？

**Comment by shibing624** [comment]
..........
