### ISSUE TITLE
关于deep_context模型

### ISSUE THREAD

**Issue by superdu12138** [shibing624/pycorrector#88]
你好，我在这个模型下运行  python3  preprocess.py  然后运行 python3 train.py
页面一直就是这样
![2019-08-12 14-31-21屏幕截图](https://user-images.githubusercontent.com/20619835/62848578-e030d800-bd0e-11e9-80f0-435d42dcb25d.png)

**Comment by superdu12138** [comment]
可以跑，但是跑一次太久了。。。

**Comment by shibing624** [comment]
rnn训练速度慢，如果需要中间步骤提示，可以自行添加。默认是one epoch 输出一次。

**Comment by superdu12138** [comment]
deep_contexty已经跑完了，没有中间步骤第一次训练时被我pass掉几次

/Downloads/NLPcorrect/pycorrector-master_ddd/pycorrector/rnn_attention
/Downloads/NLPcorrect/pycorrector-master_ddd/pycorrector/rnn_crf
/Downloads/NLPcorrect/pycorrector-master_ddd/pycorrector/transformer
/Downloads/NLPcorrect/pycorrector-master_ddd/pycorrector/utils
我在08.08号这天下载的项目，关于这4个模型 ，他们是还没有纠错功能吧？我在各infer.py下没有看到测试句子

**Comment by shibing624** [comment]
rnn_attention
rnn_crf
transformer
是有纠错效果的。
