### ISSUE TITLE
关于词粒度的语言模型

### ISSUE THREAD

**Issue by alderpaw** [shibing624/pycorrector#90]
把模型路径直接改成加载词粒度的语言模型的话，纠错效果会很差。请问如果要使用词粒度的语言模型的话是不是需要进行一些修改呢？

**Comment by superdu12138** [comment]
你应该让它跑起来，就是自己训练一下

**Comment by cjwang666** [comment]
现有代码只支持字粒度的语言模型。
所以，如果把模型路径直接改成加载词粒度的语言模型的话，纠错效果会很差。

**Comment by shibing624** [comment]
1. 是，考虑到词语用错的情况少，而且词粒度语言模型纠错效果差，故没有发布到开源代码中。
2. 纠错场景下，句子本身切词会出错，词粒度语言模型无法较好应用到错误点。
