### ISSUE TITLE
bert模型是如何工作的？

### ISSUE THREAD

**Issue by superdu12138** [shibing624/pycorrector#91]
hi， 我在bert/bert_corrector.py  下有这样两句代码：
                                   outputs = self.model(input_ids, segment_ids)
                                   predictions = outputs[0]
我尝试输出   print(predictions)，发现model是根据每次获取的文本的id  来产生一个列表
![image](https://user-images.githubusercontent.com/20619835/63242387-cbfa5700-c289-11e9-816f-7aa76e669804.png)

根据句子错误字的位置来获取某一列或者行的值
![image](https://user-images.githubusercontent.com/20619835/63242478-1bd91e00-c28a-11e9-9e09-9218afd717e5.png)
输出该张量最大值，一般都能输出我们想要的改正确的字。

所以，关键的在于 我们原始文本传给模型后 ，它是如何输出给我们的？ 解析文章只笼统说是基于上下文，有人知道它是怎样工作的吗？

**Comment by superdu12138** [comment]
chinese_L-12_H-768_A-12模型 跟 bert-base-chinese 模型  哪个更适合纠错呢？

**Comment by shibing624** [comment]
类似RNN语言模型对下一个词的预测，通过上文预测下一个词对应vocab词表中所有词的似然概率，BERT是对MASK标识的位置做出预测。

**Comment by superdu12138** [comment]
> 类似RNN语言模型对下一个词的预测，通过上文预测下一个词对应vocab词表中所有词的似然概率，BERT是对MASK标识的位置做出预测。

如果MASK位置是0 ，(假设是图一)那获取的tensor是[-7.4224，-7.4055， -7.4691.....]從中选取最大值如 -7.4055  后续是转换成数字ID，从vocab表里找id对应的汉字， 如 大阳 ，太阳  ，太：1922，
想知道的是 除了MASK获取的  0  行， 其他列或行是在干什么。通过上文预测下一个词对应vocab词表中所有词的似然概率 ：   为什么我想要的纠错结果正好（在大列表中）对应MASK标记的位置，
如果MASK为6 ，那代码是取出大列表位置为6 对应的张量的。 但列表的行数或列数又比我输入检测文本要多得多，，恩？ 除了MASK获取的  i  行， 其他列或行是在干什么的？

self.model                       我找不到model，它是指向了你提供的预训练模型的bin文件吗？
 不知道我去阅读BERT源码能否解决

**Comment by superdu12138** [comment]
bert 对应的
README.md 的指令是不是过时了？我并不能完整运行，我是用Github上的指令实现预处理的，但在接下来的微调出了问题。不过我现在跑向传统方向了，先看看有没有更好的方式

**Comment by shibing624** [comment]
fine-tune的方法欢迎留意官方库的链接https://github.com/huggingface/pytorch-transformers， 指令大同小异。
