### ISSUE TITLE
python train.py时出问题

### ISSUE THREAD

**Issue by wfchenwf** [shibing624/pycorrector#93]
input:科学的发展会带来我们极好的生活。
output:UNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNKUNK
Epoch 4/40
2/2 [==============================] - 0s 71ms/step - loss: 4.6443 - val_loss: 4.8314
input:吸烟的行为经常会影响社会里所有的人。
output:的的UNK的的的。。。
input:科学的发展会带来我们极好的生活。
output:UNKUNKUNKUNKUNKUNKUNKUNK。。
Epoch 5/40
2/2 [==============================] - 0s 69ms/step - loss: 4.6282 - val_loss: 4.8040
input:吸烟的行为经常会影响社会里所有的人。
output:的的UNK的的的的。。。
input:科学的发展会带来我们极好的生活。
output:UNKUNKUNKUNKUNKUNKUNKUNKUNKUNK。。
Epoch 00005: early stopping

请问各位大佬这是怎么回事儿？

**Comment by Micla-SHL** [comment]
还在训练，着啥急

**Comment by chendeming** [comment]
> 还在训练，着啥急

什么意思？我也是显示“UNKUNKUNKUNKUNKUNKUNKUNKUNKUNK”

**Comment by shibing624** [comment]
训练数据改为大的数据量。
