### ISSUE TITLE
我觉得语言模型 获取候选集的方法是错误的

### ISSUE THREAD

**Issue by Micla-SHL** [shibing624/pycorrector#95]
我去掉了同音字和困惑集，只保留了相似字。但是代码使用get()方法 获取，我觉的不好，效果很差。我以为找候选字 是找到 key 从而找key的候选 。格式是这样的 ： key/t/候选字/t候选字/t  
但在实际操作种， 它有可能返回的：  假设找 亲 的候选字 ，它返回 ：  key/t/哦/t打/t亲/t骄/t十
它返回了： key 哦 打 骄 十，但我想要的是返回 亲/t/答/t/腌/t/圣/t搭  。我想要它返回 答 腌 圣 塔
，我觉得这样才是符合逻辑的。所以我觉得问题主要出错在get(方法上)，我将重新找个函数替代它

**Comment by superdu12138** [comment]
def load_same_stroke(path, sep='\t'):
    """
    加载形似字
    :param path:
    :param sep:
    :return:
    """
    result = dict()
    if not os.path.exists(path):
        logger.warn("file not exists:" + path)
        return result
    with codecs.open(path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line.startswith('#'):
                continue
            parts = line.split(sep)
            if parts and len(parts) > 1:
                for i, c in enumerate(parts):
                    result[c] = set(list(parts[:i] + parts[i + 1:]))
    return result

作者 corrector.py  这函数出了问题

**Comment by shibing624** [comment]
1.测试代码无问题。
2.基本逻辑是相似的返回结果不包括它本身。
