### ISSUE TITLE
transformer模型只能在CPU中跑？

### ISSUE THREAD

**Issue by Lavine24** [shibing624/pycorrector#96]
opennmt-tf 是最新版本(1.24.1)的，tensorflow装的也是GPU版本的，但是默认就是在CPU上跑了，不会报错，就是特别慢，不知道是什么问题。另，服务器中的GPU跑其他代码是没有问题的，不知道为什么跑不了这个。
![捕获](https://user-images.githubusercontent.com/31796893/64485720-772d7900-d256-11e9-8db9-b55eab4ca776.PNG)

**Comment by zixufang** [comment]
我也发现这个问题了，请问您解决了吗？

**Comment by Lavine24** [comment]
> 我也发现这个问题了，请问您解决了吗？

还没有解决这个问题，我发现这里边的模型好多都是只在CPU里边跑，在GPU里边跑不了。

**Comment by areaChun** [comment]
我发现conv_seq2seq也是，运行sh train.sh原参数，nvidia-smi在GPU上没看到进程，1个epoch非常慢

**Comment by shibing624** [comment]
conv_seq2seq 是可以在GPU跑的，正确设置GPU_ID即可。

**Comment by shibing624** [comment]
> > 我也发现这个问题了，请问您解决了吗？
> 
> 还没有解决这个问题，我发现这里边的模型好多都是只在CPU里边跑，在GPU里边跑不了。

opennmt-tf 是原模型我没找到在GPU上运行的支持方法。所有的模型我都尽量支持在GPU上跑的呀，您说好多不能，可以列举一下吗？有GPU代码贡献欢迎提交pr。
