### ISSUE TITLE
改造意见咨询

### ISSUE THREAD

**Issue by codemayq** [shibing624/pycorrector#98]
前辈好，

非常感谢前辈的工作，不过我在使用该工具的时候，也发现了一些问题，比如如何主动保护误纠（包括人名地名不纠错更好，如何自定义定向纠错）、性能瓶颈优化、动态规划、阈值的选取等，改动会比较大。

所以我打算在此库基础上在自己账号下新开一个库，删除一些实验性的代码，然后把这些实际的feature加进去，具体的时间也待进一步规划。

当然该项目也是同样开源和非商业的，也会引用和说明此库的出处。

所以也在这里征求一下前辈的意见。

**Comment by shibing624** [comment]
fork 即可。
