### ISSUE TITLE
关于linux下安装kenlm的报错

### ISSUE THREAD

**Issue by sadxiaohu** [shibing624/pycorrector#99]
你好，我在linux环境下按照说明中的方法(pip install pycorrector)安装相关模型，但是安装kenlm模型时一直报错，网上也无相关教程，请问这部分是怎么安装的？感谢！！！

**Comment by shibing624** [comment]
https://blog.csdn.net/mingzai624/article/details/79560063 我之前写的教程。

**Comment by sadxiaohu** [comment]
你好前辈，这个我看了，但是我用的是ubuntu系统，而且是学校实验室的集群，没有root没法安装这些，搞了一下午快崩溃了。



胡作海


 




------------------ 原始邮件 ------------------
发件人: "xuming"<notifications@github.com>;
发送时间: 2019年10月22日(星期二) 晚上7:39
收件人: "shibing624/pycorrector"<pycorrector@noreply.github.com>;
抄送: "永远有多远"<401983099@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [shibing624/pycorrector] 关于linux下安装kenlm的报错 (#99)




https://blog.csdn.net/mingzai624/article/details/79560063 我之前写的教程。

**Comment by shibing624** [comment]
会用docker吗？安装一个，docker run -i -t ubuntu bash ，容器中使用ubuntu就ok，然后再pip3 install pycorrector

**Comment by sadxiaohu** [comment]
> 会用docker吗？安装一个，docker run -i -t ubuntu bash ，容器中使用ubuntu就ok，然后再pip3 install pycorrector
不会用诶，网上差了一下，是不是docker安装也需要root呢？我去前辈提供的网站看了一下，想注册一个账号通过接口调用服务，但是现在貌似没法注册了

**Comment by sadxiaohu** [comment]
> 会用docker吗？安装一个，docker run -i -t ubuntu bash ，容器中使用ubuntu就ok，然后再pip3 install pycorrector

不会用诶，网上差了一下，是不是docker安装也需要root呢？我去前辈提供的网站看了一下，想注册一个账号通过接口调用服务，但是现在貌似没法注册了

**Comment by shibing624** [comment]
嗯，不提供注册了，网站本质上是个演示平台而已，仅用于炫技。。。

**Comment by shibing624** [comment]
pip install https://github.com/kpu/kenlm/archive/master.zip

**Comment by sadxiaohu** [comment]
> pip install https://github.com/kpu/kenlm/archive/master.zip

哇塞！可以了！神奇！感谢前辈！前辈现在还在百度吗

**Comment by shibing624** [comment]
在
